### ISSUE TITLE
Translation to Indonesian

### ISSUE THREAD

**Issue by thickkoezz** [javascript-tutorial/en.javascript.info#1000]
Hello, @iliakan. I'd like to take over the translation to Bahasa Indonesia because the existing translation is stalled and the previous maintainers doesn't respond at all.

**Comment by iliakan** [comment]
Where's the existing translation?

**Comment by iliakan** [comment]
I can't see anything done in https://github.com/iliakan/javascript-tutorial-id.

I created a new translation and added you as a maintainer :

**Comment by purwnt** [comment]
Hello, @iliakan. Currently I'm contributor for id.javascript.info and I would like to help @thickkoezz to maintain translation to Bahasa Indonesia. May I join javascript-tutorial organization to help and speed up translation progress for Bahasa Indonesia.

**Comment by iliakan** [comment]
@purwnt Added you as a contributor (I belive, @thickkoezz agrees)

**Comment by purwnt** [comment]
Sure, I already discussed it with @thickkoezz
