### ISSUE TITLE
a display issue

### ISSUE THREAD

**Issue by AM-77** [javascript-tutorial/en.javascript.info#1002]
in: https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/02-first-steps/04-variables/article.md

![Screenshot_2019-05-21 javascript-tutorial en javascript info](https://user-images.githubusercontent.com/18232579/58081517-7f817b80-7bb5-11e9-96e4-a0773aa1695e.png)

**Comment by iliakan** [comment]
That's github, not site.
