### ISSUE TITLE
There is an error in the code sample at "Object methods, this" page

### ISSUE THREAD

**Issue by nexus3a** [javascript-tutorial/en.javascript.info#1031]
Dear Javascript.info team,
I have found a little typo(?) in the code sample at https://javascript.info/object-methods#method-shorthand

There are two declarations of the same variable: 
// these objects do the same
let user = ...;
let user = ...

Perhaps the code should be like this:
// these objects do the same
let userA = ...;
let userB = ...

Or like this:
// before code beautifying...
let user = ...;
// ... and after code beautifying
user = ...

Best regards,
Aleksei Andreev

**Comment by iliakan** [comment]
It wasn't runnable code, but I removed `let`.
