### ISSUE TITLE
"=" typo at "Object methods, this" page

### ISSUE THREAD

**Issue by nexus3a** [javascript-tutorial/en.javascript.info#1032]
Dear Ilya, I have found one more typo(?) at page https://javascript.info/object-methods#this-is-not-bound:

Calling without an object: this=undefined
                                                |
                                               V
Calling without an object: this == undefined

I undersand, that equality sign used here "as equality", but we are in JavaScript-Education context, and using double-equality (as JavaScript equality) sign is better here, I think

**Comment by iliakan** [comment]
Please send a PR if the typo still exists (probably fixed)
