### ISSUE TITLE
Central Khmer Translation

### ISSUE THREAD

**Issue by Bunlong** [javascript-tutorial/en.javascript.info#1034]
Dear @iliakan , I would like to start the Central Khmer translation.

The code for Central Khmer is `km`
The maintainer is @Bunlong and I will add more maintainer later.

Thank you!

**Comment by iliakan** [comment]
What's your email?

**Comment by Bunlong** [comment]
My email is bunlong.van@gmail.com

**Comment by iliakan** [comment]
Done! Did you receive the invite?

**Comment by Bunlong** [comment]
Yes, I received the invitation. Thank you!
