### ISSUE TITLE
New chapter proposal - "JavaScript - the state of things"

### ISSUE THREAD

**Issue by dfedynich** [javascript-tutorial/en.javascript.info#1042]
I would like to propose a new chapter with the name like "**JavaScript - the state of things".** There are a few goals to describe in this chapter:

- explain the difference between JavaScript, ECMAScript and ECMA-262 (students are often confused with these terms)
- explain the difference between JavaScript engine and JavaScript runtime
- mention about the difference in browser support and the idea of Babel (_"Polyfills" chapter describes Babel very well, but it may deserve one more mention from cross-browsing support perspective_)
- mention about ES1, ES2...ES5, explain name collision starting from ES6 and ES2015 (two ways of naming a version), and what is ES.next
- some words about the workflow of JavaScript proposals

I think this chapter will take its own place in this gorgeous modern tutorial. The key goal is not to describe all the terms above in a thorough way, but take a look at JavaScript scene from a bird's-eye view and put everything right.

@iliakan, please, let me know what do you think about this proposal. I could compose the new chapter and create a pull request, if you find the idea worthwhile.

**Comment by iliakan** [comment]
Could you please consider the TODO list?
- Drag events
- History api
- Pointer events
- Touch events
- Canvas (2d graphics)
- Security (xsrf xss csp etc)

**Comment by dfedynich** [comment]
@iliakan, sorry, it seems that the chapter name misled you. Maybe the name should be changed to another one that reveal the idea in a cleaner way. I didn't want to describe any browser technologies of the Web platform. 

Here is the draft TODO list (sections)
- Relationship between JavaScript and ECMAScript (describe the list of necessary definitions such as ECMAScript, ECMA International, ECMA-262, JavaScript and relationship between them)
- ECMAScript editions (describe short history of the specification and mention about the changes in naming to reflect the year of release) 
- Differences in browser support (write about ECMAScript compatibility and explain in two words what a JavaScript engine is. Mention about Babel)
- Host environment (explain what is a JavaScript runtime)
- ECMAScript proposals (just briefly describe the general lifecycle for making changes to the specification according to TC39 Process)

**Comment by iliakan** [comment]
I'm not sure these topics are of much interest to people.
This is mostly historical information.

I mean, it might be interesting, but there are so much prioritized topics around there! Like mobile events for example, and others in the todo.

**Comment by dfedynich** [comment]
It makes sense.
