### ISSUE TITLE
Google Play Books fails processing .epub

### ISSUE THREAD

**Issue by cesc1989** [javascript-tutorial/en.javascript.info#1045]
Yesterday, I bought the three book package to read it using Google Play Books.

I could successfuly upload Part 2(DOM) but it failed for Part 1 and part 3.

![image](https://user-images.githubusercontent.com/1375981/59151195-720d2380-89f4-11e9-913b-64831cb24446.png)

Following suggestions from the _internets_ I could add the failing books to my GPB account by first converting them to `.mobi` using Calibre and then reconverting the book to `.epub` though the final result loses many of the nice formatting the book has.

**Comment by iliakan** [comment]
I'd like to look into that issue.

How can I debug the problem? Try it on my Mac?

**Comment by cesc1989** [comment]
Hi @iliakan the issue occurs with downloaded books I got after the purchase.

Everything I tried was done in **Linux Mint 19.1**

Whenever I tried to upload book 1 or 3 to google play books, it would never be successfully processed. I uploaded them using Chrome and Firefox and nothing changed.

I also scanned all books with [EPUB checker](http://validator.idpf.org/) online and [in the command line](https://github.com/w3c/epubcheck). Many errors would appear.

**Comment by jasonjurotich** [comment]
Did you try uploading it first to Google Drive and then pulling it from there?

**Comment by cesc1989** [comment]
> Did you try uploading it first to Google Drive and then pulling it from there?

Noooppp. I've never done it that way, have you? 🤔

**Comment by jasonjurotich** [comment]
just go to https://play.google.com/books and then click upload files and then try Google Drive. I have not used it, but it should work.

**Comment by iliakan** [comment]
We're using Calibre converter for Epub. It aims to create the most compatible Epub, but warns that it's impossible to be compatible with every reader.

**Comment by pigeeky** [comment]
This issue is not resolved yet. ePubs not working with Kindle too. Could someone suggest some workaround, or at least a compatible app?

**Comment by iliakan** [comment]
Calibre, iBooks
