### ISSUE TITLE
Something is missing here(2-ui/5-loading/02-script-async-defer/article.md)?

### ISSUE THREAD

**Issue by lycheeEng** [javascript-tutorial/en.javascript.info#1046]
Hello, I'm translating this article (2-ui/5-loading/02-script-async-defer/article.md)

It looks like the sentence below is incomplete (In article.md penultimate line)

> So, buttons should be disabled by CSS or by other means, to let the user

and the next line starts with `In practice, `defer` is used for...`, it looks like not a part of this sentence.

So, did you mean disable buttons to prevent users from getting confused when they click?

**Comment by iliakan** [comment]
Thanks, fixed!
