### ISSUE TITLE
One question about Map article.

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1050]
Hello, I'm a little bit confused about the sentence in the article, [Map, Set, WeakMap and WeakSet](http://javascript.info/map-set-weakmap-weakset), `For string keys, Object can be fine, but it would be difficult to replace the Map with a regular Object in the example above.`

I know that if all of the keys are string type, it'd be easy to replace Map with regular Object. But, I'm still confusing this part `For string keys, Object can be fine`.

Could you elaborate more?

**Comment by iliakan** [comment]
I added more explanations, please see the updated http://javascript.info/map-set-weakmap-weakset.

**Comment by Violet-Bora-Lee** [comment]
Awesome, really :) Thanks!
