### ISSUE TITLE
question regarding new Set(iterable)

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1051]
Hello, it's me again lol.

I'm reviewing my translation the article regarding Set.

Could you add some explanation the part I highlighted?

new Set(iterable) – creates the set, `optionally from an array of values` (any iterable will do).

**Comment by iliakan** [comment]
Thanks, your feedback is valuable. If something isn't clear for you, it's probably not clear for someone else as well.

I added more details.

**Comment by Violet-Bora-Lee** [comment]
Thanks :)
