### ISSUE TITLE
Typo in Async iterators and generators

### ISSUE THREAD

**Issue by juntaozeng** [javascript-tutorial/en.javascript.info#1055]
In two places, the term "iteraterable" was used when comparing Iterators and Async iterators.

- typo: "iteraterable" -> "iterable"
- spelling aside, since Symbol.iterator returns an iterator object, would it be more accurate to describe it as "Object method to provide iterator" instead?

https://javascript.info/async-iterators-generators#async-iterators

|       | Iterators | Async iterators |
|-------|-----------|-----------------|
| Object method to provide iteraterable | `Symbol.iterator` | `Symbol.asyncIterator` |

https://javascript.info/async-iterators-generators#summary

|       | Iterators | Async iterators |
|-------|-----------|-----------------|
| Object method to provide iteraterable | `Symbol.iterator` | `Symbol.asyncIterator` |

**Comment by iliakan** [comment]
Fixed, thanks!
