### ISSUE TITLE
New chapter proposal  - "CSS for JavaScript developer"

### ISSUE THREAD

**Issue by dfedynich** [javascript-tutorial/en.javascript.info#1056]
I would be glad to contribute to this chapter

What subjects would you like to include into the chapter? In my view, it's very subjective question. Here is one of possible visions of how "CSS for JavaScript Developer" may look like:
- box model
- measurement units
- positioning content
- CSS Layout
- CSS Selectors

@iliakan, could you reveal your own vision about this chapter? Are you really interested in creating this chapter in the english edition of your tutorial? I saw your similar chapter in Russian language. Would you like to compose this chapter in English from scratch or translate it from Russian and add some new subjects afterwards?

**Comment by iliakan** [comment]
The best would be to create it in English first.

Here's the old content (in Russian): http://learn.javascript.ru/css-for-js

The new chapter should cover at least that. But it may be restructured.

**Comment by iliakan** [comment]
Looks like no one's doing it, so closing.
