### ISSUE TITLE
Translate in Bangla

### ISSUE THREAD

**Issue by mmimonir** [javascript-tutorial/en.javascript.info#1062]
Language family- Indo-European
ISO language name- Bengali
Native name (endonym)- বাংলা
639-1- bn
639-2/T- ben
639-2/B- ben
639-3- ben

List of maintainers- Now Only Me.

**Comment by iliakan** [comment]
Sure! Have you got a contact email?

**Comment by iliakan** [comment]
Done

**Comment by mmimonir** [comment]
Please note this email- mmimonir.ctg@gmail.com
