### ISSUE TITLE
Some RegExp nuggets

### ISSUE THREAD

**Issue by aubergine10** [javascript-tutorial/en.javascript.info#1076]
First, thank you for maintaining this awesome resource - the chapter on RegExp just saved me a load of time tracking down an issue with `regexp.test()` (the `lastIndex` issue)!

I was initially reading the chapter searching for two things:

1. A regexp that matches _anything_
2. A regexp that matches _nothing_

I ended up googling for answers and came up with two which I think might be worthy of a mention in the book:

1. `[^]*` - match anything, and seemingly unique to the ES regexp implementation
2. `(?!)` - match nothing

I have no idea which page would be best suited for them, or even if that sort of thing would be desirable to include, but just thought I'd mention them :)

**Comment by iliakan** [comment]
match anything is a dot with `s` flag, won't do?
match nothing - [^\s\S] ?

**Comment by aubergine10** [comment]
Another match nothing (ES regexp implementation only): `/[]/`

I guess deciding factor will be which is fastest.

**Comment by iliakan** [comment]
There's match anything in the tutorial. I'm not sure about matching nothing =)
