### ISSUE TITLE
Text inside code blocks on github view

### ISSUE THREAD

**Issue by DouglasMV** [javascript-tutorial/en.javascript.info#1084]
I noticed that some articles.md files when visualized in github have some issues.
Some parts are inside a code block when they should'nt.

So far i have noticed it in the Map/Set/weakMap/WeakSet article:
![pic1](https://user-images.githubusercontent.com/32845487/60125364-07811500-9762-11e9-94c2-b219469a1887.PNG)

And the Destructuring Assignment article:
![pic2](https://user-images.githubusercontent.com/32845487/60125404-1ff12f80-9762-11e9-8808-547da7162a9a.PNG)

I know that in the website the visualization is ok and most people see it through there, but for people like me that are helping in the translation and have to open the article in a text editor it makes it a little bit frustrating, because the editor also treat it as a code block and doesn't highlight properly the headers, quotes, code blocks, etc.

**Comment by iliakan** [comment]
Maybe you missed the part about installing the tutorial server locally? It's much better to have it running and updating in real-time as you edit, than github.

**Comment by DouglasMV** [comment]
Yes i know, but i do this mst of the time at college in a PC that doesn't have Git or Node installed and i don't have Admin privileges.
But thats ok, was just wondering if it was possible to fix it without breaking the website view.
Thanks for the fast response.
