### ISSUE TITLE
Translate in Spanish

### ISSUE THREAD

**Issue by JavyMB** [javascript-tutorial/en.javascript.info#1093]
**Language family**        Spanish
**ISO language name:**  Spanish, Castilian
**Native name:**              Español
**639-1:**                         es
**639-2/T:**                     spa
**639-2/B:**                     spa
**639-3:**                        spa
**List of maintainers:**    For now only Me.

**Comment by iliakan** [comment]
There's a translation: https://github.com/javascript-tutorial/es.javascript.info
Could you please look at it, and maybe join? :)

**Comment by JavyMB** [comment]
Thank you ! @iliakan  I missed that one !
