### ISSUE TITLE
meaning of the comments in the article

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1107]
Hello :)
I'm reviewing the translation in the [article](http://javascript.info/strict-mode) regarding strict mode.

Among the sentences, I wonder the meaning of the comments in the sentence `Only comments may appear above "use strict".`

I've ran the code and I only saw the alert. But there are two comments inside the script.

**Comment by iliakan** [comment]
Otherwise, strict mode won’t get enabled.

**Comment by iliakan** [comment]
Reopen if needed please.
