### ISSUE TITLE
Translate in Vietnamese

### ISSUE THREAD

**Issue by hunghedu** [javascript-tutorial/en.javascript.info#1108]
**Language family:** Austroasiatic
**ISO language name:** Vietnamese
**Native name:** Tiếng Việt
**639-1:** vi
**639-2/T:** vie
**639-2/B:** vie
**639-3:** vie
**Maintainers:** For now only me

**Comment by iliakan** [comment]
Created! Got an invitation?
Would also be nice to add your contact email.
