### ISSUE TITLE
Translate in Polish

### ISSUE THREAD

**Issue by aleksanderkrauze** [javascript-tutorial/en.javascript.info#1113]
Language family: Indo-European
ISO language name: Polish
Native name: Język polski
ISO 639-1: pl
ISO 639-2/T: pol
ISO 639-2/B: pol
ISO 639-3 pol
List of maintainers: only me and myslef

**Comment by iliakan** [comment]
Done! Would also be nice to add a contact email.

**Comment by aleksanderkrauze** [comment]
Thanks. My email is alkoszczak@gmail.com.

**Comment by iliakan** [comment]
Added!
