### ISSUE TITLE
Like to translate to Sinhala language - si

### ISSUE THREAD

**Issue by sameerast** [javascript-tutorial/en.javascript.info#1120]
Would like to translate for the the Sri Lankan local community who really depend on language.

**Comment by iliakan** [comment]
Created! Have a contact email?

**Comment by iliakan** [comment]
Did you receive the invitation?

**Comment by iliakan** [comment]
Let me know if you're on it, or not.

**Comment by iliakan** [comment]
Guess, I'll have to remove this translation.
