### ISSUE TITLE
Greek Translation

### ISSUE THREAD

**Issue by pcrunn** [javascript-tutorial/en.javascript.info#1131]
i'd love to translate the ebook while on vacation, here are the required information

- Language Code: el (or Greek, Modern (1453-))
- List of maintainers: @pcrunn - pcrunn@pm.me

**Comment by iliakan** [comment]
Have contact email?

**Comment by pcrunn** [comment]
> Have contact email?

It's pcrunn@pm.me

**Comment by iliakan** [comment]
Translation created, invite sent, instructions in the readme. Happy translating!
