### ISSUE TITLE
confusion about properties and methods

### ISSUE THREAD

**Issue by Ooggle** [javascript-tutorial/en.javascript.info#1134]
I think there is a little mistake on this file :
2-ui/1-document/01-browser-environment/article.md

line 25 :
```
// global functions are accessible as properties of window
```

It should be a methods instead of properties no ?

full code :
```js run
function sayHi() {
  alert("Hello");
}

// global functions are accessible as properties of window
window.sayHi();
```

**Comment by iliakan** [comment]
okay, in js methods is a kind of properties, I'll change this.

**Comment by Ooggle** [comment]
Oh okay, thanks for the clarification.
