### ISSUE TITLE
<= and < inconsistensy in Coding Style

### ISSUE THREAD

**Issue by decorator-factory** [javascript-tutorial/en.javascript.info#1141]
In the pow(x, n) example in https://javascript.info/coding-style you jump back and forth between the condition "n>0" and "n>=0", and sometimes the error message doesn't match the condition. This is a very minor detail, but i think it might be confusing to some people.

**Comment by iliakan** [comment]
Where's that issue? Maybe send a PR? Thanks!

**Comment by juntao-dev** [comment]
In the case of the mismatching error message, I believe @decorator-factory  was referring to the code style image `code-style.svg`

![example](https://user-images.githubusercontent.com/52540738/63446930-733fdf80-c47e-11e9-8c97-50d2892b625e.jpg)

**Current**
```JS
if (n < 0) {
    alert(`Power ${n} is not supported,
        please enter an integer number, greater than 0`);
} 
```

**Expected**
```JS
if (n <= 0) {
    alert(`Power ${n} is not supported,
        please enter an integer number, greater than 0`);
} 
```

**Issue**
The alert message indicates that a positive integer number is expected and the alert message should display if `n=0`.

**Comment by iliakan** [comment]
Updated the pic. Ok now?

**Comment by iliakan** [comment]
Thank you btw!
