### ISSUE TITLE
Georgian translation

### ISSUE THREAD

**Issue by mariamitata** [javascript-tutorial/en.javascript.info#1144]
Hi, I would like to create a new translation for my language (Georgian).
Language code is - ka
My Github nick is - Mariamitata
Email - mtatanashvili@yahoo.com

**Comment by iliakan** [comment]
Is this still actual? Sorry for the delay.

**Comment by mariamitata** [comment]
Hello, thank you for your reply. Yes it is still actual. I would like to
start as soon as possible.

Best regards

Mariami

**Comment by iliakan** [comment]
The repository was created, you're invited to it 🎉 

If you have a public contact email, please tell it. Also please write in case of any questions.
