### ISSUE TITLE
[Closure] Function in if

### ISSUE THREAD

**Issue by mnurik** [javascript-tutorial/en.javascript.info#1145]
Solution says **The result is an error.**, but it runs ok and shows: Hello, John

**Comment by Sarratas** [comment]
Error is thrown in strict mode. Otherwise it runs without problems.

As per #982, strict mode is assumed to be enabled everywhere, but maybe there should be additional note? As of now it seems to cause some confusion.

**Comment by iliakan** [comment]
It's enabled everywhere by default.

I don't see a way to send a clear message about it in every example though.
