### ISSUE TITLE
Could add some explanation why we dont use `toGMTString()`?

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1153]
Hello. I'm translation the [article about cookie](http://javascript.info/cookie)

Could you add some explanation use the article by mdn about toGMTString?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString

It'd be awesome then.

Thanks

**Comment by iliakan** [comment]
Hi,

Why the information about this deprecated method should ever be in the tutorial? :)

**Comment by Violet-Bora-Lee** [comment]
Good point :) the reason i asked comes from this sentence.

`The date must be exactly in this format, in GMT timezone.`

It's alright not to mention the method but i thought it could be more helpful to mention :)

**Comment by iliakan** [comment]
Usually we do not mention deprecated methods, unless there's a strong reason to do it (e.g. widely used in the old code).

**Comment by Violet-Bora-Lee** [comment]
I understand now :) Thanks for your reply. I'll close the issue

**Comment by iliakan** [comment]
Did you actually mean to add explanations about https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString ?

**Comment by Violet-Bora-Lee** [comment]
Nope. I just wondered why we use the method, toUTCString althought we want to change the format into GMT

**Comment by 1van0v** [comment]
@Violet-Bora-Lee maybe this [link]( https://www.nhc.noaa.gov/aboututc.shtml) can help you. Here are quotes related to your question:
>... time based on the 0° longitude meridian, also known as the Greenwich meridian.

> Prior to 1972, this time was called Greenwich Mean Time (GMT) but is now referred to as Coordinated Universal Time or Universal Time Coordinated (UTC)

Thus, I would say that there is no difference between GMT and UTC in the current context.

**Comment by iliakan** [comment]
![image](https://user-images.githubusercontent.com/349336/61767708-cece6d00-aded-11e9-91fd-34aaeb48875e.png)

**Comment by iliakan** [comment]
There's such a mention.
