### ISSUE TITLE
Translate in Chinese

### ISSUE THREAD

**Issue by jinggoing** [javascript-tutorial/en.javascript.info#1160]
Language family: Sino-Tibetan
ISO language name: zh-cn
Native name: 中文
ISO 639-1: zh
ISO 639-2/T: zho
ISO 639-2/B: chi
ISO 639-3 zho + 13
Maintainers: For now only me

**Comment by iliakan** [comment]
https://github.com/javascript-tutorial/zh.javascript.info ?
