### ISSUE TITLE
error.js File does not exist in cors. subdomain

### ISSUE THREAD

**Issue by mootookoi** [javascript-tutorial/en.javascript.info#1161]
In [http://javascript.info/onload-onerror#crossorigin-policy](http://javascript.info/onload-onerror#crossorigin-policy), the error.js file which is supposed to be present in [https://cors.javascript.info/article/onload-onerror/crossorigin/error.js](https://cors.javascript.info/article/onload-onerror/crossorigin/error.js) does not exist.
It is present in [https://javascript.info/article/onload-onerror/crossorigin/error.js](https://javascript.info/article/onload-onerror/crossorigin/error.js).
So, examples do not work.
PS: do not forget to sent crossorigin relative headers from cors. subdomain.

**Comment by iliakan** [comment]
Good catch!

Fixed now.

P.S. Not sure why crossorigin headers are needed there, anything fails without them?

**Comment by mootookoi** [comment]
I am a complete noob at this.
I just simply repeated what I read in your magnificient tutorial.

> To allow cross-origin access, the <script> tag needs to have crossorigin attribute, plus the remote server must provide special headers.
