### ISSUE TITLE
elem.classList.toggle("class") also returns value based on class added/removed

### ISSUE THREAD

**Issue by nikhilmandlik** [javascript-tutorial/en.javascript.info#1165]
issue: doc update/correction (minor)
url: https://javascript.info/styles-and-classes
section: className and classList
line: elem.classList.toggle("class") – adds the class if it doesn’t exist, otherwise removes it.

Actually it returns value based on given class added/removed. :)

**Comment by iliakan** [comment]
Does anyone ever use that value?
