### ISSUE TITLE
Java Script Tutorial Task Solution is problematic

### ISSUE THREAD

**Issue by MickyLee3** [javascript-tutorial/en.javascript.info#1170]
Re https://javascript.info/ifelse
The task solution for "Rewrite 'if' into '?'" is:

result = (a + b < 4) ? 'Below' : 'Over';

This failed because I had included "Use Strict" at the beginning.  When I commented it out, the solution worked. 

When I included "Use Script" and added "Let" just before result, it worked:

Let result = (a + b < 4) ? 'Below' : 'Over';

I was confused at first.  It's a little early in the tutorial to be introducing that, I think.  But I learned something.

**Comment by iliakan** [comment]
Ok fixed.
