### ISSUE TITLE
`this` is defined

### ISSUE THREAD

**Issue by luc4leone** [javascript-tutorial/en.javascript.info#1179]
Hi @iliakan :)

there is this snippet in `/1-js/04-object-basics/04-object-methods/article.md` where you explain the advance topic of "Reference Type":

```js
let user = {
  name: "John",
  hi() { alert(this.name); }
}

// split getting and calling the method in two lines
let hi = user.hi;
hi(); // Error, because this is undefined
```

I run the code above through the debugger, to better understand what happens. `this` does not seem to be `undefined`. `this` seems to be the global object `window`, that has not a `name` property, that's why we get `undefined`.

<img width="866" alt="Screenshot 2019-07-23 17 56 13" src="https://user-images.githubusercontent.com/2797254/61727222-37c4cf00-ad73-11e9-8148-b179ffbe3b3d.png">

**Comment by iliakan** [comment]
You forgot use strict.

**Comment by luc4leone** [comment]
Let me give you a short feedback _as a student of your tutorial_ @iliakan. Hopefully my feedback will help you improve your already incredibly excellent tutorial. 

First off the "Internals: Reference Type" section is a **great** section. I'd like to see more of that in-depth explanations of the language feature.

The "global vs undefined" concept has being an unnecessary complication in the line of explanation – again, my opinion as a student trying to make sense of the section.

Another source of difficulty has been the "loosing `this`" concept, which is often repeated during the explanation. 

The main point of the section is to understand what happens to `this` in different forms of call syntax. For this purpose, the "Reference type" language feature is introduced.

Let's get back to the example I mentioned above.

```js
let hi = user.hi
hi();
```

Let's focus on `hi()`. Why `this` is not `user`? That's the whole point I guess. And this point is totally independent from the code being or not in strict mode.

The whole point is that `this` is determined by the value we have on the left side of the calling parantheses. `hi` will result in a Reference type, because that's a rule of the language: an identifier always results in a Reference type. Then `this` will be the `base` of the Reference type, **regardless** of the base being `undefined` or `window`, meaning regardless of the code being or not in strict mode.

Let's see also this different call syntax:

```js
(user.name == "John" ? user.hi : user.bye)();
```
 
Why in this case`this` will not be `user`? The condition is `true`, so we have to focus on `user.hi`. It will result in a Reference type, that's the language rule: an object property accessor results in a Reference type. And the `base` will be `user`. So then one would expect `this` to be `user` but that's not the case,  because the result of the conditional is `GetValue(ReferenceType)`, not a Reference type. When on the left of call parentheses there is a value that's not a Reference type, `this` will be set to `null` to `window` or `undefined` (if we are in strict mode). 

Again, what I am trying to say is that being in strict mode or not is not the point. Moreover `this` is never lost (even if I eventually understood what you meant by this, I think it might be confusing).

That's it @iliakan 😊 

PS: I am not sure 100% what I wrote above is correct. It's been possible for me to write this comment, only after I read the tutorial section and the ECMA documentations at least 10 times. Which is good, so thank you 😉
