### ISSUE TITLE
Change "Debugging in Chrome" to "Debugging in your browser" or "Debugging in the browser"

### ISSUE THREAD

**Issue by scheinercc** [javascript-tutorial/en.javascript.info#1183]
Moving every novice to Chrome just because it is easier for the pros seems rather counter productive for an open web. Is it feasible to at least have an optional "Debugging in Firefox"  page (ideally also "Debugging in Safari" I guess!? We don't have to worry about Edge in this case anymore as this engine incl its tools is lost)?

Maybe a "Choose your browser" cross section with the different "Debugging in ..." behind?

Or at least change the headline to "Debugging in your/the browser" to not emphasis / advertise for one vendor so much and address in the description that Chrome is used here as an example + explicitly help novice devs to find alternative sources easily, by lining to them, like
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_a_breakpoint
https://mozilladevelopers.github.io/playground/debugger/
https://support.apple.com/en-au/guide/safari-developer/devd24689f72/mac
etc.

**Comment by iliakan** [comment]
Other browsers are alike, that's mentioned.

**Comment by scheinercc** [comment]
I think the brand "Chrome" gets a lot of emphasis and could be at least minimal toned down to "browser".

**Comment by scheinercc** [comment]
Just stumbled upon that page again and I still think the title should at least be changed to "Debugging in the browser".

The second paragraph points out which browser will be used in the examples anyway
"We’ll be using Chrome here, because it has enough features, most other browsers have a similar process."

**Comment by iliakan** [comment]
Yep. Done.
