### ISSUE TITLE
Does async block rendering?

### ISSUE THREAD

**Issue by panablue** [javascript-tutorial/en.javascript.info#1191]
[This page](https://javascript.info/script-async-defer) says:

> Both async and **defer** have one common thing: they **don’t block page rendering**.

My understanding - older, but as illustrated [here](https://bitsofco.de/async-vs-defer/) and [here](https://www.growingwiththeweb.com/2014/02/async-vs-defer-attributes.html) - is that `async` does block parsing/rendering if the file downloads (and then immediately executes) before parsing/rendering is complete.

(For initial rendering performance, unless a `<script>` has to be run as soon as possible, I generally prefer `defer` and avoid `async` for this reason.)

Which is correct? Or am I misunderstanding?

**Comment by iliakan** [comment]
You mean if the script is cached?

**Comment by panablue** [comment]
Or a small, quickly-downloaded file. Even if very brief, I thought that technically `async` can/will interrupt rendering to execute.

**Comment by iliakan** [comment]
@panablue Did you test it? Make a cached script with a long for loop. Does it block? In all browsers?

**Comment by panablue** [comment]
Not recent, but it looks like [someone already did](https://stackoverflow.com/questions/22294131/script-element-with-async-attribute-still-block-browser-render).

As far as I can tell this is well established. I find numerous sources - including the [WHATWG spec](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element) graphic - that clearly state `async` blocks/pauses rendering and so far no other sources that suggest `async` does not block rendering.

It's often also noted (including in the first link above) that even if downloaded in the background, all JavaScript execution blocks rendering. (If executed before rendering is complete, obviously. And of course `defer` specifically waits until rendering is complete.)

**Comment by iliakan** [comment]
Fixed.
