### ISSUE TITLE
defer & DOMContentLoaded

### ISSUE THREAD

**Issue by panablue** [javascript-tutorial/en.javascript.info#1192]
[This page](https://javascript.info/onload-ondomcontentloaded) says:

> Scripts with async, **defer** or type="module" **don’t block DOMContentLoaded**

While [this page](https://javascript.info/script-async-defer) says:

> Scripts with **defer** always execute when the DOM is ready, but **before DOMContentLoaded event**.

Is there an inconsistency here or am I just misunderstanding?

**Comment by iliakan** [comment]
Right, thanks, the second explanation was updated in a8f90e8e9fa0dd21b9b8bc6960df5742d4eb2114 to be correct.

**Comment by iliakan** [comment]
There are two exceptions from this rule:
1. Scripts with `async` attribute that we'll cover [a bit later](info:script-async-defer) don't block `DOMContentLoaded`.
2. Scripts that are generated dynamically with `document.createElement('script')` and then added to page also don't block this event.
