### ISSUE TITLE
Don't be exclusive and add section about Firefox in DevTools as you did for Chrome

### ISSUE THREAD

**Issue by dehghani-mehdi** [javascript-tutorial/en.javascript.info#1199]
Hi,

Don't be exclusive and add section about Firefox in [DevTools](https://javascript.info/devtools) _and other articles, I didn't check all articles_ [as you did for Chrome](https://javascript.info/devtools#google-chrome).

I don't think by having section about Chrome you mean Chrome is better than Firefox, but readers, specially new programmers may do. so ...

Thanks for the tutorials btw,

**Comment by iliakan** [comment]
Firefox are alike. Other browsers are alike. There's no reason to list all.

**Comment by iliakan** [comment]
I'm not assuming Chrome is better.

**Comment by dehghani-mehdi** [comment]
@iliakan still I think you should do same for Firefox and Chrome as they are 2 most used browsers and as resource for developers you have to do that, because people will decide based on your articles. no matter what you think, what you do is matter.

And Firefox is not just like other browsers, specially when it comes to developing, it has unique dev tools.
