### ISSUE TITLE
Question about one sentence on Closure chapter

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1203]
Hello, I'm translating this [article<Closure>](http://javascript.info/closure).

I couldn't fully understand this sentence, `Without use strict, an assignment to an undefined variable creates a new global variable, for backwards compatibility.`

Is it means that the new variable is created on the global Lexical Environment while the value of the variable is undefined?

**Comment by iliakan** [comment]
I updated the text a bit.

**Comment by Violet-Bora-Lee** [comment]
Thanks. I can understand the sentence now :)
