### ISSUE TITLE
Question about the term on Closure chapter

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1204]
Hello, I'm translating this [article](http://javascript.info/closure) regarding Closure.

I wonder the term `specification object` means.

Is it a special term to represent a special object in JavaScript?

I've tried to find the definition to understand the sentence fully but I only could find [this article](https://files.b-studios.de/bachelor_thesis.pdf) which mentions the "specification object". I couldn't find the definition of the term in this article as well.

Could you elaborate more about this?

**Comment by iliakan** [comment]
Is it clear now?

Please continue asking if anything isn't clear. As if it's not clear for you, it may also be a difficulty for other people.

**Comment by Violet-Bora-Lee** [comment]
I can fully understand now 💯
Thanks for your effort to update tutorial again! Your efforts enhance the quality of JS developers life 👍 🥇
