### ISSUE TITLE
Meaning of "on birth"

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1211]
Hello, I have a suggestion of the sentence in [Closure Chapter](http://javascript.info/closure), `All functions “on birth” receive a hidden property [[Environment]] with a reference to the Lexical Environment of their creation.`

Among the sentence, the phrase, `on birth`, could be vague. Some reader could interpret this phrase "when the function is defined" the others could interpret this into "when the function is called".

Could you elaborate the sentence more before we jump into the explanation about this?

**Comment by iliakan** [comment]
When created :)

**Comment by Violet-Bora-Lee** [comment]
Yes. When created(when the function is defined). Could you add few words on the sentence?

It's a suggestion btw. If you think it's enough not to add explanation on the sentence, you can close the issue.

Thanks in advance.

**Comment by Violet-Bora-Lee** [comment]
Ah... I read the article more times and now I can see the meaning of the "function creation". Thanks for your comment.

**Comment by Violet-Bora-Lee** [comment]
I have one question to verify my understanding.

So,  "when the function created" is equal "when the function is initialized" (and the function is initialized when a Lexical Environment created)?
