### ISSUE TITLE
Using a function name in a function expression

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1219]
In the section "JavaScript specials", which is a summary of the "JavaScript Fundamentals" tutorial, we find:

"Function expressions can have a name, like sum = function name(a, b), but that name is only visible inside that function."

However I do not think that feature was mentioned before. I could not find any mention of it in the "Function expressions and arrows" section, where I think it would have been if it were.

**Comment by iliakan** [comment]
Right, fixed that.
