### ISSUE TITLE
Method name of .toUpperCase

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1220]
In the Data Types chapter, in the first section "Methods of primitives", it is written:

"For instance, there exists a method str.toUpperCase() that returns a capitalized string."

I would think the method name should just be ".toUpperCase()" without "str" (or else "String.prototype.toUpperCase()"). Or there's something I don't understand.

**Comment by iliakan** [comment]
That's just to show that it's a string method.

**Comment by paroche** [comment]
I did infer that. And soon after that statement you refer to the method name as "toUpperCase" without the "str.". But I think it would be clearer, and more accurate, to use just the actual method name from the start. One of the things I have found exceptionally good about your tutorials -- and I have been very impressed with them -- has been just that kind of explicit accuracy (I've also been impressed with the level of completeness and explanations of the underlying logic presented simply, clearly, and concisely). It makes it much easier to put things clearly in my mind than if I have to infer what you really mean or figure it out from context. That's how it is for me, anyway. But I think it could be the same way for a significant number of other people, whether they notice it or not.

**Comment by iliakan** [comment]
Could you please create a PR of the suggested fixes? Thanks!

**Comment by iliakan** [comment]
People are often reading the tutorial not in the straight order, skipping parts. They may skip such a note if only given once.

We can add an explanation everywhere: what a `str` or `obj` or `num` is.

**Comment by paroche** [comment]
Cool. Though I think a first-time explanation would probably also still be good.


-----Original Message-----
