### ISSUE TITLE
what 'them' represent in the sentence, 'For now, we can already use them for one-line actions and callbacks.'

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1221]
Hello. I'm translating the article, http://javascript.info/function-expressions-arrows.

I wonder what `them` represents inside the sentence, 'For now, we can already use `them` for one-line actions and callbacks.'

features? arrow functions?

I think it's better to remove the sentence.

**Comment by iliakan** [comment]
arrow functions (will update)
