### ISSUE TITLE
I think 'negative' and 'positive' are switched in description of locale.Compare()

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1224]
In Data Types / Strings, it says:

"
The call str.localeCompare(str2) returns an integer indicating whether str comes before, after or is equivalent to str2 according to the language rules:

Returns a negative number if str is less than str2, i.e. str occurs before str2.
Returns a positive number if str is greater than str2, i.e. str occurs after str2.
Returns 0 if they are equivalent.
For instance:

 alert( 'Österreich'.localeCompare('Zealand') ); // -1
"
However, unless my brain is misfiring, I think it should say that it "Returns a POSITIVE number if str is less than str2" and "Returns a NEGATIVE number if str is greater than str2" (or "str" and "str2" should be switched). In the example, for instance, str ("Osterreich" w/ its umlaut), is greater than str2, "Zealand", and the result is negative.

Also, "Z".localeCompare("z") returns 1, and "Z"(str) < "z"(str2)

**Comment by iliakan** [comment]
Let's check:
- "a".localeCompare("b") - returns `-1` (negative number)

**Comment by paroche** [comment]
alert( 'Österreich'.localeCompare('Zealand') ); // -1
alert('Österreich' > 'Zealand'); // true
alert( 'Z'.localeCompare('z')); // 1
alert('Z' < 'z'); // true
alert( 'a'.localeCompare('b')); // -1
alert('a' < 'b'); // true

Ah, I think maybe I get it -- it's that "language rules" thing, not the Unicode values.
