### ISSUE TITLE
Error: Already exists an entry with slug:currying-partials

### ISSUE THREAD

**Issue by HachemiH** [javascript-tutorial/en.javascript.info#1227]
Hi,

since the last update, the server crashed because there is a duplicate slug.

I've tried to rename 03-currying-partials (in /1-js/99-js-misc) to 03-currying and it worked. 
So it's just a little name problem.

**Comment by iliakan** [comment]
That's because renamed aren't merged correctly. That article was moved. Please remove 03-currying-partrials from the previous place, let it be only in 99-js-misc.

**Comment by HachemiH** [comment]
Thank you, it's ok now
