### ISSUE TITLE
Datatypes/Arrays/toString section shows use of String() global, but not .toString method

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1228]
In the "toString" section of the Data Types / Arrays tutorial, it is written:

"
toString

Arrays have their own implementation of toString method that returns a comma-separated list of elements.

For instance:

 let arr = [1, 2, 3];

 alert( arr ); // 1,2,3
 alert( String(arr) === '1,2,3' ); // true
...
"

Nowhere in this section is the use of the toString method actually shown explicitly. As I understand it, the String() syntax gives the same results except for some edges, like String(null) returns null, while null.toString throws an error. 

And while it's true that, as per the MDN doc:

"JavaScript calls the toString method automatically when an array is to be represented as a text value or when an array is referred to in a string concatenation."

So that in the next part of this section of the tutorial:

"
   Also, let’s try this:

   alert( [] + 1 ); // "1"
   alert( [1] + 1 ); // "11"
   alert( [1,2] + 1 ); // "1,21"

   Arrays do not have Symbol.toPrimitive, neither a viable valueOf, they implement only toString 
   conversion, so here [] becomes an empty string, [1] becomes "1" and [1,2] becomes "1,2".
"
toString is called implicitly, and some explanation is given of that, I think the information could be presented more clearly.

**Comment by iliakan** [comment]
There's a previous chapter about that http://javascript.info/object-toprimitive.

Did you read it?
Should I add a reference to it?

**Comment by paroche** [comment]
Thanks. I did read it, but it was a little while ago -- the chapter on "Objects: the basics" was actually the first one I read on your site, and I found it very helpful, though apparently I didn't remember everything :-). In fact, it was reading it which led to me deciding to "relearn" JavaScript and start your tutorial from the beginning -- but I did skip re-reading it after the first three chapters (though I was planning on going over it again a bit later). So for most people I imagine that that chapter would be more recent and clearer in their minds. Still, I expect that a reference wouldn't hurt. I'll probably re-read at least the linked section tomorrow when I'm less tired and see how things look then. I only point out my perception of a lack of clarity because for the most part clarity is a real hallmark of your writing.

**Comment by iliakan** [comment]
Thank you!

Could you please suggest a PR with such reference? I'll gladly accept it.

**Comment by paroche** [comment]
>Could you please suggest a PR with such reference?
Do you mean like a promotional blurb for your tutorials mentioning clarity and the like (completeness, logic, reasonable attitude toward usage style considerations, etc.)? 
If so, I think I could come up with something.
Also, I thought I would mention that for the first several chapters I read, I thought you were a native English speaker; everything was perfect. Starting with the Data types section, I think, I started to notice a few little issues with article and preposition use and the like. Would you like me to point them out? I'd be happy to but I don't want to be annoying.

-----Original Message-----

**Comment by paroche** [comment]
I did reply directly to the email notification I received for the above, since it was from a Github "reply" (as opposed to "noreply") domain. Did you get it?

**Comment by iliakan** [comment]
I'm sorry, I'm not getting notifications, because there were too many of them, and I turned them off.

I'll look into it and maybe reenable or fine-tune to react faster.

Do you know how to make PRs (pull requests) using GitHub?

**Comment by iliakan** [comment]
P.S. By PR I mean "Pull Request".

**Comment by paroche** [comment]
I don't think I can do a PR for this in that I don't know exactly what you want to say. Starting in the lesson "Type Conversions" in the chapter "JavaScript Fundamentals" (or at least that's where I first became aware of it) you use the words "toString" (or "ToString" as a header), "toNumber", and "toBoolean", apparently to indicate some general process of converting a value to a string, a number, or a boolean. And perhaps those terms are used in JS circles as a kind of shorthand -- I don't know, though I haven't seen them. But in any case, to the first-time reader they create an ambiguity, in that they look like method or function names. And, in fact, there IS a number method ".toString", so that would contribute to the confusion. (Though I don't think there is a string (or other) method ".toNumber" or a method ".toBoolean"). So I would suggest either explaining your shorthand (if that's what it is, which is what I think) before using it, or else spell out "convert to string", "convert to number", etc. or something throughout the tutorial so there is little possibility of thinking that you are referring to an actual JS method or something.

**Comment by iliakan** [comment]
Hopefully, fixed? Not sure. There were changes there.

By the way, it would really help if you broke long texts into paragraphs. Much easier to understand 👍
