### ISSUE TITLE
"Objects" chapter references "Data types" chapter as if it had come before

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1234]
_The JavaScript language   Objects: the basics
30th July 2019
Objects
As we know from the chapter Data types, there are seven data types in JavaScript. Six of them are called “primitive”, because their values contain only a single thing (be it a string or a number or whatever)._

But we wouldn't generally have read the chapter Data types yet, since "Objects: the basics" (the chapter in which this page, "Objects" appears) is chapter 4 and "Data types" is chapter 5.

**Comment by iliakan** [comment]
Please follow that link. The referenced chapter is very early in the tutorial.

**Comment by paroche** [comment]
You are right, if I had clicked the link, and I should have, I would have seen that it referred to the earlier section 2.5 ("JavaScript fundamentals / Data structures"), But I had just been going through part (?) 5 of the tutorial, which is also called "Data structures" (5.1 - 5.12) and I was taking that to be what you meant by a "chapter". In my defense, in the sidebars such parts are referred to as "Sibling chapters", as shown below from the "JavaScript fundamentals" page:

Sibling chapters
An introduction
JavaScript Fundamentals
Code quality
Objects: the basics
Data types
Advanced working with functions
Object properties configuration
Prototypes, inheritance
Classes
Error handling
Promises, async/await
Generators, advanced iteration
Modules
Miscellaneous 
([https://javascript.info/first-steps](url))

So it was based on that that I assumed that phrase "the chapter Data types" referred to the "sibling chapter" "Data types" above and didn't click on the link.
