### ISSUE TITLE
Couldn't grasp this sentence regarding comment

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1235]
Hello. I'm translating the [article](http://javascript.info/comments) regarding comments.

In the summary section, there is a sentence `Put them only if it’s impossible to make the code so simple and self-descriptive that it doesn’t require those.`

I wonder what the last **that** and **it** represents in the sentence.

**Comment by iliakan** [comment]
that code doesn't require comments =)
