### ISSUE TITLE
Fisher-Yates shuffle example in Array Methods task uses Destructuring Assignment

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1239]
However, I don't think destructuring assignments had been covered yet at that point in the tutorial, so it makes it a little confusing. Did make me find out what it was, though.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

From the lesson task solution, where destructuring assignment is made on the line w/ "// swap elements":
https://javascript.info/array-methods#tasks

"There are other good ways to do the task. For instance, there’s a great algorithm called Fisher-Yates shuffle. The idea is to walk the array in the reverse order and swap each element with a random one before it:

function shuffle(array) {
  for (let i = array.length - 1; i > 0; i--) {
    let j = Math.floor(Math.random() * (i + 1)); // random index from 0 to i
    [array[i], array[j]] = [array[j], array[i]]; // swap elements
  }
}
"

**Comment by iliakan** [comment]
Fixed thanks!

**Comment by paroche** [comment]
Still looks the same to me. Is there a delay?
