### ISSUE TITLE
JS Fundamentals(Variables) Declaring versus defining 

### ISSUE THREAD

**Issue by oizabaiye** [javascript-tutorial/en.javascript.info#1244]
The following sentence implies that declaring a variable is the same thing as defining a variable. I am thinking the text should say "The statement below declares a variable with the name 'message'...". I'd recommend a short sentence explaining that a variable definition is when you assign a value (hence why 'undefined' denotes the absence of a value). Happy to do a pull request.

https://javascript.info/variables#a-variable

>The statement below creates (in other words: declares or defines) a variable with the name “message”:
`let message;`

**Comment by iliakan** [comment]
Could you please send a pull request?

**Comment by oizabaiye** [comment]
Hi, I think there may have been a misunderstanding. The thumbs up meant I'm working on it. With apologies, did I miss a deadline?

**Comment by iliakan** [comment]
Oh I just closed it, because this isn't actual any more: you'll be making a PR that obsoletes the issue.

**Comment by oizabaiye** [comment]
Oh my bad! I didn't understand. Feel free to close again.
