### ISSUE TITLE
Using "occasional" to mean "accidental"?

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1246]
Several times (5, I think) in the lesson "Symbol type" w/in the chapter "Objects: the basics", and a few times in some other lessons (though I don't recall which), the words "occasionally" or "occasional" are used in a way that doesn't make much sense in English. What I think may have happened is that the author may also speak French, where "occasionnel" does have the sense of "accidental" or "by chance", which, however, "occasional" does not in English:
https://www.dictionary.com/browse/occasional

(as a side note, I think we got the word "occasion" from the French (Norman conquest and all that), but added the Latin suffix "-al" on our own centuries later).

So I think what should probably happen is that the words "occasional" and "occasionally" should be replaced by "accidental" and "accidentally", in this lesson and elsewhere in the tutorial.

**Comment by iliakan** [comment]
Thank you very much, would you be so kind to make a PR?

I already asked you previously, in other issues. That's not because I'm lazy, but to ensure that the corrected variant is of a high quality, and that it's what you really mean.

**Comment by iliakan** [comment]
Making a PR is very easy takes about the same time as writing the issue.

**Comment by iliakan** [comment]
Let me know if you need help with that.

**Comment by paroche** [comment]
I'm sure I can do a PR for the article(lesson) I referenced ("Symbol type") (I'll have to read the GitHub doc on it, but it would be a good thing to know how to do). However, I did also notice that word usage on other lessons. Doing a Google search on your domain I get likely hits from the lessons:
Status            SubHeader  (Lesson) or Lesson (Chapter) or something (something above it)
**change**    "Symbol type" ("Objects: the basics") ( "occasionally" -> "accidentally") (are 4 cases of "occasionally" and 1 of "occasion" that should be changed. Maybe that will be my first PR).
*OK*             (in "Comparisons" ("JavaScript fundamentals") "occasionally" seems to be being used in the sense of "on occasion" so is OK)
**change**   "Mixins" ("Classes") ("occasionally"  -> "accidentally")
*???*           "Styles and classes" ("Browser: Documents, Events, Interfaces") (could maybe be changed to "accidentally" but also could be what you want to say the way it is)
*change?*  "LocalStorage, session storage" ("Storing data in the browser") (I think probably "occasionally" -> "accidentally")
**change**   "Cookies, document.cookie" ("Storing data in the browser") ( "occasionally -> "accidentally")
"OK?*        (in "TextDecoder and TextEncoder" (under "Binary data, files") "occasionally" may be the word you want, but you should maybe look at it)
*OK?*       (in "Infinite backtracking problem" (under "Regular expressions") "occasionally" is probably still the word you want).
*OK?*       (in "Unicode: flag 'u'" under ("Regular expressions"), also "occasionally" is probably still the word you want)

So there are at least 3 other articles (lessons) that I'm pretty sure need changing, and some others you may want to look at and decide for yourself. Also, I haven't gotten to most of those sections yet and may not as well be able to understand the context of what is being said.
Also, the Google search only showed the 1st instance of the use of the word -- there may be other cases that didn't show.

-----Original Message-----

**Comment by paroche** [comment]
I think I've done it for the "Symbol type" page. Let me know if it all worked right.


-----Original Message-----

**Comment by iliakan** [comment]
Yes, that's right.

I carefully review all changes, to make sure your understanding is correct.

**Comment by iliakan** [comment]
Please close this issue if you feel occational -> accidental is fully replaced where needed =)

**Comment by paroche** [comment]
Wanted to make sure I did it right and it was approved, then, as I wrote yesterday,  there are several other articles where the same changes should, or perhaps should, be made.

Sent from AOL Mobile Mail
On Tuesday, August 20, 2019 Ilya Kantor <reply@reply.github.com> wrote:

Please close this issue if you feel occational -> accidental is fully replaced where needed =)
