### ISSUE TITLE
Terminology inconsistent -- "Chapter" and "Lesson"

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1247]
The word "Chapter" seems to be used for 3 different levels in the tutorial. On the sidebar for "The Javascript Language" section:
https://javascript.info/js

other such high-level sections, such as:
Browser: Document, Events, Interfaces
Frames and windows
Binary data, files
Network requests
Storing data in the browser
Animation
Web components
Regular expressions

are referred to as "Sibling Chapters". However, if you go deeper into the "JavaScript Language" "chapter", you will then find lower-level divisions also referred to as "chapters":
Sibling chapters
An introduction
JavaScript Fundamentals
Code quality
Objects: the basics
Data types
Advanced working with functions
Object properties configuration
Prototypes, inheritance
Classes
Error handling
Promises, async/await
Generators, advanced iteration
Modules
Miscellaneous

Then, in one of those sections if you go to one of the options, like "Hello, World!" under JavaScript Fundamentals", you find that sections like "Hello, World!" and the like are referred to in the sidebar as "lessons" (which I think is totally appropriate). However, within the lessons, when prior lessons are referred to, they are generally called "chapters". E.g. in the lesson "Object to primitive conversion", we find:

"In the chapter Type Conversions we’ve seen the rules for numeric, string and boolean conversions of primitives. But we left a gap for objects. Now, as we know about methods and symbols it becomes possible to fill it."

But, using the terminology from the sidebar, "Type Conversions" is a "lesson", not a "chapter". In another lesson (sorry, don't recall which one right now) where an earlier lesson (lesson "Data types" within the chapter "JavaScript fundamentals" https://javascript.info/types) was called a "chapter" it was especially ambiguous because there actually was a chapter ("Data types" https://javascript.info/data-types) with the same name.

**Comment by iliakan** [comment]
Here's the structure:
1) Folders (contain other folders or articles).
2) Articles
3) In an article, there are subheaders.

How to name those?

**Comment by paroche** [comment]
Sorry, I'm not quite sure what you're asking. I think the way you have it in the mid and low level side bars is good -- sections like "Objects: the basics" should be called "chapters", and the individual pages like "Objects" or "Garbage collection" should be called "lessons (is this what you are also referring to in this email as "articles"?). And within lessons, to refer to the other linked headers as "subheaders" is OK. The only thing I would change there is in the text of the articles (lessons), when referring to other articles (lessons) that they are indeed called "lessons" and not "chapters".
With respect to the higher level divisions, like "The JavaScript language", "Browser: Document, Events, Interfaces", "Frames and Windows", etc. perhaps you call them "sections" rather than also referring to them as "chapters" as they are below:
Sibling chapters
   
   - The JavaScript language
   - Browser: Document, Events, Interfaces
   - Frames and windows
   - Binary data, files
   - Network requests
   - Storing data in the browser
   - Animation
   - Web components
   - Regular expressions

There is probably some Chicago Manual of Style approved format for this, but I don't know. Though I did just check with my ex-girlfriend who's been a technical copy editor forever and I think she said (connection was garbled and she was in a hurry) that using "sections" as the level above "chapters" would be good. 

Does that answer your question?

-----Original Message-----

**Comment by paroche** [comment]
("Same as before but I realized I was using the word "sections" in two ways and wanted to remove any ambiguity)
Sorry, I'm not quite sure what you're asking. I think the way you have it in the mid and low level side bars is good -- divisions like "Objects: the basics" should be called "chapters", and the individual pages like "Objects" or "Garbage collection" should be called "lessons (is this what you are also referring to in this email as "articles"?). And within lessons, to refer to the other linked headers as "subheaders" is OK. The only thing I would change there is in the text of the articles (lessons), when referring to other articles (lessons) that they are indeed called "lessons" and not "chapters".
With respect to the higher level divisions, like "The JavaScript language", "Browser: Document, Events, Interfaces", "Frames and Windows", etc. perhaps you call them "sections" rather than also referring to them as "chapters" as they are below:
Sibling chapters
   
   - The JavaScript language
   - Browser: Document, Events, Interfaces
   - Frames and windows
   - Binary data, files
   - Network requests
   - Storing data in the browser
   - Animation
   - Web components
   - Regular expressions

There is probably some Chicago Manual of Style approved format for this, but I don't know and didn't find anything helpful with a quick search. Though I did just check with my ex-girlfriend who's been a technical copy editor forever and I think she said (connection was garbled and she was in a hurry) that using "sections" as the level above "chapters" would be good. 

Does that answer your question?


-----Original Message-----

**Comment by iliakan** [comment]
Is that correct?
![image](https://user-images.githubusercontent.com/349336/63297119-54ecaf00-c2d9-11e9-966d-37cc9260c83e.png)

Folders = sections, and individual articles are chapters?

And if we're talking about subheaders in an article?

**Comment by iliakan** [comment]
P.S. I don't like the word "lesson", as the tutorial is more like a book actually. Chapters/articles are closer.

**Comment by paroche** [comment]
That's fine, I was mostly using your terminology from the sidebar. Though I actually do like the term "lesson", because you have the "Tasks". But I wouldn't complain about "Section / Chapter / Article" :-).


-----Original Message-----

**Comment by paroche** [comment]
Well, in that case (what you have below) "articles" (aka "lessons") would be "chapters", I think. The way you have it in your table of contents is good (I don't think I'd looked at the table of contents before -- was using the chapter sidebars for context). 
But I did notice that the Table of Contents:
* Says in the header it contains 2 parts, but currently has a Part 3.* Is somewhat inconsistent with this page: https://javascript.info/js, which it does not reference directly but which can be accessed by clicking on the context link ("The JavaScript Language") at the top of any(?) of the Chapter pages. On that page, Part 2 and the various components of Part 3 are all referred to as being at the same level and are called "Chapters".
But for Part 1, at least, I do think this works:
Part 1: The JavaScript Language(Part 1) Chapter 1: An Introduction(Part 1, Chapter 1) Lesson 1 (or Article 1): An Introduction to JavaScript
Guess one doesn't need the term "section" above "chapter" after all. I think that is covered by "Part". Seems like everything under a "Part" is a "Chapter" that contains "Lessons" (or "Articles), so that's cool.

For the most part that is what you have in your side bars, except on the https://javascript.info/js page, where Part 2 "Browser: Document, Events, Interfaces", which has it's own Chapters with Lessons below them, and Chapters like "Frames and Windows", that only have Lessons under them, are listed as if they were on the same level. Not a big deal, but a bit inconsistent.


-----Original Message-----

**Comment by iliakan** [comment]
And what if we're talking about a part of an article?

E.g. what's this? https://javascript.info/intro#what-can-in-browser-javascript-do (a section in the article).

**Comment by paroche** [comment]
I think if you need to refer to them those linkable parts could be called "sections". 
I do still favor calling the individual pages with the explanations and the tasks and comments "Lessons", though. Even if you are thinking of the site as a book, books don't typically contain "articles", but could consist of chapters and lessons (magazines and newspapers typically contain articles).
So FWIW, what I think would be pretty good is:
Part 1  "The JavaScript Language"  Chapter 1.1  "An Introduction"     Lesson 1.1.1  "An Introduction to JavaScript"        Section 1.1.1.a  "What is JavaScript?"
But I think the most important thing, whatever the terminology, is that it's used consistently. 



-----Original Message-----

**Comment by iliakan** [comment]
Is this fine (Lesson -> Article) ?
- Part 1  "The JavaScript Language"  
- Chapter 1.1  "An Introduction"     
- Article 1.1.1  "An Introduction to JavaScript"        
- Section 1.1.1.a  "What is JavaScript?"

**Comment by iliakan** [comment]
An alternative (no article/lesson):

- Part 1  "The JavaScript Language"  
- Chapter 1.1  "An Introduction"     
- Chapter 1.1.1  "An Introduction to JavaScript"        
- Section 1.1.1.a  "What is JavaScript?"

**Comment by paroche** [comment]
Well, yes, it's fine, though as I wrote before I do prefer "lesson" (which is what you currently have in the navigation side bars) over "article", for the reasons I gave and, more generally, that they really just overall strike me as being lessons (didactic instruction for people learning a topic) rather than as articles. There are, of course, articles on JavaScript (and everything else) technical issues out there far and wide. For instance this post on Medium:
https://medium.com/poka-techblog/simplify-your-javascript-use-map-reduce-and-filter-bd02c593cc2d
which even refers to itself as an "article". It does tell you how to use certain JS features, but isn't presented in a "now for our next lesson..." kind of way, but rather as kind of an ad hoc presentation of a topic of interest. I mean, it certainly has a lot in common with a lesson in a tutorial, and could be converted to one without much trouble, but the attitude and the context are different. 

I spoke w/ my ex yesterday, and she has been a copy editor for technical writing for a very long time, and after I explained the situation, she felt even more strongly about the suitability of "lesson" over "article" than I did. 
So, that's how it looks to me. But if you still prefer "article" for your pages, than I don't think it will do any harm, as long as the terminology is consistent.
I know you posted later on another possibility for this, and I'll respond to that separately. 


-----Original Message-----

**Comment by paroche** [comment]
The problem I see with this is when you want to refer to a particular lesson from another lesson, what do you call it? Currently you have the word "chapter", which is kind of what got me started on this thread. 
Also, I don't think calling Chapter 1 of Part 1 "Chapter 1.1" is good. I think it's either "Part 1.1" (not recommended) or "Part 1, Chapter 1". "Chapter 1.1" suggests a sub section of Chapter 1. I don't think the names can be treated as independent of the numbers, at least not when they are being combined.


-----Original Message-----

**Comment by iliakan** [comment]
I've read many tutorials, I just don't remember them self-referencing with "lessons".

But my experience with English tutorials is limited, maybe you know better =)

**Comment by paroche** [comment]
Hmmm. Don't recall, so I have to check (part of this is from stuff I was familiar with, part from doing searches on "javascript tutorials" and "learn javascript"):
This DigitalOcean "tutorial series", it calls itself, on JS & the DOM, refers to it's individual lessons as "tutorials". That would work, except that I think currently you are referring to your whole learn JS project as a "tutorial", but, if so, that could be changed, if needed.https://www.digitalocean.com/community/tutorials/how-to-use-object-methods-in-javascript(I think this is a very good series, BTW, though I haven't gone through your stuff on the topic yet).
FreeCodeCamp refers to their individual pages "lessons" (below, in the first sentence, "We have thousands of coding lessons...",)https://learn.freecodecamp.org/
But elsewhere they refer to them as "Coding challenges", since each one consists of some explanation followed by a coding challenge that has to be passed to move on. But many of these are quite small -- much smaller than most of your lessons.
At the much-reviled W3Schools they call their whole section dedicated to learning JS a "tutorial", and the individual pages "chapters".  At least, they do here:https://www.w3schools.com/js/
They don't have the same type of organizational hierarchy as you do, so the term "chapters" was still available.

At CodeCademy, they do seem to call the individual pages "lessons", or, more precisely, "interactive lessons" (and the overall collection a "course"):https://www.codecademy.com/learn/introduction-to-javascript
Learn-JS calls the individual pages "chapters":https://www.learn-js.org/
GeeksForGeeks does call them "articles", so there is precedent there:https://www.geeksforgeeks.org/switch-case-javascript/
A site called "java T point" seems to call each of their pages a "topic":https://www.javatpoint.com/javascript-string
(see bottom, where it says "Next topic")
"Learn JavaScript" calls them lessons:https://learnjavascript.online/

The mighty MDN has "Modules", like "Introducing JavaScript objects", then within them "Guides", like "Object basics", which are single pages.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics

So that's a sampling, anyway. Actually, it's most of what I could find that wasn't kind of haphazard. Looks like "lesson" isn't unheard of as a name for an instruction page. Found two or three that do it at least partly. From the above (and maybe one should include more examples) it looks like "lessons" is the most common (say 2 1/2 examples), followed by "chapters" (2). Then 1 each for "tutorial" (for a single page), "article", "topic", and "guide".


-----Original Message-----

**Comment by iliakan** [comment]
What a great in-depth research you have made! 

I'm hesitating to call them lessons, because some materials are not exactly lessons.

For example, http://javascript.info/webcomponents-intro - an introduction into web components.

Or http://javascript.info/indexeddb - is an article, that's not a lesson.

**Comment by iliakan** [comment]
Imho, a lesson must include tasks, but many articles do not (yet)

**Comment by iliakan** [comment]
they are not "lessonish" enough

**Comment by paroche** [comment]
For my part, and IMAO, I would be comfortable w/ both of the below being referred to as "lessons". I think they still fit the definition:
"a section into which a course of study is divided, especially a single, continuous session of formal instruction in a subject:The manual was broken down into 50 lessons."https://www.dictionary.com/browse/lesson?s=t

Even without tasks or exercises is still a lesson. They're sections of a course of study, for sure.


-----Original Message-----

**Comment by paroche** [comment]
i think they are. I mean, it's semantics, and we may have different understandings and associations about what the word means, but it seems like OK usage to me.


-----Original Message-----

**Comment by iliakan** [comment]
I discussed it with my colleagues, who translate and review PRs to the Russian version of the tutorial. 

Their consensus is that an "article" should remain an "article",  because the whole tutorial has more a "book" feeling. Not a "course with lessons", but rather a "book with chapters, articles".

Also, my personal feeling is that a "lesson" is a more strict term. It implies tuition, tasks. "Article" gives us more freedom on what to write and how to write it.

So, "article" looks like a more safe choice.

- Part 1 "The JavaScript Language"
- Chapter 1.1 "An Introduction"
- Article 1.1.1 "An Introduction to JavaScript"
- Section 1.1.1.a "What is JavaScript?"

**Comment by paroche** [comment]
I don't agree with that description of what "lesson" means or implies. Again, from the dictionary (or a dictionary):
(Def 1) "a section into which a course of study is divided, especially a single, continuous session of formal instruction in a subject:The manual was broken down into 50 lessons."https://www.dictionary.com/browse/lesson?s=t

Which is also compatible with my personal understanding of the word, and seems to fit quite closely what I've read so far.
But if you would still find it constrictive to call them lessons, and would be more comfortable calling them "articles", I don't really think it will matter all that much to the readers, as long as the usage is consistent. 

-----Original Message-----

**Comment by iliakan** [comment]
Ok, so we stop at the latest variant. Thank you a lot for having this settled! I myself felt confused about the good way to name parts.

- Part 1 "The JavaScript Language"
- Chapter 1.1 "An Introduction"
- Article 1.1.1 "An Introduction to JavaScript"
- Section 1.1.1.a "What is JavaScript?"
