### ISSUE TITLE
Traditional Chinese translation (zh-Hant)

### ISSUE THREAD

**Issue by lenchen1112** [javascript-tutorial/en.javascript.info#1251]
Due to some terminologies that are used differently between Simplified and Traditional Chinese, we'd like to fork a Traditional Chinese version of this repo.

- language code: `zh-Hant`, refer to [W3C](https://www.w3schools.com/tags/ref_language_codes.asp)
- maintainers:
`lenchen1112` lenchen.ckl@gmail.com
`kaddopur` chaoju.huang@gmail.com
`tom76kimo` tom76kimo@gmail.com

Thanks a lots!

**Comment by iliakan** [comment]
You're going to for from en version or from zh version?

**Comment by lenchen1112** [comment]
From en version might be better. I guess there is an issue for tracking progress in it only from en right?

**Comment by iliakan** [comment]
Right, from en is better.

Are you sure you'd like to make a separate zh-hant version, given that zh version is mostly translated already?

**Comment by lenchen1112** [comment]
Yes. Because sentence structures and terminologies are different between these two forks of Chinese. We will need to modify sentence by sentence to make it more fluent.

**Comment by iliakan** [comment]
Right now there's https://zh.javascript.info

The zh-hant vesion will at https://zh-hant.javascript.info?

**Comment by lenchen1112** [comment]
Sure, no problem. Many thanks.

**Comment by iliakan** [comment]
Created 🎉 
Got the invitations?

**Comment by lenchen1112** [comment]
Yes, have already joined the team. Many thanks!

**Comment by lenchen1112** [comment]
@iliakan 
Sorry that I accidentally set team `translate-zh-hant` to only has permission of write so I can't modify configuration of repository...
Could you please help to set permission of team `translate-zh-hant` back to `admin` of `zh-hant.javascript.info`?
Thanks a lot.
