### ISSUE TITLE
please change this if you think 

### ISSUE THREAD

**Issue by shahid192** [javascript-tutorial/en.javascript.info#1257]
page url: http://javascript.info/regexp-character-classes
section: Word boundary: \b
please change this
< When the pattern contains \b, it tests that the position in string is a word boundary, that is one of three variants:
Immediately before is \w, and immediately after – not \w, or vise versa.
At string start, and the first string character is \w.
At string end, and the last string character is \w.
> 
with 
<There are three different positions that qualify as word boundaries:
Before the first character in the string, if the first character is a word character.
After the last character in the string, if the last character is a word character.
Between two characters in the string, where one is a word character and the other is not a word character. >

![change this pleasae if you think so](https://user-images.githubusercontent.com/48304669/63409454-1113ab80-c3a6-11e9-81d1-00fe6cb8f985.png)

**Comment by iliakan** [comment]
Kind of did it =) Thanks

**Comment by shahid192** [comment]
thanks for this great effort to provide anyone great material about javascript
