### ISSUE TITLE
 "Symbol" subject has disappeared

### ISSUE THREAD

**Issue by lumosmind** [javascript-tutorial/en.javascript.info#1265]
in "**Objects: the basics**" section, "**Symbol**" subject has disappeared
It is still alive in github repo but it is removed from [https://javascript.info/](url)

**Comment by iliakan** [comment]
Sorry, I don't understand?

**Comment by iliakan** [comment]
What is wrong, elaborate?

**Comment by iliakan** [comment]
Sorry, look like @paroche accidentally renamed the file. 

Returned it back.

**Comment by paroche** [comment]
Sorry! How did I do that?

**Comment by iliakan** [comment]
Fixed

**Comment by iliakan** [comment]
You renamed `article.md` =)

**Comment by paroche** [comment]
Huh. Didn't realize. I'll try to be mindful of the possibility in the future.

I've kind of been feeling my way through the PR process -- seems that I can't fork directly off the article (doesn't give me the option, though the GitHub tutorial seemed to be saying it would), but seem to have to edit the last update to the article (look, I'm calling it an article -- in this more abstract context it seems to make more sense). Doesn't seem perfect, but it seemed to be working, and I figured it was only a request so couldn't do much harm by itself anyway.

-----Original Message-----

**Comment by iliakan** [comment]
Git allows to fork off a "branch" (a state of the whole project), not off an individual article.

**Comment by iliakan** [comment]
I review all pull requests, somehow managed to miss that 🤷‍♂

**Comment by paroche** [comment]
Did seem to be something like that. Thanks.


-----Original Message-----

**Comment by paroche** [comment]
There's always enough, um, responsibility, to go around.


-----Original Message-----
