### ISSUE TITLE
Sinhala Translations

### ISSUE THREAD

**Issue by vishwaefor** [javascript-tutorial/en.javascript.info#1270]
Hi

I have translated an article and put a pull request. But it is not merged yet. Please have a look. I would be happy to be a maintainer as well.

Thank you

**Comment by iliakan** [comment]
The maintainer doesn't respond?

**Comment by vishwaefor** [comment]
Nope. https://github.com/javascript-tutorial/si.javascript.info/pull/2

**Comment by iliakan** [comment]
Ok. You're a maintainer now =)

**Comment by iliakan** [comment]
Hopefully, this one is closed.
