### ISSUE TITLE
"Array methods" task "Create an extendable calculator" solution uses closure 

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1271]
In 5.5, "Array methods", the solution for the task "Create an extendable calculator" seems to assume some understanding of closure and the lexical environment of JS functions. This is mentioned in a way at the beginning: "Please note how methods are stored. They are simply added to the internal object.", but I don't think at this point in the tutorial the readers have been exposed to the knowledge of why that would work. If they have, I missed it. I think that a solution should be shown that does not require any knowledge that hasn't been covered yet, and, if the current solution is also kept, have some note about how this uses a feature that will be covered in a future lesson (i.e. 6.3, "Closure").

**Comment by iliakan** [comment]
There'a commit reference in "closed...".

I changed it to `this.methods`, that doesn't imply any "closures" understanding.
