### ISSUE TITLE
Question：The spread operator operates only on iterables.

### ISSUE THREAD

**Issue by Flcwl** [javascript-tutorial/en.javascript.info#1274]
In the article [02-rest-parameters-spread-operator](https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/06-advanced-functions/02-rest-parameters-spread-operator/article.md), I see the difference between Array.from(obj) and [...obj]:

> - `Array.from` operates on both array-likes and iterables.
> - The spread operator operates only on iterables.

I have a test as follow, Can explain that the `spread operator` also supports the `array-likes`?
```
function fun() {
  const args = [...arguments]
  console.log(args)
}
fun(1, 2, 3) // [1, 2, 3]
```

**Comment by iliakan** [comment]
`arguments` is iterable. 
Why did you suppose it isn't? Anything unclear in the tutorial?

**Comment by Flcwl** [comment]
`arguments` is also an `Array-like` object, So I think the `spread operator operates` also supports the `array-likes` /h.
I want to know that why the `spread operator` operates only on `iterables`?  Can u give an example of why The spread operator does not support `array-likes`? thx~

**Comment by iliakan** [comment]
there's such example in the tutorial.

**Comment by iliakan** [comment]
`let obj = { 0: 'a', length: 1}`

**Comment by Flcwl** [comment]
thx very much.
