### ISSUE TITLE
A mistake with "shallow" copy.

### ISSUE THREAD

**Issue by MeTheCoder4** [javascript-tutorial/en.javascript.info#1278]
I think there is a mistake in a section "Prototype methods, objects without __proto__" in chapter "Prototypes, Inheritance", the last code example. A comment there states, that a **shallow** copy is being created by a call to method Object.create(...), while that method, as stated in the specification, creates a new object, allocating new memory and resulting, in this case, in a **deep** copy of an object. A call to alert(clone === obj) outputs false.

**Comment by iliakan** [comment]
Nested objects are not copied. That’s shallow.
