### ISSUE TITLE
Missing clarity over a shorthand

### ISSUE THREAD

**Issue by LLMpeeters** [javascript-tutorial/en.javascript.info#1290]
In the tutorial's part about objects, it talks about property value shorthand.
http://javascript.info/object#property-value-shorthand
At one point it shows a snippet of code:
let user = {
  name,  // same as name:name
  age: 30
};
To me this implies I don't have to declare name as a variable before doing this. When I try this in the console in chrome or firefox (I change 'name'  to something unused, as 'name' is already used') I simply get an error.
![Chrome error](https://user-images.githubusercontent.com/49389488/63945497-b2b88e00-ca73-11e9-9999-51c95697d1ad.png)

I know that you could do it this way:
![chrome fix](https://user-images.githubusercontent.com/49389488/63945628-f14e4880-ca73-11e9-9dee-836cd2a3805c.PNG)

But when I google this issue I get a lot of other examples that similarly imply you don't have to declare anything beforehand. 
I just wanna find out the truth!

**Comment by iliakan** [comment]
As said, writing `name` is the same as writing `name: name`.

The latter assumes you have a variable `name` already =)
