### ISSUE TITLE
Type Conversions: Elaborate or simplify the solution for point no.7

### ISSUE THREAD

**Issue by anonymouscoderx** [javascript-tutorial/en.javascript.info#1291]
![Solution point 7](https://user-images.githubusercontent.com/42294693/63971647-a4df2900-cac4-11e9-9677-7e90acd9fe08.png)

" \t \n" - 2 = -2
The explanation doesn't seem to be satisfying. If the space characters on the start and '\t \n' gets trimmed, it still has a space in-between them. Can you please be more elaborate on the solution?

**Comment by iliakan** [comment]
Space in-between them is a space character too. So obvious. What can I add to make this clear?

**Comment by anonymouscoderx** [comment]
Cool! So all the space characters get trimmed? 

Why don't you split the sentence into two short sentences? One explaining about the trimming of the \t \n and another one detailing about the space present. It's just a suggestion.
