### ISSUE TITLE
Fate of original function properties when function is wrapped

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1308]
In the Summary, you  have:

"It is generally safe to replace a function or a method with a decorated one, except for one little thing. If the original function had properties on it, like func.calledCount or whatever, then the decorated one will not provide them. Because that is a wrapper. So one needs to be careful if one uses them. Some decorators provide their own properties."

I don't think this is covered in the body of the article (I could be wrong, but I've read it a few times), and I think it would be useful if it were.

**Comment by iliakan** [comment]
Is it acceptable now?
