### ISSUE TITLE
Fix the statement "A non-configurable property can not be deleted or altered with defineProperty""

### ISSUE THREAD

**Issue by dfedynich** [javascript-tutorial/en.javascript.info#1309]
There is the next statement in the chapter "Property flags and descriptors"
> A non-configurable property can not be deleted or altered with defineProperty.

The statement above is almost true. According to this [reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Modifying_a_property) for non-configurable data properties it is still possible to **change writable** attribute from `true` to `false`.

Here is the source code example to check.

```javascript
let user = { };

Object.defineProperty(user, "name", {
  value: "John",
  writable: true,
  enumerable: true,
  configurable: false
});
```
Then we can change _writable_ attribute from `true` to `false`.
```javascript
'use strict'

Object.defineProperty(user, "name", {
  value: "Steve",
  writable: false
});
```

I think, it would be great to complete the whole picture and fix the statement above by adding  the appropriate note.

**Comment by iliakan** [comment]
Good point! Please check the updated description.
