### ISSUE TITLE
Fix the statement "An attempt to delete on accessor property causes an error"

### ISSUE THREAD

**Issue by dfedynich** [javascript-tutorial/en.javascript.info#1310]
There is the statement in chapter "Property getters and setters"

> An attempt to delete on accessor property causes an error

It seems, that it's not true anymore. I managed to create an accessor property and delete it afterwards successfully.

Here is the source code to check

```javascript
let user = {
  name: "John",
  surname: "Smith",

  get fullName() {
    return `${this.name} ${this.surname}`;
  }
};

user.fullName; // output: John Smith
```

Then the accessor property is deleted

```javascript
'use strict'
delete user.fullName; // output: true
user.fullName; // output: undefined
```

**Comment by iliakan** [comment]
Thank you for the correction.
