### ISSUE TITLE
no responses on the text area(mouse event)

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1316]
Hi, I'm reading the [article](http://javascript.info/mousemove-mouseover-mouseout-mouseenter-mouseleave).

![image](https://user-images.githubusercontent.com/6451384/64240702-548d1e80-cf3d-11e9-9084-f1918965949f.png)
(the first one!)

When I move the mouse inside div, the text area isn't updated.

I'm using Windows 10, Chrome.

**Comment by iliakan** [comment]
Is everything ok now?

**Comment by Violet-Bora-Lee** [comment]
YES 👍
