### ISSUE TITLE
question about mouseover event

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1318]
Hi, I'm reading the [article](http://javascript.info/mousemove-mouseover-mouseout-mouseenter-mouseleave) regarding mouser event.

---
![image](https://user-images.githubusercontent.com/6451384/64241812-61ab0d00-cf3f-11e9-93f1-250ca9f6fb00.png)

**Q1.** I couldn't fully understand this part of the sentence `elements can be only skipped as a whole.`.
Could you elaborate more?

---

![image](https://user-images.githubusercontent.com/6451384/64250208-7e9c0c00-cf50-11e9-8ad3-1cd4ae151abf.png)

**Q2.** I also couldn't understand this part of the sentence `If the code inside the handlers doesn't look at `target`,`. I'm confusing the meaning of the `look at` in this phrase.

**Comment by iliakan** [comment]
Better now?

**Comment by Violet-Bora-Lee** [comment]
Yeah, absolutely! 👍
