### ISSUE TITLE
Prototypal Inheritance: "The value of this" part confusing

### ISSUE THREAD

**Issue by muradsofiyev** [javascript-tutorial/en.javascript.info#1323]
https://javascript.info/prototype-inheritance#the-value-of-this
In this part you talk about how this work and in there you say "**That is actually a super-important thing, because we may have a big object with many methods and inherit from it. Then inherited objects can run its methods, and they will modify the state of these objects, not the big one**."
I think this is not good explanation. Your sentence like you say "this value give to us performance optimisation" but this is does not make sense.
In my opinion this sentence must be change or update new one because this sentence can be make confusing.

**Comment by muradsofiyev** [comment]
And before close this issue please discuss about this sentence.

**Comment by iliakan** [comment]
Discussed =)
