### ISSUE TITLE
question about `this`, inside replacer function

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1338]
Hi, I'm translating this article.
http://javascript.info/json

I have a question about below sentence.
 - The value of `this` inside `replacer` is the object that contains the current property.

I know that what `this` means in the context of Object but I want to make sure that `this` is the `this` referencing Object.

There is no `this` inside replacer function literally.

**Comment by iliakan** [comment]
What you mean "there's no `this` inside replacer"? That there's no `this` in examples?

**Comment by Violet-Bora-Lee** [comment]
Yes, your guess is right.

**Comment by iliakan** [comment]
In practice, I never saw `this` used in `replacer`, that's why.

**Comment by Violet-Bora-Lee** [comment]
Yes, I also haven't seen `this` inside the `replacer` function.
I'll close the issue because `this` references the Object like usual.
I just wanted to make sure that what I was thinking is right.
