### ISSUE TITLE
Question on decorating defer task solution in Native prototypes lesson 

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1357]
When I modify the test code for the solution to include a "this" in the function, it no longer works:
<pre>
Function.prototype.defer = function(ms) {
  let f = this;
  return function(...args) {
    setTimeout(() => f.apply(this, args), ms);
  }
};

// check it
function f(a, b) {
  this.c = 5;
  alert( a + b + this.c );
}

f.defer(1000)(1, 2); // does not execute
</pre>
However, if I replace the arrow function with a regular function expression:
 <code> setTimeout(function() {f.apply(this, args)}, ms)</code>
it works fine. After a second it alerts "8".

**Comment by iliakan** [comment]
It's not an object method, why is it supposed to work?

**Comment by paroche** [comment]
The directions were "Add to the prototype of all functions the method defer(ms), that returns a wrapper, delaying the call by ms milliseconds." Maybe I'm misunderstanding, but I would think that a wrapper added to the prototype of all functions would be better if it preserved the "this" of the functions than if it didn't, especially if the code is just as simple.

**Comment by iliakan** [comment]
Maybe I'm missing something about your code, but it seems you're calling a function without an object. So `this=undefined`.

If it's not so, please give me a link to a sandbox, so I can see the full example.

**Comment by paroche** [comment]
No, you're totally right. I was operating on an unquestioned, unnoticed, assumption. I've just realized that even though I have read and understood much of what's written here and elsewhere about 'this', there has also been an unconscious pull, if you will, toward the plain-English meaning of "this" as "the current thing", rather than as "the current thing's dynamic context". This little adventure, by bringing it to light, may have helped to untangle that some.

But still, I was totally right when I said I "maybe I'm misunderstanding."

**Comment by iliakan** [comment]
If you have a misunderstanding, then someone else may have it as well.

If you think we should add a few words here or there to prevent it, please suggest a PR =)

**Comment by paroche** [comment]
Usually that's what I think too, and a few words here and there can be very helpful to clarify and reinforce ideas. But in this case it looks like it was my own idiosyncratic error. Still, if in the course of my continuing studies and research any brilliant suggestions come to mind, I'll chime in.
