### ISSUE TITLE
question about eval

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1369]
Hi, im translating the article related to eval.

I'm confusing this sentence.

Code minifiers (tools used before JS gets to production, to compress it) replace local variables with shorter ones for optimization. That's usually safe, but not if `eval` is used, as **it** may reference **them**. So minifiers don't replace all local variables that might be visible from `eval`. That negatively affects code compression ratio.

Could you specify what it means and them means?

**Comment by iliakan** [comment]
Rewritten thanks.

**Comment by CreatiCoding** [comment]
```text
Code minifiers (tools used before JS gets to production, to compress it) replace local
variables with shorter ones for optimization. That's usually safe, but not if eval is
used, as it may reference them. So minifiers don't replace all local variables that
might be visible from eval. That negatively affects code compression ratio.
```

Is it mean that `Code minifiers` don't replace local varuables from `eval`?

**Comment by iliakan** [comment]
No
