### ISSUE TITLE
Would like to create translation for tamil (ta)

### ISSUE THREAD

**Issue by sivarajans** [javascript-tutorial/en.javascript.info#1370]
Please provide repo to create tamil translation.

maintainers
sivarajans

**Comment by iliakan** [comment]
Done. Got an invite?

**Comment by sivarajans** [comment]
Yes its done.  Thank you

**Comment by sivarajans** [comment]
Hey

Could you please add kishorechandran41 in our github organisation?  

I would like to have him to review and help me.

**Comment by gokatz** [comment]
Hi mates. I would like to help to translate the guide to the Tamil language. How can I get started? TIA for the time 🙂

**Comment by iliakan** [comment]
Join https://github.com/javascript-tutorial/ta.javascript.info =) Submit a PR, write me if no one reacts.
