### ISSUE TITLE
Issue on explanation accuracy about const

### ISSUE THREAD

**Issue by Neo42** [javascript-tutorial/en.javascript.info#1377]
> Variables declared using const are called “constants”. They cannot be changed. An attempt to do so would cause an error...

The explanation in the Variable chapter is a little unclear. Because, as far as I know, you can actually change the value of a const. For example,
```js
const foo = {};
foo.bar = 42;
console.log(foo.bar); // 42
```
I borrowed this example from @mathiasbynens 's great [blog post on es6 `const`](https://mathiasbynens.be/notes/es6-const) written a few years ago. He said const can change but no "rebinding will happen". And I think by "rebinding", he meant "reassignment".

So it is probably better to just change "cannot be changed" to "cannot be reassigned".

**Comment by iliakan** [comment]
That feels like a better word indeed.
