### ISSUE TITLE
questions about string article.

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1382]
Hi, I'm translating [the article regarding String](http://javascript.info/string).

`This feature makes it easier to wrap strings into custom templating or **other functionality**, but **it** is rarely used.`

I wonder it refers to what. Wrapping string into other functionality?
If so, could you share the idea of what it means `Wrapping string into other functionality`?

**Comment by iliakan** [comment]
f`str` allows to call arbitrary `f` on a string.

**Comment by Violet-Bora-Lee** [comment]
Yes i read mdn page regarding that. So, it refers what?

**Comment by iliakan** [comment]
Gave it a minor rewrite. I mean, tagged templates are rarely used, sorry for not making this clear.

**Comment by Violet-Bora-Lee** [comment]
Thanks as always Ilya 👍
