### ISSUE TITLE
Bulgarian [BG] translation

### ISSUE THREAD

**Issue by tmollov** [javascript-tutorial/en.javascript.info#1396]
Hello,

I'm starting to translate the project, here is my repo
https://github.com/tmollov/javascript-tutorial-bg

Thanks.

**Comment by iliakan** [comment]
Are you still enthusiastic about the translation? 
I can make the official Bulgarian repo for you and set you admin.

**Comment by tmollov** [comment]
Of course :)

**Comment by iliakan** [comment]
Ok, sent you an invite.

You might want to port your translations there. Maybe git pull & push or copy.
