### ISSUE TITLE
hard to grasp the sentence on Object.keys, values, entries

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1399]
Hi, I'm translating the article, http://javascript.info/keys-values-entries

It's hard for me to understand the last sentence, `We can make powerful one-liners for more complex transforms this way. It’s only important to keep balance, so that the code is still simple enough to understand it.`.

I think there are some figurative words such as `one-liners` among the sentence. Could you explain more? You don't need to rewrite the sentence because only ME couldn't understand the sentence.  😭😭😭

btw, the tutorial's popularity is growing among Korean readers. Thanks as always.

**Comment by iliakan** [comment]
ok, maybe worth rewriting.

Among programmers, a "one-liner" is an powerful sequence of operations that can be written in one line.

E.g. `array.map(...).filter(...).reduce(...)`.

**Comment by iliakan** [comment]
Thanks as always for your comments.
If something isn't clear for you, it may as well be obscure for others.

**Comment by Violet-Bora-Lee** [comment]
Adding an example is good 👍
what about the second sentence?
I'm confusing the meaning of balance(between what?) and why keeping the balance is important.

**Comment by iliakan** [comment]
rewritten
