### ISSUE TITLE
Add top of article to navigation panel

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1400]
Often there is only a short introduction before the first section with a link in the navigation panel on the left, in which case clicking that link will get you close enough to the intro to read it. But in some cases there is quite a lot of text in the intro section (pages), so that there is no direct way to get to the introductory section without scrolling up. For instance:
https://javascript.info/class-inheritance#overriding-a-method
is the first section in the navigation panel, but it is about 3 screens full of info below the start of the article. So I think it would be good to either have a navigation link for the start of the article, or to add sections where needed so that the first section always starts near the top.

**Comment by iliakan** [comment]
Ok, improved that article a little bit. Intro here was indeed too long and full of code.
