### ISSUE TITLE
Rabbit behavior

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1405]
In "Class inheritance" article, have example:

<pre>
class Rabbit extends Animal {
  hide() {
    alert(`${this.name} hides!`);
  }

  stop() {
    super.stop(); // call parent stop
    this.hide(); // and then hide
  }
}
</pre>

However, having seen many rabbits, I can tell you that they hide **before** they stop, or, more often, they stop and **freeze**, and hope to blend in. At least American rabbits do.

Just sayin'.

**Comment by iliakan** [comment]
Oh, well, our rabbit does that at the same time!

It finds a place, then (stops and hides) there 🐰

**Comment by iliakan** [comment]
Personally, I've seen most rabbits domesticated, they don't hide. So maybe I just don't know enough.

Hares do hide though. But that's another story.

**Comment by paroche** [comment]
Well, when they freeze, they're hiding in plain sight, hoping they'll blend in and not be noticed. And they do blend in pretty well.

**Comment by paroche** [comment]
The hares we have here are jackrabbits (not Apache Jackrabbits, though the Apaches do live not all that far from here). Don't see them nearly as often. They're so fast that dogs I've know that were familiar with them didn't even bother trying to chase them. They may hide after they stop running, but by then they're out of sight anyway.

**Comment by iliakan** [comment]
Oh, I see. In our forests hares just tend to leap somewhere under a tree or to another hideout, and freeze there. 

I'm talking about regular hares, that change color in winter, https://en.wikipedia.org/wiki/Hare. 

That's also something you don't see at the daily basis, there are not so many of them in the outskirts.

So, that was the reason why I put it like that. They jump somewhere, then stop and hide. 

I can surely fix provide additional explanations of that in the article. 🐇 🐇 🐇

**Comment by paroche** [comment]
Yeah, here in the desert scrub, the cottontail bunnies tend to just freeze in place, out in the open.  

But I don't think anyone will have trouble learning class inheritance based on possible discrepancies w/ their experience of real world rabbit behavior.

We have snow here but the jackrabbits (which are hares) don't turn white. Further north there are snowshoe hares that do.

**Comment by lumosmind** [comment]
```
class Rabbit extends Animal {
  eatCarrot() {
    alert(`${this.name} hides!`);
  }

  stop() {
    super.stop(); // call parent stop
    this.hide(); // and then hide
  }
}
```
This can be more understandable without any conflict. Rabbits can't eat while running. 
And this refers to Bugs Bunny. so funny and so geeky :)

**Comment by iliakan** [comment]
Guess, there's consensus here. Rabbits are different, but can be trained.
