### ISSUE TITLE
Brazilian Portuguese [pt-BR] Translation

### ISSUE THREAD

**Issue by fernanDOTdo** [javascript-tutorial/en.javascript.info#1412]
Hello! There's an effort to translate javascript.info to Portuguese, but they're using both Brazilian Portuguese and European Portuguese. I think that can hurt the final result for both Brazilian and European users.

I would like to start a Brazilian Portuguese translation ( https://en.wikipedia.org/wiki/Brazilian_Portuguese ).

Language code: **pt-BR**
Maintainers: **@fernanDOTdo - fern@ndo.io**

Thank you!

**Comment by iliakan** [comment]
Wikipedia only has the single Portuguese, right?

**Comment by iliakan** [comment]
Only https://pt.wikipedia.org/

**Comment by fernanDOTdo** [comment]
@iliakan Yes. Wikipedia also has only one English as well. Because most of users write articles using US english, you don't see too much difference.
There's some attempt to create a pt-BR Wikipedia as well: https://meta.wikimedia.org/wiki/Requests_for_new_languages/Wikipedia_Brazilian_Portuguese

Brazilian Portuguese is really different than European Portuguese and reading "ficheiros" instead of "arquivos" (different translation for "files") and vice-versa is a turn off to both audiences.

**Comment by iliakan** [comment]
If even Wikipedia struggles with creating two different versions, we, being a smaller community, have even more reasons to concentrate on one of them.

Right now, we don't have any Portuguese at all.

**Comment by iliakan** [comment]
I really hope there's a way to write somewhat understandible text suitable for both audiences.
