### ISSUE TITLE
get/set syntax vs. getProp()/setProp(): hidden complxity

### ISSUE THREAD

**Issue by htho** [javascript-tutorial/en.javascript.info#1437]
http://javascript.info/private-protected-properties-methods

Id like to add Another aspect about the advantages of using getProp()/setProp() over the get/set syntax:

The sytax suggests that the value is "just there". Although it might in fact call other costly functions. If I knew that as the user of an API, id cache the value instead of requesting it over and over again.

It is a good practice to use get/set only in order to limit access to actually existing members. A "synthetic" member should be called as a function and communicate that it has costs.

**Comment by iliakan** [comment]
That's somewhat debatable. Sometimes performance matters, sometimes it doesn't. Let people think for themselves. These are general programming issues.

We could add a minor note about that though.

**Comment by htho** [comment]
> We could add a minor note about that though.

Thats what I was hoping for. I see it in the "Getter/setter functions" Info-Box.

**Comment by iliakan** [comment]
Could you submit a PR?
