### ISSUE TITLE
js showing in window

### ISSUE THREAD

**Issue by dannyk3941** [javascript-tutorial/en.javascript.info#1448]
going through the js fundamentals section, I am coming across JS that is displayed on the page for some reason. 
![Screen Shot 2019-10-12 at 11 20 19 PM](https://user-images.githubusercontent.com/52807859/66710462-fa0a8d80-ed46-11e9-977a-153e8f188948.png)

**Comment by iliakan** [comment]
1. Try in another browser?
2. Tell me OS and browser version.
3. Tell me exactly the URL of the page.

Thanks!

**Comment by dannyk3941** [comment]
@iliakan this issue can be closed, it was caused by a Firefox extension for changing geolocation. 

Thanks!
