### ISSUE TITLE
For the animal, the plural is also 'elk'

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1449]
One elk, two elk, look at all those elk.

"Deer" and "moose" work the same way.

Kind of unfair, I know.

https://www.dictionary.com/browse/elk

Don't get me started on cows.

**Comment by iliakan** [comment]
Wait a minute, I look at the link that you provided and see: "noun, **plural elks**".

**Comment by paroche** [comment]
Read a little further: "elk for 1, 2."

1 & 2 are animal meanings.

**Comment by iliakan** [comment]
Oh. Right. 

Is the overall text ok? We can change it to other animals or anything else if needed.

**Comment by paroche** [comment]
As far as I've noticed, overall text OK.

Could change animal, though I did kind of want to know the truth about elk, once it was suggested there was something to know. 

Or could just change "elks" to "elk". Problem solved?

Or make it about the Benevolent and Protective Order of Elks, rather than about the cunning animals.

Or make it about otters, or raccoons, or bears, or honey badgers. Maybe you could explain under what circumstances honey badgers might actually care.

**Comment by iliakan** [comment]
That's just any text. Wondered if it sounds too odd for USA =)

**Comment by iliakan** [comment]
Should be a little bit odd and funny.

**Comment by paroche** [comment]
Then "honey badgers" is looking promising.

**Comment by iliakan** [comment]
Oh, and also should be somewhat easy to translate.

Honey badgers may be cool, but many people from other countries and languages may not know what they are 😸

**Comment by paroche** [comment]
I thought everyone from Timbuktu to Outer Mongolia and beyond had seen the video.
[(https://www.youtube.com/watch?v=4r7wHMg5Yjg)]

**Comment by iliakan** [comment]
Guess they did. What for the others? =)

**Comment by paroche** [comment]
That was supposed to be kind of inclusive of everywhere, but, ... hmmmm....

Well, can't use caribou or reindeer -- same problem. Also, pretty much, same animal.

Or sheep. One sheep, two sheep.. ... ... zzzzzzz

If you have any vital truths to share about mice, now would be the time. One mouse, two mice, ...

Or, as I said, could just change "elks" to "elk". Would still make sense, would it not? "The truth about elk"..."An elk is...". I don't see a problem with that. And so little to change.

**Comment by iliakan** [comment]
Okay. Elk now. All pictures updated as well.

**Comment by paroche** [comment]
OK. 

If you didn't want to go with a noun whose plural was the same as the singular, but that could be a little bit funny or odd, and was easy to translate, I was thinking "ducks". Maybe not as out-of-left-field as elk, but if needed you would have built-in duck names like Daffy, Donald, Daisy, and Scrooge, plus Huey, Dewey, and Louie (the last three also doubling as (Junior) Woodchucks)*. 

*Woodchuck is the same as Ground Hog (type of marmot found in USA and Canada, famous for being used to predict the end of winter, and for a movie), but the Junior Woodchucks is a fictional idealistic and rigorous Boy Scout-like group the young ducks Huey, Dewey, and Louis belong to, or at least did at one time.

🌈 The more you know... ✋✋✋🌈

[(https://en.wikipedia.org/wiki/The_More_You_Know)]

**Comment by paroche** [comment]
Coincidence? For the first time in months, I received an email today (besides from GitHub) with "elk" in the subject line:

_Tell the U.S. Forest Service to make the right decision for Rocky Mountain elk.
 
...Every fall, bull elk announce the beginning of mating season with distinctive bugling calls. Soon after, elk begin their seasonal migration from the upper summer range to lower winter habitat where food is more available. Unfortunately, these migration pathways are increasingly under threat from new roads, development, and other habitat fragmentation.We must act now. Will you tell the U.S. Forest Service to protect elk habitat in the Caja del Rio management area in the Santa Fe National Forest today? PROTECT ELK HABITAT
etc...etc...etc..._

And didn't receive a single email about honey badgers or ducks. 

If I believed in omens...

**Comment by iliakan** [comment]
=))))))
