### ISSUE TITLE
This way is more reusable and expandable

### ISSUE THREAD

**Issue by wonder13662** [javascript-tutorial/en.javascript.info#1455]
https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto

```
// https://javascript.info/prototype-inheritance#why-two-hamsters-are-full

let hamster = {
  stomach: null,

  eat(food) {
    if (!this.stomach) {
      this.stomach = [];
    }
    this.stomach.push(food);
  }
};

let speedy = {
  __proto__: hamster
};

let lazy = {
  __proto__: hamster
};

// This one found the food
speedy.eat("apple");
console.log(speedy.stomach); // apple

// This one also has it, why? fix please.
console.log(lazy.stomach); // apple
```

### What I did?
1. Set null to the stomach of Animal. Because if we set the array to the stomach of Animal, the inherited object will refer the same array reference unless it has own stomach.
2. When the user calls the method - eat, logic checks whether stomach refers the valid array or not. If not, assign a new array on its caller scope(context). So every inherited object could have its own stomach. They don't share the state of the stomach anymore.

### Why is it better?
1. I just changed the method in the hamster object. Therefore every object inherited from the hamster object doesn't need to set their stomach by a new array. We can reuse that code.

**Comment by iliakan** [comment]
That's also fine, but not much different. A bit more complex though, and we don't need that complexity =)
