### ISSUE TITLE
example on Proxy article

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1460]
Hi, I'm translating the Proxy article.

I think there are some changes regarding Proxy on Chrome's engine.

When I run the example(below) I can see the alert and the message says that there is Error, not TypeError.

![image](https://user-images.githubusercontent.com/6451384/66858576-84abf080-efc4-11e9-98ad-c261fc09ca86.png)

**Comment by iliakan** [comment]
I updated the internal try..catch to show `error type : error message`.

Please try again.

**Comment by Violet-Bora-Lee** [comment]
Cool :) Thanks 👍 👍 👍 
https://github.com/javascript-tutorial/engine/commit/a66f763e287ee74b0dd1cf3bd63c1855b07e3804
