### ISSUE TITLE
WRONG CHARACTER @ regexp-greedy-and-lazy

### ISSUE THREAD

**Issue by JasonBastin** [javascript-tutorial/en.javascript.info#1481]
At the end of the "witch" and "broom" examples, there's a wrong character in the paragraph:

"In this example we saw how the lazy mode works for +?. Quantifiers +? and ?? work the similar way – the regexp engine increases the number of repetitions only if the rest of the pattern can’t match on the given position."

The second +?, after the word "Qualifiers", should be a *?. 

Also, the "witch" and "broom" example seems to be unfinished. The original objective was to replace the quotation marks with guillemet marks but the example stops before that step. I'm curious as to how that would be done, so could you add it in?

Thanks for the clear and concise website. It's been as helpful as any for someone teaching themselves.

**Comment by JasonBastin** [comment]
Hey Ilya,

I am new to this, so forgive me if this is a stupid question/response.

In the example of the witch and her broom, I know how to replace ("witch"
and "broom") with (<<witch>> and <<broom>>) directly, but I don't know how
to make it so I find any word with quotes and replace it with '<< >>'.

Thanks,
Jason














#

**Comment by iliakan** [comment]
`str.replace(/"([^"]*)"/gm, '<<$1>>') ?`
