### ISSUE TITLE
ChildNode.remove() not supported by IE 

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1503]
It is my understanding that ChildNode.remove() (_node_.remove) is not supported by IE. Is IE too irrelevant, will it always be handled by polyfilling w/ Babel or something, or does this deserve a mention?

https://javascript.info/modifying-document#node-removal

https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove

**Comment by iliakan** [comment]
IE is mostly irrelevant, but for some countries it matters, and then it's polyfilled very easily.

**Comment by paroche** [comment]
OK, just checking.
