### ISSUE TITLE
Inspecting the DOM in 'Why does "aaa" remain' task

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1512]
In "Modifying the Document", for this task, the solution states:

"The question can be easily answered by exploring the DOM using the browser tools. It shows "aaa" before the <table>."

However, my experience is that you can only see "aaa" before the <table> if you have disabled 'table.remove()' in the script first. Otherwise there is no table in the DOM to see. And the alert before the 'table.remove()', only shows "[object HTMLTableElement]".

**Comment by iliakan** [comment]
May I ask for a screenshot, of what seems wrong?

**Comment by paroche** [comment]
HTML from task:

![Screenshot (2)](https://user-images.githubusercontent.com/46547072/67467404-e8a66880-f605-11e9-9713-110ea6903ca2.png)

view of Elements in DevTools:

![Screenshot (1)](https://user-images.githubusercontent.com/46547072/67467067-6027c800-f605-11e9-9090-d4c4537be8f0.png)

Of course, script has removed table, so can't see that "aaa" was moved out of table unless "remove" is deactivated. Like this:

![Screenshot (3)](https://user-images.githubusercontent.com/46547072/67467744-91ed5e80-f606-11e9-92ed-969f86ffdf77.png)

Which then allows you to see this in DevTools:

![Screenshot (4)](https://user-images.githubusercontent.com/46547072/67467910-dc6edb00-f606-11e9-8255-291e86bbea07.png)

**Comment by iliakan** [comment]
The idea of the task was to show that even if we put something inside HTML, in improper place, the browser will "fix" the DOM by moving it out.

I'm not sure where's the misunderstanding. But maybe you could suggest a fix?

**Comment by paroche** [comment]
Yes, that part was fine and good information to have. What I was saying, though I see now that part of my comment was missing, because I hadn't put a "\" before the table tags, was, and I quote (myself) (tried to put the below in italics but it didn't work):

"quote"-------

In "Modifying the Document", for this task, the solution states:

"The question can be easily answered by exploring the DOM using the browser tools. It shows "aaa" before the \<table>."

However, my experience is that you can only see "aaa" before the \<table> if you have disabled 'table.remove()' in the script first. Otherwise there is no table in the DOM to see.

"end quote"------

My only issue is that it doesn't appear to me that the question can be "easily answered by exploring the DOM using the browser tools", exactly, because after the script runs there is no longer a table in the DOM to be seen (though, of course, the "aaa" is still there), so the person would have to disable the script (or, specifically, the remove statement) in order to see the "aaa" before the table. And I thought that deserved mentioning.

**Comment by iliakan** [comment]
Please make the PR, it will be the best.

P.S. You could put the backticks ` around the table tag.

**Comment by paroche** [comment]
OK (to PR).

But I think one "\" is easier than two " ` "s. Seems to work :-)

**Comment by iliakan** [comment]
`<table>` "table"

**Comment by iliakan** [comment]
the second (Empty) is a quoted table tag ^^.

**Comment by paroche** [comment]
Sorry, should have looked at the preview. Meant to say one "\\" is easier than two " \` "s. 

If you don't need it to show in `code` style. (i.e. if \<table> is as good as `<table>`).
