### ISSUE TITLE
meaning of "it"

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1516]
Hi, I'm translating the article regarding class inheritance.

https://javascript.info/class-inheritance

I wonder what it means in both sentences.

- As we can see, it basically calls the parent constructor passing **it** all the arguments.

- When a normal constructor runs, it creates an empty object and assigns **it** to this.

**Comment by iliakan** [comment]
Tweaked the wording a little bit. Please tell me, is it better now?

I'd love everything to be clear without any possible confusion. 
Thanks!

**Comment by Violet-Bora-Lee** [comment]
```suggestion
When a normal constructor runs, it creates an empty object and assigns the object to `this`.
```
Umm... I think previous explanation focused on constructor is better.

Adding new contexts such as `new F` could make readers confused.

It's just my opinion. 

Thanks for your update as always 👍

**Comment by iliakan** [comment]
M'kay, tweaked a bit more =)
