### ISSUE TITLE
Tutorial map's search box doesn't work

### ISSUE THREAD

**Issue by haond10adp** [javascript-tutorial/en.javascript.info#1522]
![image](https://user-images.githubusercontent.com/39975444/67628925-756c5300-f8a0-11e9-955a-5bb1a91cbda3.png)

**Comment by iliakan** [comment]
How to reproduce that? :)

**Comment by haond10adp** [comment]
> How to reproduce that? :)

Your docs are great, I am reading it, just a little let down when a function doesn't work correctly. Documentations are meant to be authoritative, just remove the function altogether, problem solved

**Comment by iliakan** [comment]
Which function to remove? 

Things are working fine for me, I'd like to see the error.

**Comment by haond10adp** [comment]
https://github.com/javascript-tutorial/en.javascript.info/issues/1522#issue-512912388
I can't search in the 'tutorial map' modal in desktop

**Comment by iliakan** [comment]
@haond10adp I tried to search, and everything's fine for me.

You just get http://javascript.info/comparison?map in Chrome on Windows and type something in the "Search" field or what?

**Comment by haond10adp** [comment]
I wake up, start my computer and the problem's solved. Issues closed, thank for the response
