### ISSUE TITLE
redundant Timeout Error

### ISSUE THREAD

**Issue by lumosmind** [javascript-tutorial/en.javascript.info#1523]
Examples about  "**before/after and beforeEach/afterEach**"  is not usefull. Because, it gives **Timeout Error** when we use **makeTest** function and create a lot of test checks. So, we must use **console.log** function instead of **alert** function for **beforeEach** and **afterEach** functions.

**Comment by iliakan** [comment]
Where is the problem exactly?

**Comment by lumosmind** [comment]
alert() function waits us for user interaction and this waiting process takes time. Mocha try to finish test in limited time. so I take a lot of error when I can't click super fast to **ok** button of aler() function message.

**Comment by iliakan** [comment]
Maybe just increase timeout? 
`console.log` requires people to open the console, while `alert` doesn't.

```
describe...{
 this.timeout(500);
}
```

**Comment by lumosmind** [comment]
Example code isn't executable in article or it doesn't have link to plunker. It is just static code and readers need to copy and paste the code to their local .js file and run. opening console can't be a problem for readers at this level. (They are learning unit test.)
Before the article they already have read **Debugging in Chrome** article. 

`describe...{
 this.timeout(500);
}`
thanks this code solve my issue but article needs more touch.
