### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by tozaicevas** [javascript-tutorial/en.javascript.info#1540]
- Language code: **lt**
- Maintainer: **tozaicevas** **tozaicevas@gmail.com**

**Comment by iliakan** [comment]
How about to join https://github.com/javascript-tutorial/it.javascript.info ?

**Comment by tozaicevas** [comment]
> How about to join https://github.com/javascript-tutorial/it.javascript.info ?

I don't think my Italian would be of any help :D

**Comment by iliakan** [comment]
Oh sorry, it's not IT, but LT (Lithuanian) ?

**Comment by tozaicevas** [comment]
Yes!

**Comment by iliakan** [comment]
Done, invite sent! =)
Hope you'll make a great translation!
