### ISSUE TITLE
question during translating async/await

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1548]
Hi, I'm translating http://javascript.info/async-await.

If `await` gets a non-promise object with `.then`, it calls that method providing **native functions** `resolve`, `reject` as arguments. Then `await` waits until one of them is called (in the example above it happens in the line `(*)`) and then proceeds with the result.

I wonder what native functions mean here. alert and setTimeout? or resolve and reject?

**Comment by iliakan** [comment]
I mean that `resolve/reject` come from the language itself. Just like in a promise executor.

How I should rephrase to make that obvious?

**Comment by Violet-Bora-Lee** [comment]
What about using dashes like below?

If `await` gets a non-promise object with `.then`, it calls that method providing **native functions** —`resolve`, `reject`—as arguments. Then `await` waits until one of them is called (in the example above it happens in the line `(*)`) and then proceeds with the result.

**Comment by iliakan** [comment]
Added a few words.
