### ISSUE TITLE
Incorrect explanation of object to primitive 

### ISSUE THREAD

**Issue by dheeraj-br** [javascript-tutorial/en.javascript.info#1569]
Issue in the section 'Object to primitive conversion' under the 'toString/valueOf' [here](http://javascript.info/object-toprimitive#tostring-valueof) as well as in the summary section

It is implied that while converting Object to string the _toString_ is called first if its not present then _vallueOf_ is called, this is not correct, because if _toString_ is not present javascript calls the Object.prototype's _toString_ method which outputs "[Object Object]"

Here is Demo on JsBin https://jsbin.com/vikisihosa/edit?js,output

**Comment by iliakan** [comment]
Sorry for confusion, I added more explanations about that, to make things clearer.

P.S. We can't mention `prototype` in this section of the tutorial, so I'm talking about "default" `toString`.
