### ISSUE TITLE
generator

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1608]
Hi, I'm reading http://javascript.info/generators

In the section, http://javascript.info/generators#yield-is-a-two-way-road there is an example.

In the example of the section,  http://javascript.info/generators#yield-is-a-two-way-road, there is `(*)` but no mention about this in the explanation below.

![image](https://user-images.githubusercontent.com/6451384/68765618-89fe6880-0660-11ea-9154-e987e49b80f5.png)

I think it need to be mentioned.

Btw, this article is the most well-explained article regarding Generator! so cool :)

**Comment by iliakan** [comment]
You're totally right!

Added a few words about that. We've almost finished the upgrade of Elastic and plan to deploy this fix and Korean tomorrow, if our testing of the latest version go well.
