### ISSUE TITLE
albanian languaage

### ISSUE THREAD

**Issue by ardianpjetri** [javascript-tutorial/en.javascript.info#1611]

**Comment by ardianpjetri** [comment]
Translate into Albanian language

**Comment by iliakan** [comment]
Are you familiar with github? No language code too.

**Comment by ardianpjetri** [comment]
Not too familiar with GitHub
Albanian language
Please help me because I want to learn from you and why not translate it
for other peoples here.
If it is possible send me resources so I can translate them.
Thanks!

Më Pre, 15 Nën 2019, 20:51 Ilya Kantor <notifications@github.com> shkroi:
