### ISSUE TITLE
typeof null is written off as an error in the language

### ISSUE THREAD

**Issue by zhirzh** [javascript-tutorial/en.javascript.info#1619]
The article _js/first-steps/types_ states that `typeof null` being `"object"` is _an officially recognized error_.

I tried looking for any official material where this was addressed but couldn't find any. I also looked into the latest released spec from June 2019 and found something that contradicts this statement. The table [`typeof` Operator Results][1] lists the result for `typeof null` to be exactly `"object"`.

Is this accurate or did I miss something?

https://github.com/javascript-tutorial/en.javascript.info/blob/79417c6e73645d37f184f0cc7e4bc3353e85224f/1-js/02-first-steps/05-types/article.md#L223

[1]: https://www.ecma-international.org/ecma-262/index.html#table-35

**Comment by srishtiBajpai** [comment]
Hey! Would like to work on this issue

**Comment by iliakan** [comment]
A word from Brendan Eich, I believe.
