### ISSUE TITLE
The link doesn't follow the url

### ISSUE THREAD

**Issue by koala-lava** [javascript-tutorial/en.javascript.info#1622]
In this page the first task. Clicking on the link doesn't follow to w3.org. Something is not right.
https://javascript.info/default-browser-action

**Comment by masterashu** [comment]
This reason for this behavior is the url defined in `<a>` tag. It refers to http while initial of site is https so most modern browsers will block the request.
On chrome developer console the following error is shown:
![image](https://user-images.githubusercontent.com/39612799/69640064-b7e1a500-1083-11ea-84d4-c99b6f3117cb.png)
