### ISSUE TITLE
Unexpected token Error in example

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1623]
While I'm running this example on https://javascript.info/private-protected-properties-methods, I encountered Syntax Error.

Is the error you intended?

<img width="641" alt="20191124_162149" src="https://user-images.githubusercontent.com/6451384/69491297-a4450b80-0ed6-11ea-94a3-2889b072ebe2.png">

**Comment by iliakan** [comment]
Yes. Private methods are not supported yet. Private fields should work fine though.
