### ISSUE TITLE
Named Function Expression (https://javascript.info/function-object )

### ISSUE THREAD

**Issue by FDV79** [javascript-tutorial/en.javascript.info#1638]
**_"There’s no such thing for Function Declaration
The “internal name” feature described here is only available for Function Expressions, not for Function Declarations. For Function Declarations, there is no syntax for adding an “internal” name.
Sometimes, when we need a reliable internal name, it’s the reason to rewrite a Function Declaration to Named Function Expression form."_**

I tried to use the same name of the function as an internal name using a Function Declaration and it worked

function func(who) {
  if (who) {
    alert(`Hello, ${who}`);
  } else {
    func("Guest");
  }
};

function func(who) {
  if (who) {
    alert(`Hello, ${who}`);
  } else {
    func("Guest");
  }
};

func('Frank') //Hello, Frank
func() //Hello, Guest

**Comment by iliakan** [comment]
Forgot use strict? Also, are there two code samples or one?

**Comment by FDV79** [comment]
I used the Eloquent JavaScript Code Sandbox (that doesn't use the use strict)
It's one code sample (sorry, probably I pasted a part of the code 2 times).

By the way, it seems that it works with 'use strict' too:


'use strict'

function func(who) {
  if (who) {
    alert(`Hello, ${who}`);
  } else {
    func("Guest"); // Now all fine
  }
};

func('Frank') //Hello, Frank
func() //Hello, Guest

**Comment by iliakan** [comment]
This is not NFE, just a regular function call.
