### ISSUE TITLE
Type conversions on strings

### ISSUE THREAD

**Issue by CyberMew** [javascript-tutorial/en.javascript.info#1646]
https://javascript.info/type-conversions

> This only happens when **at least** one of the arguments is a string. Otherwise, values are converted to numbers.

This is confusing as it implies that as long as an expression contains a string, the whole expression will be a string. However based on the example `4 + 5 + "px"` which gives `9px`, this is not the case. I understand the "arguments" to be for `+`, but it can also be read as arguments for the `alert()` function. I think being a little more explicit is better here. Maybe state something like only the immediate left and right operands of the + operator is affected? And the expression is evaluated from left to right (or by operator precedence)?

**Comment by CyberMew** [comment]
Just saw https://javascript.info/operators after type-conversions, perhaps operators should come first? After all we need operators to use some of the type conversions.

**Comment by iliakan** [comment]
Good catch! Thanks!
