### ISSUE TITLE
request to change the term 'spread operator' to 'spread syntax'

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1669]
Could you refer to these articles and update the tutorial?

https://github.com/tc39/ecma262/issues/1295

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by iliakan** [comment]
Ok, I will. Or you can make a PR :)

**Comment by Violet-Bora-Lee** [comment]
It's better you to update the tutorial to maintain consistency :)

There are some articles using the term, the spread operator, and I could make a mistake when I change many articles...
