### ISSUE TITLE
The JavaScript language->JavaScript Fundamentals->Loops: while and for

### ISSUE THREAD

**Issue by momirmarkovic** [javascript-tutorial/en.javascript.info#1674]
Hello dear guys,

You have made really good job with this Tutorial!

I noticed 1 small thing in the section: 'The JavaScript language'-> 'JavaScript Fundamentals'-> 'Loops: while and for'-> 'Breaking the loop':

In your example, you say: 
'The 'break' directive is activated at the line (*) if the user enters an empty line or cancels the input.' You missed to say, that it occurs, also, if the user enters a 0 (number zero).

Kind regards from the passionate beginner,
Momir Marković

Now- receive my apology!
I noticed wrong, because I've missed that the input, in 'prompt' window, is always a string (so- it can't be a number).  :-)

**Comment by lex111** [comment]
We can close this issue?

**Comment by momirmarkovic** [comment]
Yes surely.
My apology again!

чет, 19. дец 2019. у 21:23 Alexey Pyltsyn <notifications@github.com> је
написао/ла:
