### ISSUE TITLE
German Language

### ISSUE THREAD

**Issue by 1H0** [javascript-tutorial/en.javascript.info#1676]
Hey there! I would like to start the translation to German!

**Language code:** `de`
**Maintainers:**
- @1H0

Cheers
Lukas

**Comment by Violet-Bora-Lee** [comment]
Cool! I wonder why the german version hasn't started yet 👍

**Comment by iliakan** [comment]
Sure! I created it, got an invite?

**Comment by 1H0** [comment]
Yes, I did! Thank you!
