### ISSUE TITLE
Misleading Statement "We can copy a function to another variable" in Function-Expressions Tutorial

### ISSUE THREAD

**Issue by pragun-sharma** [javascript-tutorial/en.javascript.info#1685]
Funcitons are a special type of objects. They can be assigned from one variable to another. However, saying that " `func = sayHi` copies function" is misleading.

Here is why:
```
var a = function abc(){};
b = a;
a.x = 1;
console.log(b.x) //prints '1'
```
`a.x = 1` attaches variable `x` to the function object referenced by `a`.
It's availablity from `b` means that only reference of object was copied at the time of `b=a` and not object cloning/copying.

![image](https://user-images.githubusercontent.com/21987886/71307425-252eee80-2414-11ea-8fbe-dae971a608dd.png)

**Comment by iliakan** [comment]
That's called "copy by reference". At that stage of the tutorial, we don't cover the concept as a whole.
