### ISSUE TITLE
Add transalation for sounth indian language - malayalam

### ISSUE THREAD

**Issue by Amalkarunakaran** [javascript-tutorial/en.javascript.info#1686]
Hi,
add transalation for sounth indian language - malayalam 
English name of Language - Malayalam
ISO 639-1 Language Code - ml
ISO 639-2 Language Code - mal

i i'll help to transalate
maintainers : amal324@gmail.com
https://github.com/Amalkarunakaran

**Comment by iliakan** [comment]
Are you sure the translation will be finished and published? Enough maintainers?
