### ISSUE TITLE
Add translation for Indian language Telugu - te

### ISSUE THREAD

**Issue by AkhileshwarReddy** [javascript-tutorial/en.javascript.info#1696]
Add translation for Indian language Telugu - te
Language code: ISO 639-1 : te
Language code: ISO 639-2 : tel
nick: AkhileshwarReddy
email: akhil.vedas@outlook.com

**Comment by iliakan** [comment]
Still actual?

**Comment by AkhileshwarReddy** [comment]
Yes

**Comment by iliakan** [comment]
Created. Got an invite?
