### ISSUE TITLE
Add translation for turkmen language - tk

### ISSUE THREAD

**Issue by hallayev289** [javascript-tutorial/en.javascript.info#1701]
Add translation for Turkmen language - tk
Language code: ISO 639-1 : tk
Language code: ISO 639-2 : tuk
nick: mekkush
email: mekanhallayev1@gmail.com

**Comment by iliakan** [comment]
Are you the only maintainer? Will the translation be finished?

**Comment by hallayev289** [comment]
Yes for know I am only but I really want to start contribute. And thank you for your respond

**Comment by hallayev289** [comment]
@iliakan please open us new repository to translate "turkmen" language

**Comment by iliakan** [comment]
Done!

**Comment by iliakan** [comment]
Sent you the invitation.
