### ISSUE TITLE
A sintax error

### ISSUE THREAD

**Issue by jacobo12montes** [javascript-tutorial/en.javascript.info#1703]
Does this explication looks good?

"The reason is that an equality check == and comparisons > < >= <= work differently. Comparisons convert null to a number, treating it as 0. That’s why (3) null >= 0 is true and (1) null > 0 is false."

The last word of the sentence above should be "TRUE".
Thanks

**Comment by Violet-Bora-Lee** [comment]
Have you run the script on the page?

https://javascript.info/comparison#strange-result-null-vs-0

It seems that the explanation is correct for me.
