### ISSUE TITLE
Async/await chapter should mention new features

### ISSUE THREAD

**Issue by JoelVenable** [javascript-tutorial/en.javascript.info#1716]
There is a new TC39 proposal in stage 3 for "Top level await" that allows use of await inside the "global" scope of a javascript module.  This information should likely be positioned in the "info" boxes alongside the current discussion that it is not possible in the global scope.

https://github.com/tc39/proposal-top-level-await

Also, it might be worth mentioning the IIAFE pattern:

```
(async () => { 
  await doSomething()
  await doSomethingElse()
})()

// or: 

(functionThatReturnsPromise)()
```

**Comment by iliakan** [comment]
Not stage 4 yet.
