### ISSUE TITLE
Script stops working suddenly with error "SyntaxError: Unexpected token class"

### ISSUE THREAD

**Issue by Hirendiks** [javascript-tutorial/en.javascript.info#1718]
Script stops working suddenly with error "SyntaxError: Unexpected token class"

It is stopping at below code:

var toClass_ = {}.toString;
function objIsClass_(object,class) {
  return (toClass_.call(object).indexOf(class) !== -1);
}

I am not able to identify what is wrong with it as existing scipts are working on it but newly created are not.
Please suggest on urgent basis.

**Comment by Violet-Bora-Lee** [comment]
Could you specify the path of the script or the path of the article containing the script?

**Comment by iliakan** [comment]
Please provide more details about the script and the browser. Presumably, your browser is too old.
