### ISSUE TITLE
Lesson 2.2 Page navigation is wrong

### ISSUE THREAD

**Issue by aploskov** [javascript-tutorial/en.javascript.info#1721]
This page contains 2 anchors `comments` and it doesn't work right. Both anchors links to the Discuss section instead of lesson's `comments` part.

**Comment by Violet-Bora-Lee** [comment]
What is Lesson 2.2?

**Comment by aploskov** [comment]
> What is Lesson 2.2? Could you specify the link to the page?

[Code structure](https://javascript.info/structure)

**Comment by iliakan** [comment]
Hopefully fixed.
