### ISSUE TITLE
ko.js.cs server problem

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1722]
https://github.com/javascript-tutorial/ko.javascript.info/issues/449

Hello, the TEAM!

There is a problem with ko.js.cs server.

```
ko.js.cx’s server IP address could not be found.
```

Could you look at it?

You can see the issues on the several pages having demos.

e.g., https://ko.javascript.info/testing-mocha

**Comment by iliakan** [comment]
Hi @Violet-Bora-Lee , I'm a kind of on vacations, but still eager to look into the problem!

Found a small DNS issue, resolved, is it ok now?
