### ISSUE TITLE
Contents might need to be updated regarding assigning transitionend event handler using DOM-property

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1739]
![image](https://user-images.githubusercontent.com/6451384/74049269-20031e80-4a17-11ea-83f6-28298d2a802c.png)

Hi. I was reading the article, [Introduction to browser events](https://javascript.info/introduction-browser-events) and have found some inconsistency regarding assigning `transitionend` event handler using DOM-property.

I've run the example on Chrome and Firefox, and found the first handler works on both browsers.

Engines might be changed I guess.

P.S. If so, where do you find the information to update the article?

**Comment by iliakan** [comment]
The quoted footnote says the "in most browsers only the second handler works, not the first one".

Do you have a different experience?

**Comment by Violet-Bora-Lee** [comment]
First one is also working
I edited the issue

**Comment by iliakan** [comment]
Indeed, that changed some time ago.

**Comment by Violet-Bora-Lee** [comment]
Cool! The new version makes sense.

Btw, how can I find the methods working only with `addEventListener`?
Do you reference the specification to get information in this case?

**Comment by iliakan** [comment]
There are methods `on*`, specified in various specifications (as extensions to existing interfaces).

Those events that have corresponding `on*` methods, can be handled using them.
