### ISSUE TITLE
One example not working regarding event delegation

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1741]
In the article, https://javascript.info/event-delegation, this example is not working.
There is `Uncaught SyntaxError: Identifier 'Menu' has already been declared`.

![image](https://user-images.githubusercontent.com/6451384/74090231-5b235180-4aec-11ea-9ef1-676661438501.png)

I've tested on Chrome and Firefox.

**Comment by iliakan** [comment]
Maybe you run another example that declared `Menu`?

**Comment by iliakan** [comment]
Added `untrusted` into the article text, so it runs in a separate frame every time.
