### ISSUE TITLE
"Proxy and Reflect" article -- navigation to top of page difficult

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1742]
Since there is nothing in the navigation pane for jumping to the beginning of the article, the intro, which is pretty long, can "only" be accessed by jumping to the top of the section below it (technically the "first" section) then scrolling up (for several screens, to get to the beginning). So, if navigation to the beginning of the article is not to be a feature, the intro should probably be broken up into a short intro followed by navigable section.

First section: https://javascript.info/proxy#default-value-with-get-trap

**Comment by iliakan** [comment]
Thanks, but did you try "page up" and something like "ctrl + page-up"?

Usually, there's a keyboard shortcut to move to the top of the article.

Still I'm pinging @Bezart, our designer, what you think: is an easy "go to top" link needed?

**Comment by paroche** [comment]
In Chrome, ctrl + PgUp switches you to the previous tab (and ctrl + PgDn moves you to the next tab -- new info to me, good to know). 

As is often the case, ctrl + Home works for top-of-page. That's why I put "only" in quotes. 

But if you're going to keep the long intro section, then I do think a link to the start of the article would be better.

**Comment by iliakan** [comment]
Indeed 😸  🚀
