### ISSUE TITLE
Contradiction between text and diagram on order of microtasks vs rendering?

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1747]
In the article:
`https://javascript.info/event-loop`

From the comments:

_`Stanislav Nesnov  Devil Says Hi • 17 days ago • edited
"Immediately after every macrotask, the engine executes all tasks from microtask queue, prior to running any other macrotasks or rendering or anything else."
This statement from the text contradicts to the last Event Loop diagram which shows rendering happens in between Macrotask and Microtasks execution._

Looks that way to me too.

**Comment by iliakan** [comment]
The picture gives the following sequence:
`setTimeout` → microtasks → rendering → `mousemove` → ...

Do you perceive it another way?

**Comment by paroche** [comment]
In the diagram labeled "Event Loop" on the left, I see in the loop on the right:
<pre>
script
  render
  microtasks
mousemove
  render
  microtasks
setTimeout
  (loop back to 'script')
</pre>

but then it immediately says:
"All microtasks are completed before any other event handling or rendering or any other macrotask takes place."

**Comment by iliakan** [comment]
Do you read the events as they happen from top to bottom OR from bottom to top?

**Comment by paroche** [comment]
Following the direction of the arrow -- clockwise, which on the right, is from top to bottom as laid out above.

**Comment by paroche** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/46547072/74312088-31f20380-4d2e-11ea-9b89-0236bcd3bbdd.png)

**Comment by paroche** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/46547072/74312356-ca888380-4d2e-11ea-8318-fd38adcdb29f.png)

**Comment by iliakan** [comment]
In the first version of this picture, the order was top to bottom.

But many people were actually reading it as events happen bottom to top, so I repainted it, and now it's bottom to top: first `setTimeout`, then `microtasks`,and so on. 

I'm not sure about which order is correct, but as different people see it differently, looks like both are (somewhat).

I added the note about it being bottom to top.

**Comment by paroche** [comment]
Are you going to change the direction of the arrow?

**Comment by iliakan** [comment]
If I do so, many people will still be mistaken. I added a note just above the picture.

**Comment by paroche** [comment]
Having the loop arrow point clockwise (down) while execution order runs counter-clockwise (up) is what you want? I don't get that at all.

**Comment by iliakan** [comment]
Yeah, the first edition of the picture had the arrow reversed.

And people didn't get it, I got complains :/

**Comment by paroche** [comment]
With arrow pointing in the opposite direction to the order of execution, I'd think you may get complaints now. Don't see how it makes sense to have arrow pointing that way with items in order they are. What if you reversed the order of the events themselves? (setTimeout on top, then microtasks, then render, then mousemove, microtasks, render, then script on the bottom). Wouldn't that be more consistent? Also, wouldn't there be microtasks and render following "script", like with the other macrotasks?

**Comment by paroche** [comment]
But I truly don't understand why you would now have the macrotasks running from top to bottom. This illustration looks like, and is introduced ("The richer event loop picture looks like this") like, it was supposed to be an expansion of the first illustration in the "Event Loop" section:
![Screenshot (22)](https://user-images.githubusercontent.com/46547072/74500202-74891c80-4ea3-11ea-9868-574850e1fb5a.png)
![Screenshot (21)](https://user-images.githubusercontent.com/46547072/74500155-4efc1300-4ea3-11ea-8187-59e8ab332d9b.png)
,which I think could be successfully and straightforwardly accomplished, while remaining consistent with the text, by just, in the illustration directly above, putting the microtasks above the renders (and, for completeness and consistency, putting microtasks, then render underneath "setTimeout" before the loop back to the top).

**Comment by iliakan** [comment]
Did it =)

**Comment by paroche** [comment]
But it still has the renders before the microtasks in the diagram. That's the main think I think needed to be changed.

**Comment by iliakan** [comment]
It's like this now:
![image](https://user-images.githubusercontent.com/349336/74558926-16b80b80-4f5b-11ea-9d79-d5b062f96cae.png)

**Comment by paroche** [comment]
That looks good to me, though I don't see it on the article page (even after refreshing).

**Comment by iliakan** [comment]
clear cache? (refreshed server cache)

**Comment by paroche** [comment]
I did ^ctrl refresh and now it shows right.
