### ISSUE TITLE
Translating Javascript.info to Azerbaijani language

### ISSUE THREAD

**Issue by GasimGasimzada** [javascript-tutorial/en.javascript.info#1749]
We would like to translate this post to Azerbaijani language.

Language Code: **az**
Maintainers:

- @GasimGasimzada
- @azizaismayilova
- @Hadiyev

**Comment by iliakan** [comment]
There exists a translation already, added you as maintainers. 
Please see what's already done there.

https://github.com/javascript-tutorial/az.javascript.info
