### ISSUE TITLE
Sort order of local-/sessionStorage

### ISSUE THREAD

**Issue by a26z** [javascript-tutorial/en.javascript.info#1758]
Great article, very detailed description and quite clearly explained, thank you for publishing this information. There is, though, a passage that may lead to a misunderstanding: 

"LocalStorage, sessionStorage ... As you can see, it’s like a Map collection (setItem/getItem/removeItem), but also **keeps elements order** and allows to access by index with key(index)."

This is in a very restrictive way the case, as whatwg.org describes:

"**The order of keys is user-agent defined**, but must be consistent within an object so long as the number of keys doesn't change. (Thus, adding or removing a key may change the order of the keys, but merely changing the value of an existing key must not.)"

(https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface)

Cheers and thanks again for all the valuable information your site provides!!

**Comment by iliakan** [comment]
Thank you very much for the point.

Could you please name a browser that **doesn't keep elements order**?

**Comment by a26z** [comment]
Iliakan, I noticed the browser's own sorting of entries using  **Firefox 73.0 (64-bit), Firefox 74.0b4 (64-bit) and  Google Chrome 80.0.3987.106 (Official Build) (64-bit)**. 

My scenario (using the console) is as follows:

- Set 5 Items in the following order:

sessionStorage.setItem("A", "Anna");
sessionStorage.setItem("B", "Boris");
sessionStorage.setItem("C", "Claudia");
sessionStorage.setItem("D", "Dan");
sessionStorage.setItem("E", "Emilia");

- Show the storage:

sessionStorage;

Storage { C: "Claudia", E: "Emily", D: "Dan", B: "Boris", A: "Anna", length: 5 } (This using **FF 73** same result in **FF 74.0b4**)

Storage {A: "Anna", C: "Claudia", D: "Dan", B: "Boris", E: "Emily", …} (This using **Chrome 80**)

If the entry order is important, this internal browser-sorting will create trouble accessing the items by their keys. Running FF you access on key on key 1 "E" (Emily), using Chrome "C" (Claudia). But according to my initial entry order, on key 1 there should be "B" (Boris). 

Cheers,

Christian.

**Comment by iliakan** [comment]
Thank you! Removed the note about the order being kept.
