### ISSUE TITLE
Dynamic imports: suggest how to use in a project

### ISSUE THREAD

**Issue by asherccohen** [javascript-tutorial/en.javascript.info#1762]
I understand the concept of dynamic imports but I'm finding it hard to use them in a project since top-level await is not supported.
Any suggestion how to enable it?I tried with a Babel plugin with no luck.
Also adding this reference on your website would be nice to have.
Tx.

**Comment by iliakan** [comment]
that's for runtime imports, e.g. depending on a condition

if (something) import('modal.js')
