### ISSUE TITLE
Request to add me as a moderator on Disqus

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1763]
Hello.

Could you add me as a moderator on Disqus of Korean site?

When I add a link to relate a comment and issue on the repository, the system automatically detect my comment as spam.

**Comment by iliakan** [comment]
Sure, where was that disqus? ;) It's an exclusively Korean feature.

**Comment by iliakan** [comment]
What is your Disqus username?

![image](https://user-images.githubusercontent.com/349336/74926474-da0e6900-53cd-11ea-8715-26c7f24a4cb8.png)

**Comment by Violet-Bora-Lee** [comment]
@violetboralee is my username.

https://disqus.com/by/violetboralee/

**Comment by iliakan** [comment]
Done
