### ISSUE TITLE
Nested comments possible

### ISSUE THREAD

**Issue by Ifycode** [javascript-tutorial/en.javascript.info#1764]
Awesome javascript tutorial. About nested comments though, the tutorial says it's not possible. It's possible to have nested comments. I use it a lot.
By adding a backslash (\) in between the (*) symbol and the (/) symbol in this manner:

/* 
/* nested comment *\/ 
*/

More:

/* 
/* nested comment 1 *\/ 
/* nested comment  2*\/ 
*/

Written on different lines for easy reading 😊
See image/screenshot in the comments below incase backlash doesn't show.

**Comment by Ifycode** [comment]
![IMG_20200220_023538_685](https://user-images.githubusercontent.com/45185388/74892407-cb05c780-5389-11ea-96ce-41c2c982df01.jpg)

**Comment by Ifycode** [comment]
For some reason Github doesn't show backslash. So i had to upload a photo of my comment on javascript.info site.

**Comment by iliakan** [comment]
Yeah, but that's not quite it =)

**Comment by Ifycode** [comment]
OK... I would like to know what is though...
