### ISSUE TITLE
Exercise phrasing points to index, not value

### ISSUE THREAD

**Issue by PrettyFloralBonnet** [javascript-tutorial/en.javascript.info#1769]
In https://javascript.info/array-methods#filter-range, I would suggest saying "...looks for elements with values higher or equal to a and lower or equal to b" rather than the current "...looks for elements between a and b".

Right now it sounds like "between" is referring to indices. The solution I wrote initially looked like this:

```
let filterRange = (arr, a, b) => {
    if (b > arr.length) return arr.slice(a);
    else return arr.slice(a, b);
};
```

**Comment by iliakan** [comment]
Make a PR please?

**Comment by dorelljames** [comment]
@iliakan I created a pull request #2194 for this very old issue. Thanks

**Comment by iliakan** [comment]
Thanks =)

**Comment by PrettyFloralBonnet** [comment]
Thank you. Sorry for not coming through with the PR back then, I was meaning to but never got around to it.

**Comment by dorelljames** [comment]
I'm sorry if I took it to myself @PrettyFloralBonnet. Thank you for understanding.

**Comment by PrettyFloralBonnet** [comment]
No worries @dorelljames , I'm grateful you picked it up ;)
