### ISSUE TITLE
Why are you not clear about EcmaScript version of the code in the documentation?

### ISSUE THREAD

**Issue by mgrechanik** [javascript-tutorial/en.javascript.info#1772]
When you describe some feature it would be useful to say from which EcmaScript version it starts to work.
It is a bit confusing to read about ```let``` and ```const``` and only after find out that they work only from ES6.
Say I want to write some code with Vuejs. It does not use ```let``` or ```const``` then it is for ES5.
Now I read all of other documentation and do not know whether I can use those features to make my code ES5 compatible. 
Do you add changes from the latest ES-s into this tutorial also?

**Comment by iliakan** [comment]
The tutorial uses latest/supported ES. With some of the latest/unsupported stuff (notes are provided).

There's no point to label ES versions now, as we have yearly releases. Numbers do not matter. Browser support does.
