### ISSUE TITLE
Translation to Dutch

### ISSUE THREAD

**Issue by ChiefChingu** [javascript-tutorial/en.javascript.info#1773]
Hi,

I am interested in translating into Dutch (nl).
I guess I will be the maintainer, since there is none yet (or at least not visible to me).

I have a basic understanding of JavaScript and am learning. That is how I stumbled upon your resources. I think that I can increase my learning speed and quality by translating the material into Dutch.

Let me know what you think!

My nick: ChiefChingu.
My email address: sangho.grolleman@gmail.com

Regards,
Sangho

**Comment by iliakan** [comment]
Repo created, invitation sent.
