### ISSUE TITLE
wrong usage of backticks?

### ISSUE THREAD

**Issue by paseaf** [javascript-tutorial/en.javascript.info#1778]
In the solution to this task: https://javascript.info/coding-style#bad-style
The following code
``` javascript
 // below - long lines can be split into multiple lines for improved readability
 alert(`Power ${n} is not supported, please enter an integer number greater than zero`);
```
has been improved to 
``` javascript
  alert(`Power ${n} is not supported,
    please enter an integer number greater than zero`);
```
But they are not equivalent since backticks also record whitespace characters.
An equivalent could be 
``` javascript
  alert(`Power ${n} is not supported, ` + 
   `please enter an integer number greater than zero`);
```
or
``` javascript
  alert(oneLine `Power ${n} is not supported, 
    please enter an integer number greater than zero`);
```
in which `oneLine` is a tag function which could remove the unneeded whitespace.

**Comment by iliakan** [comment]
not equivalent for `alert` indeed. But splitting like this will cause questions, usually backticks allow to just break the line...

**Comment by paseaf** [comment]
True. Wish I could have a better example.
