### ISSUE TITLE
13-modules, 01-modules-intro note about CORS policy and file:// protocol

### ISSUE THREAD

**Issue by benjaminpreiss** [javascript-tutorial/en.javascript.info#1786]
hey,

I just bumped into an error yesterday which was due to CORS policy and said:

> "Cross origin requests are only supported for HTTP."

So i just found out that you can only use import/export when you have a webserver serving the site which I find a very useful information.

Thats why I would like to suggest a note about that in `02-import-export`

**Comment by iliakan** [comment]
Indeed. Please make a PR about it?

**Comment by benjaminpreiss** [comment]
yes, happily!
