### ISSUE TITLE
1-js/11-async/01-callbacks statement about asynchronicity 

### ISSUE THREAD

**Issue by Etheraex** [javascript-tutorial/en.javascript.info#1801]
`Many actions in JavaScript are asynchronous.`

This is a newbie question, but is this actually true? Is Anything in JS itself asynchronous or are the runtimes (browsers/ node.js) the ones that provide you with the ability to make parts of your code execute asynchronously?

**Comment by iliakan** [comment]
The phrase should be changed. Not in JavaScript itself.

**Comment by iliakan** [comment]
Any idea how to adjust it?

**Comment by Etheraex** [comment]
I'm not quite sure, perhaps something like this:

`
Many functions are provided by JavaScript host environments that allow you to schedule asynchronous actions. In other words, actions that we initiate now, but they finish later.`

` For instance, one such function is the setTimeout function.`

**Comment by iliakan** [comment]
Smth along these lines, yeah. Make a PR?

**Comment by Etheraex** [comment]
Done.
