### ISSUE TITLE
Constructor function prototype property can continue to affect instances

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1803]
I don't remember if or how I may have addressed this before, but I still find the paragraph below, from the "F.prototype" article, misleading (**emphasis** added):

<i>F.prototype only used at new F time
F.prototype property is only used when new F is called, it assigns [[Prototype]] of the new object. **After that, there’s no connection between F.prototype and the new object.** Think of it as a “one-time gift”.

If, after the creation, F.prototype property changes (F.prototype = <another object>), then new objects created by new F will have another object as [[Prototype]], but already existing objects keep the old one.</i>

But is it not the case that when new F is called a pointer is passed to the new instance that points to the current F.prototype object, and if that object is changed (rather than replaced by another object) it **will** still affect the previously created instances? 

For instance:
```
var Person = function(name, yearOfBirth, job) { 
    this.name = name;
    this.yearOfBirth = yearOfBirth;
    this.job = job;
}

Person.prototype.calculateAge = function() {
    console.log(2020 - this.yearOfBirth);
};

let john = new Person('John', 1990, 'teacher');

john.calculateAge(); // 30

Person.prototype.calculateAge = function() {
    console.log("Person.prototype has changed");
}

john.calculateAge(); // "Person.prototype has changed"
```

**Comment by iliakan** [comment]
Removed this phrase. Nope it's cleaner now =)

**Comment by paroche** [comment]
It is, though I would still say that the phrase "_F.prototype property is only used when new F is called,_" could cause confusion, in that the prototype object that was pointed to by `F.prototype` at the time of the creation of a new object `newObj` by `F` is used by `newObj`, and if at a later time  `F.prototype` still points to that object, and the contents of the object are changed by an assignment to `F.prototype.somepropertyormethod` (as shown above), they will also be changed for `newObj` (as shown above). So in that sense it would appear that the `F.prototype property` is still used by `newObj`

**Comment by iliakan** [comment]
Yes, I got it.

**Comment by paroche** [comment]
BTW, good to see you're still kicking around in these strange times.

**Comment by iliakan** [comment]
Staying out of the city, otherwise all is fine =)

**Comment by iliakan** [comment]
How's at your place?

**Comment by paroche** [comment]
Not too bad in terms of numbers -- 35 confirmed cases in the state of New Mexico, (population over 2 million) last I heard, probably a few more by now. Only 3-5 or so in Santa Fe county (population of maybe 100,000). But not nearly enough testing, so who knows. Meanwhile, hoarding and shortages, most things closed and cancelled. Very unusual. Situation changes by the day.

**Comment by paroche** [comment]
Like to get my facts straight: looks like SF County population more like 150,000+. We'll know much better after the 2020 census.
