### ISSUE TITLE
api.github requests failing, or were. May be a temporary situation

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1811]
As of today am noticing that api.github is rejecting requests with messages like:

`Access to fetch at 'https://api.github.com/users/iliakan' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

The above was triggered by running the sample code used in one of the Promise API (https://javascript.info/promise-api) examples:
 <pre><code>
<!DOCTYPE html>
<script>
'use strict';

let urls = [
  'https://api.github.com/users/iliakan',
  'https://api.github.com/users/remy',
  'https://api.github.com/users/jeresig'
];

// map every url to the promise of the fetch
let requests = urls.map(url => fetch(url));

// Promise.all waits until all jobs are resolved
Promise.all(requests)
  .then(responses => responses.forEach(
    response => alert(`${response.url}: ${response.status}`)
  ));
</script>
</code></pre>

But it seems to be across the board. For instance, also got:

`Access to fetch at 'https://api.github.com/repos/javascript-tutorial/en.javascript.info/commits' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Don't know if this is a temporary or permanent condition.

Update:
As of an hour later of so, not getting same error, though it's still failing on some requests, so maybe is just a glitch or sign-of-the-times network problem. 

Update 2:
As of a few hours later, intermittent failures in fetching from api.github. So, strengthens the 'network problem' theory.

**Comment by iliakan** [comment]
Just check, no such messages, everything works ok for me.

Please reopen if the examples do not work correctly.

**Comment by paroche** [comment]
Still fails here. Same example now gives:

`Access to fetch at 'https://api.github.com/users/iliakan' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
JavaScriptInfo async demo requests 1.html:1 Uncaught (in promise) TypeError: Failed to fetch
JavaScriptInfo async demo requests 1.html:1 Access to fetch at 'https://api.github.com/users/jeresig' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
JavaScriptInfo async demo requests 1.html:1 Access to fetch at 'https://api.github.com/users/remy' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Also, I have my own script to check commits to your site, which has always worked before, but which now (today) fails, to varying degrees at different times, which is how I noticed this situation in the first place. Then I checked the examples in the article, figuring they would probably have the same kind of problem (partly wanting to make sure it wasn't just me :-), and saw that they did.

**Comment by iliakan** [comment]
That's the output of curl for me (with all headers):

```
/js/en.javascript.info master> curl -vvv https://api.github.com/users/iliakan
*   Trying 140.82.118.5:443...
* TCP_NODELAY set
* Connected to api.github.com (140.82.118.5) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
*  start date: Jul  8 00:00:00 2019 GMT
*  expire date: Jul 16 12:00:00 2020 GMT
*  subjectAltName: host "api.github.com" matched cert's "*.github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> GET /users/iliakan HTTP/1.1
> Host: api.github.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 24 Mar 2020 03:27:46 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 1284
< Server: GitHub.com
< Status: 200 OK
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 49
< X-RateLimit-Reset: 1585021810
< Cache-Control: public, max-age=60, s-maxage=60
< Vary: Accept
< ETag: "bec9374c529cf0720fee0594222dd505"
< Last-Modified: Tue, 24 Mar 2020 01:53:41 GMT
< X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
< Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Content-Security-Policy: default-src 'none'
< Vary: Accept-Encoding, Accept, X-Requested-With
< X-GitHub-Request-Id: C84A:452B7:129C3D:15480B:5E797E32
<
{
  "login": "iliakan",
  "id": 349336,
  "node_id": "MDQ6VXNlcjM0OTMzNg==",
  "avatar_url": "https://avatars0.githubusercontent.com/u/349336?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/iliakan",
  "html_url": "https://github.com/iliakan",
  "followers_url": "https://api.github.com/users/iliakan/followers",
  "following_url": "https://api.github.com/users/iliakan/following{/other_user}",
  "gists_url": "https://api.github.com/users/iliakan/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/iliakan/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/iliakan/subscriptions",
  "organizations_url": "https://api.github.com/users/iliakan/orgs",
  "repos_url": "https://api.github.com/users/iliakan/repos",
  "events_url": "https://api.github.com/users/iliakan/events{/privacy}",
  "received_events_url": "https://api.github.com/users/iliakan/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ilya Kantor",
  "company": null,
  "blog": "https://javascript.info",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 112,
  "public_gists": 724,
  "followers": 2393,
  "following": 0,
  "created_at": "2010-07-30T14:31:35Z",
  "updated_at": "2020-03-24T01:53:41Z"
}
* Connection #0 to host api.github.com left intact
```

**Comment by paroche** [comment]
Oh, well in that case....

**Comment by paroche** [comment]
Problem above not happening like it was, but it does seem like Github is now limiting requests from a given IP more than they were a few months ago.
