### ISSUE TITLE
Auto deploy failed now, and the date on the website has not updated for many days

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/en.javascript.info#1813]
RT. Thanks!

<img width="780" alt="Screen Shot 2020-03-24 at 1 27 44 PM" src="https://user-images.githubusercontent.com/26959437/77391321-706dea00-6dd3-11ea-812f-3d2415bd9033.png">

**Comment by iliakan** [comment]
Fixed it. Let me know if such thing happens again, please.

**Comment by leviding** [comment]
No problem! Thanks again!
