### ISSUE TITLE
Thought I couldn't find article to edit for 1st task of https://javascript.info/object-methods. But never mind. Don't see how to delete this, so...

### ISSUE THREAD

**Issue by paroche** [javascript-tutorial/en.javascript.info#1835]
Never mind -- I see now that it's there as task 2. I imagine there used to be another task before it, maybe.

**Comment by iliakan** [comment]
Here in the tutorial, I try to use "brackets" for `[]` and "parentheses" for `()`, curly braces for `{}`.

A diversion from these rules should probably be fixed.

Does that sound ok?

**Comment by paroche** [comment]
Yep. That's what I thought, that's the way I think it should be, and that's what I implemented in my two commits following this. All is well.
On Tuesday, March 31, 2020 Ilya Kantor <reply@reply.github.com> wrote:



Here in the tutorial, I try to use "brackets" for [] and "parentheses" for (), curly braces for {}.

A diversion from these rules should probably be fixed.

Does that sound ok?
