### ISSUE TITLE
wrong explanation on how lookaheads work

### ISSUE THREAD

**Issue by Ieahleen** [javascript-tutorial/en.javascript.info#1836]
there has been this change to the explanation on lookaheads:

![image](https://user-images.githubusercontent.com/26656284/78038150-c828ca00-736c-11ea-9b2e-14c8eaefdf51.png)
[change log here](https://github.com/javascript-tutorial/en.javascript.info/commit/6dbd3060e1e81023730b5a8fd3951211a7d68204)

but this make the page [Lookahead and lookbehind](https://javascript.info/regexp-lookahead-lookbehind) wrong.

if what's written there is true, this test method should return true:
``` javascript
const str = "ab0";
const re = /a(?=b)(?=0)/;
re.test(str); // this returns false
```
lookaheads and lookbehinds are zero width characters, they do not advance position that is being matched.

this change should be reverted, it was correct saying

> More complex tests are possible, e.g. X(?=Y)(?=Z) means:
> 
> Find X.
> Check if Y is immediately after X (skip if isn’t).
> Check if Z is immediately after X (skip if isn’t).
> If both tests passed, then it’s the match.

reference:
https://www.regular-expressions.info/lookaround.html

thank you

**Comment by iliakan** [comment]
Thanks for the catch!
