### ISSUE TITLE
What does "bound" do in "this.click = this.click.bound(this)" ? (Lesson: Classes, class basic syntax)

### ISSUE THREAD

**Issue by JasmineCAicai** [javascript-tutorial/en.javascript.info#1843]
In the last part **Class fields**, what does "bound" mean in the second parts of code of "Making bound methods with class fields"? 

class Button {
  constructor(value) {
    this.value = value;
    this.click = this.click.bound(this);
  }
}

**Comment by iliakan** [comment]
I updated the article with more details. Better now?

**Comment by JasmineCAicai** [comment]
yeah! thanks
