### ISSUE TITLE
Gender neutrality in examples

### ISSUE THREAD

**Issue by augustodg2** [javascript-tutorial/en.javascript.info#1848]
I noticed that in some articles, there are gender-specific examples. For instance, in the [Garbage Collection article](https://javascript.info/garbage-collection): 

![image](https://user-images.githubusercontent.com/55559552/78553887-71921480-77e0-11ea-8f4b-782e48383f72.png)

It implies that marriage only occurs between a man and a woman. A better and more inclusive approach to that would be:

```javascript
function marry(person1, person2) {
  person1.partner = person2;
  person2.partner = person1;

  return {
    parent1: person1,
    parent2: person2
  }
}

let family = marry({
  name: "John"
}, {
  name: "Ann"
});

// But it is also fine for
let anotherFamily = marry({ name: 'Ann' }, { name: 'Jane' })
```

**Comment by ayylmar** [comment]
This looks like a troll to me.

`person1`, `person2`, `parent1` and `parent2` are also very bad, undescriptive variable names. Having such variable names with sequential numbers means you'd be better off with an array.  
Changing this accross all the languages for consistency's sake would be a colossal waste of time for **absolutely** no benefit.

You also have to take into account that this is a resource for learning, not for indoctrination.

**Comment by iliakan** [comment]
Why are you against different-sex marriages?
