### ISSUE TITLE
Please create a release when a new article is released!

### ISSUE THREAD

**Issue by mesqueeb** [javascript-tutorial/en.javascript.info#1849]
I'm following releases only of this repository.
It would be great if a new release could be created every time a new article is added!
🎉

**Comment by iliakan** [comment]
You can just follow master branch =)

**Comment by iliakan** [comment]
No need to introduce a "release" machinery here =)

**Comment by mesqueeb** [comment]
@iliakan thanks for your comment.
The thing is, following master branch will give me notifications on every small change & minor fix & merge. It also doesn't seem like you squat features merged into master.

I think a notification on just the "releases" with a link to the new article would be very user friendly!

Keep up the good work!!
