### ISSUE TITLE
Translating to my language 

### ISSUE THREAD

**Issue by prajwal467** [javascript-tutorial/en.javascript.info#1854]
Hello. This is my language. Dravidian | Kannada | ಕನ್ನಡ | kn. I am from Bangalore,which is part of Karnataka. As every one knows Bangalore is a IT hub many people want to come to Bangalore for job, but due communication problem in English they would find it hard to get a job. So i am requesting for a translation to my language Kannada, so that many people can access it.

**Comment by iliakan** [comment]
Still interested?
