### ISSUE TITLE
Issue in: Code quality > Automated testing with Mocha > beforeafter.view > test.js

### ISSUE THREAD

**Issue by tmollov** [javascript-tutorial/en.javascript.info#1866]
Hi, people

Here in "Automated testing with Mocha":

https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/03-code-quality/05-testing-mocha/beforeafter.view

opened html locally causes error:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

this is because default timeout for tests in mocha is 2000ms
and if user doesn't respond to the alert box in time, all tests fails:
some time just in before hook, sometimes in beforeEach and so on.
I will add this.timeout(200000) to bulgarian translations to prevent it.
Like this:
describe("test", function () {
  this.timeout(200000); 
.... 
});

**Comment by iliakan** [comment]
Send a PR here?

**Comment by iliakan** [comment]
Thanks, merged!
