### ISSUE TITLE
I can’t understand the last task of string

### ISSUE THREAD

**Issue by shivarad** [javascript-tutorial/en.javascript.info#1867]
Hello
I can’t understand the usage of “+” in the return phrase of the last task of string:
Return +str.slice(1);

**Comment by zmarconato** [comment]
The function in question is:
```
function extractCurrencyValue(str) {
  return +str.slice(1);
}
```
Say you input it the string "$140", here is what happens:
- Firstly, str.slice(1) evaluates to the _string_ '140'
- Then +'140' converts it to the _number_ 140

It's all about the **unary + operator**.

Please refer to the following sections in these articles:
- https://javascript.info/operators#numeric-conversion-unary
- https://javascript.info/type-conversions#numeric-conversion
