### ISSUE TITLE
EPUB display issue: Dark mode in Apple Books breaks syntax highlighting

### ISSUE THREAD

**Issue by bobobox** [javascript-tutorial/en.javascript.info#1869]
Hi - I purchased the EPUB version of the three books, and am reading them in the Books app on my iOS devices and Mac. The documents look fine in light mode, but in dark mode, the syntax highlighting in the code sections is lost, except for the 'highlighted lines', which show up as a confusing series of lines:

![BEADB2BA-1E37-4F54-8335-4780CC03FF9D_1_105_c](https://user-images.githubusercontent.com/2499321/80121415-e50e8280-8551-11ea-85f7-7bdcc2ed83fe.jpeg)

Is this something that can be addressed? Dark mode is very helpful on the eyes when reading on an iPad.

**Comment by iliakan** [comment]
Hi,

Sorry for that, but EPUB isn't very compatible format. Not all readers work the same. 

Try Calibre or iBooks please.
---
Best Regards,
Ilya Kantor
https://javascript.info
