### ISSUE TITLE
Code block are not displayed in EPUB format

### ISSUE THREAD

**Issue by antoine1000** [javascript-tutorial/en.javascript.info#1871]
Hi,

First, thanks for these wonderful ressources! 

I purchased these books a while ago and downloaded it again today in order to get the last versions. 

PDFs versions are fine, but when I opened the EPUB books (with the Books app on MacOS), all blocks code completely disappeared from the book. See screenshot (here, `ui.epub`):

<img width="1069" alt="No block codes on EPUB" src="https://user-images.githubusercontent.com/18557215/80253382-77f60c80-8679-11ea-9167-495117eae8e8.png">

Do you have an idea why it happens?
Thanks!

**Comment by iliakan** [comment]
That's odd indeed! iBooks work just fine.

Please send me the exact file you're viewing at iliakan@javascript.info.
Also what's your MacOS version? Is it the latest Catalina or not? I'm on Mojave.

**Comment by antoine1000** [comment]
I just sent you en email with the file!

I'm using macOS Catalina (10.5.4) and iBooks 2.4 (1923).

**Comment by iliakan** [comment]
I don't see other similar reports. For me it looks ok:

![image](https://user-images.githubusercontent.com/349336/80275161-1faa2380-86e8-11ea-8177-db32db753e79.png)

Do you have any plugins? I can't reproduce the problem.

**Comment by antoine1000** [comment]
Hmm, I don't have any plugins on iBooks as far as I know...

I just tried to open the EPUB with Calibre, block codes appeared. I guess the issue does not concern the EPUB file itself but my iBooks version.

_Note : other books that contains code blocks show them properly._

**Comment by iliakan** [comment]
I remember there was a way to see the DOM in iBooks (epub is html-based). Then one could check the styles to see why the code does not show up.

But I can't debug this in my iBooks, because everything works well for me.

If that's a problem for you, I can make a refund.

**Comment by antoine1000** [comment]
I converted the EPUB file to MOBI and imported it into a Kindle device. The code blocks are properly displayed. So the issue is definitely not about the file... 
Maybe other Catalina users should try to open the EPUB too to see if the issue come from iBook.

Thanks for the refund proposal but I will manage to read it anyway! I want to support the project whatsoever so don't bother.

**Comment by iliakan** [comment]
Thanks. The report that you provided is unique, other Catalina users don't have such problem, it seems.

**Comment by iliakan** [comment]
This rare issue appears to be fixed now.

**Comment by antoine1000** [comment]
Indeed, working like a charm! Thanks a lot!

**Comment by iliakan** [comment]
Sorry it take too long, we tried hard to reproduce the problem, but finally managed to do it.
