### ISSUE TITLE
needs explanation on the example about dynamic script

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1872]
Hi, Ilya and the Team! How's the COVID situation there? I hope all the members are fine.

I'm reviewing the translated article of https://javascript.info/script-async-defer.

All other examples have an explanation of what it demonstrating but this example has no explanation.

![image](https://user-images.githubusercontent.com/6451384/80273142-bc7db880-870a-11ea-9420-85f84aadabe8.png)

Could you add?

**Comment by Violet-Bora-Lee** [comment]
Btw, I wonder the differences between loading and downloading the script in the article.

I think the two words have the same meaning but I want to verify.

**Comment by iliakan** [comment]
Hi, I'm ok so far, but our team member (admin) living in Czech got Covid.  Quite a nasty thing he says. So take care.

Yes, loading/downloading is the same. 
Could you suggest a PR please?

**Comment by Violet-Bora-Lee** [comment]
I'm not sure why you explicitly assign false on script.async.

I hope Alexey will be recovered soon!

**Comment by iliakan** [comment]
Yeah, was unclear for me too some time ago.

By default, scripts added via DOM methods behave as if they had `async=true`.

That is, they execute in "first loaded - first run" order.

But if there's an explicit `script.async = false`, then they execute in page order.  If you create two scripts and append them to `document.body`, then the first that you add always runs first. Even if the second one is fully loaded, it waits.

**Comment by iliakan** [comment]
I remember this was fixed?
