### ISSUE TITLE
[WANTED ARTICLE] TreeWalker and NodeIterator

### ISSUE THREAD

**Issue by MathiasWP** [javascript-tutorial/en.javascript.info#1892]
I recently found about the TreeWalker (https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker) and NodeIterator (https://developer.mozilla.org/en-US/docs/Web/API/NodeIterator) API's. Is this something you could write an article or two about? These seem like very interesting features.

**Comment by iliakan** [comment]
They exist for quite some time, but very rarely used (never seen in real code actually)

**Comment by MathiasWP** [comment]
By why's that? They seem pretty useful, even though not many people use them anymore.

**Comment by iliakan** [comment]
Isn't it a paradox?

They *seem* useful to you. But no one uses them.

Someone must be mistaken =)

**Comment by MathiasWP** [comment]
Lol at least you're not bitter 😂

Many people not using it doesn't always equal **not useful in any way**. Recently had a case where this exact API was basically what i needed, so i tried it out. It's a pretty cool API, but modern stuff about performance and edge-cases are hard to find good docs on. I may be mistaking about all this, but there are definitely some use cases to an API like this. It just basically boils down to performance, and if this API is even worth using, or if it is better to create a recursive DOM-searcher that pushes everything to an array with modern JS.
