### ISSUE TITLE
Is the word "to" superfuous in this sentence?

### ISSUE THREAD

**Issue by Li-YangZhong** [javascript-tutorial/en.javascript.info#1918]
The second to last sentence in page located at https://javascript.info/optional-chaining is written as below:

"Still, we should apply ?. carefully, only where it’s ok that the left part doesn’t to exist."

I figured the word "to" in the sentence above should be removed. Please correct me if I am wrong. Thanks.

**Comment by iliakan** [comment]
Send a PR?

**Comment by Li-YangZhong** [comment]
Sorry, I am still new to this Github pull and submitting issue, etc.... I will check out how to best collaborate via GitHub soon.
