### ISSUE TITLE
add difference between Object.getOwnPropertyNames and Object.keys

### ISSUE THREAD

**Issue by kiniggit** [javascript-tutorial/en.javascript.info#1923]
For instance, in the article  "Object properties configuration" or "Object.keys, values, entries" we could find a section talking about the difference between Object.getOwnPropertyNames and Object.keys. 

This section could be easily skipped by some beginners that would come back later to better understand it.

What do you think about it? I would gladly write some of it.

**Comment by iliakan** [comment]
In the summary of [Prototypes](https://javascript.info/prototype-methods#summary):

![image](https://user-images.githubusercontent.com/349336/82740296-2dd37a00-9d50-11ea-8cf6-98800e393203.png)

The difference is very small =)

**Comment by kiniggit** [comment]
Nice! Thanks!
