### ISSUE TITLE
Old versions repos in other languages to translate.  Mr BOT is smart. Can it be smater?  

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/en.javascript.info#1924]
A year ago I asked maintainers to sync EN ES versions.  No luck,  Untranslated part is still 4 years old, so traslators use EN as base,

problems: 
*new translators surely miss the recomentation,
*review shows diff on ES repo, so I suppose the review (I never did) is more complicated.

Can the bot check the version when an article is claimed? then warn the user AND the maintainers?
or
Is there an easy way to selectively sync the NON claimed articles?
thanks you!

**Comment by iliakan** [comment]
The bot labels claimed articles automatically, when someone posts its title in the progress issue.

**Comment by iliakan** [comment]
What's necessary is a stable maintainer who manages the translation and syncs when needed.

When there are many differences, then it might be easier to just read and compare articles, and then commit the newer version without any git merging involved.

**Comment by joaquinelio** [comment]
Ok...
1) The problems stand. For now.
*Oct 2019 I did the work twice, today I know better.  Bue there's no warn for new translators.
*Easier Reviews?  

2) We just got a new maintainer Apr2020, still waiting, hope he catches up with the goals soon. I bet.  

Bytheway, great job.  Love the site and the commitment.

**Comment by iliakan** [comment]
I can help, explain and advise, but if a Spanish translation is to exist, it should be maintained by Spanish-speaking people.

**Comment by joaquinelio** [comment]
Got it!
I agree, I was just wondering if there is a easy tunnig to the procedure, like the good boy bot.

"Stable maintainer" is the real answer.  That's right.

**Comment by joaquinelio** [comment]
ha ha 
it JUST happened again, new transl 
maksumi just worked on a 2 y old document, and he is now translating it again.

perhaps
 bot, after label, "pls check date against EN version" ? 
Either way, I dont know how to do the REVIEW then.

So this issue is closed but left yesterdays one on ES open.
It is our issue
Thanks

**Comment by iliakan** [comment]
Are you familiar with git? Can pull from upstream, there are instructions at the top of the issue.

**Comment by joaquinelio** [comment]
I screwed my first fork in tranlation. Im still.... scr... learning. 

I dont get.
reviews should be easy online:  open the diff, then just follow the diff colors .

my local upstream is the old /es. 
the pull for the upstream of my upstream can only be done by Mr Stable Maintainer,

I do pull from it to my local to do translation, but it's not worth for every branch to review, 
So it looks like then easiest way is still online, with 2 browser windows (/en and PR)  trying to keep them aligned. Not so hard, but avoidable,  without Mr Stable Maintainer wouldnt be merges at all, anyway.  So the solution must still be from our side.
