### ISSUE TITLE
Explicitly introduce statement vs expression

### ISSUE THREAD

**Issue by icncsx** [javascript-tutorial/en.javascript.info#1937]
The two words, statement and expression, are sprinkled throughout the site, but I don't think we explicitly introduce their meaning.

A simple way to explain their difference:

- Expression is like a noun. It produces the value or is a value itself.
- Statement is like a verb. It performs an action.

What do you think?

**Comment by iliakan** [comment]
Please see https://en.wikipedia.org/wiki/Statement_(computer_science)#Expressions =)
