### ISSUE TITLE
Suggestion: Explicitly include "use strict"; in function declaration examples

### ISSUE THREAD

**Issue by icncsx** [javascript-tutorial/en.javascript.info#1938]
In the function expressions  [lesson](https://javascript.info/function-expressions), we mention: 

`In strict mode, when a Function Declaration is within a code block, it’s visible everywhere inside that block. But not outside of it.`

Then we proceed to show an example of an error that occurs only if we're in strict mode. But the code block does not itself include "use strict";.

```js
"use strict";
let age = prompt("What is your age?", 18);
...
```

In the following example, we can also make the addition:

```js
"use strict";
let age = prompt("What is your age?", 18);
...
```

**Comment by iliakan** [comment]
Everywhere in the tutorial, unless explicitly stated, the code assumes `use strict`.
