### ISSUE TITLE
Suggestion: When talking about the constancy of "const", use the word "reassign" as opposed to "change"

### ISSUE THREAD

**Issue by icncsx** [javascript-tutorial/en.javascript.info#1939]
We use the word "change" 8 times in the [variables lesson](https://javascript.info/variables), which is frequent enough that it can confuse the reader into thinking that `const` denotes constancy in the absolute sense (no change). Unless the reader is already familiar with pass/copy by value vs. reference w/ Objects, I think the lesson should use the word "reassign" to drive the point that we cannot reassign when using `const` as opposed to saying that `const` means constant so no change.

@iliakan, I think you recently made a commit so that the article uses the word "reassign" twice, so this issue is just an extension of the change you already made. We can make the entire article much more consistent if we stick to "reassign" instead of change. 

Also, I acknowledge the fact that we talk about this topic more in the [array lesson](https://javascript.info/array), but the variables lesson precedes that.

**Comment by iliakan** [comment]
Might be fine, make a PR if you consider it worthy.

**Comment by icncsx** [comment]
Most of my issues are going to be nit-picky because the resource is pretty awesome. Thanks for starting this by the way. I never told you how much I appreciated this resource when I first discovered it :)

**Comment by iliakan** [comment]
Thanks, closing this for now then =)
