### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by otmon76** [javascript-tutorial/en.javascript.info#1943]
If nobody does it yet, I would like to start translation of the website to Czech language.

language code: cs
nick: Otmon76
email: onderek@volny.cz

**Comment by iliakan** [comment]
Still interested?

**Comment by otmon76** [comment]
Yes, I am.

**Comment by iliakan** [comment]
Great, repo is ready, invite sent!

**Comment by Micah-Shallom** [comment]
Yes I am

**Comment by iliakan** [comment]
@Micah-Shallom you'd like to join?
