### ISSUE TITLE
Oversimplified Documentation in Function Expressions

### ISSUE THREAD

**Issue by dsomel21** [javascript-tutorial/en.javascript.info#1951]
Can we try and be a bit more careful in [these examples](https://javascript.info/function-expressions)? 

It summarizes the following example as the following: 

```
function sayHi() {   // (1) create
  alert( "Hello" );
}

let func = sayHi;    // (2) copy

func(); // Hello     // (3) run the copy (it works)!
sayHi(); // Hello    //     this still works too (why wouldn't it)
```

> The Function Declaration (1) creates the function and puts it into the variable named sayHi.
> Line (2) copies it into the variable func.

I can see the point that is trying to be made here, but saying _Line (2) copies it into the variable func._ isn't an accurate description of what's happening. It's literally the same reference.

**Comment by iliakan** [comment]
It's called "copy by reference".

Explained later in more detail.
