### ISSUE TITLE
1-js/06-advanced-functions/01-recursion The execution context and stack

### ISSUE THREAD

**Issue by curlywater** [javascript-tutorial/en.javascript.info#1954]
Hey,

I'm just a bit confused about when the execution context is pushed onto the stack:

> When a function makes a nested call, the following happens:
> - The current function is paused.
> - The execution context associated with it is remembered in a special data structure called execution context stack.

This seems to mean the context is pushed to the stack when function is paused.

But the MDN record it like:
> When a script calls a function, the interpreter adds it to the call stack and then starts carrying 
 out the function.
Source: [https://developer.mozilla.org/en-US/docs/Glossary/Call_stack](https://developer.mozilla.org/en-US/docs/Glossary/Call_stack)

Did I misunderstand it?

**Comment by iliakan** [comment]
The tutorial is more correct here than MDN.

**Comment by iliakan** [comment]
At least, that's for sure:
- function isn't pushed.
- the context is pushed to the stack.

**Comment by curlywater** [comment]
> At least, that's for sure:
> 
> * function isn't pushed.
> * the context is pushed to the stack.

Exactly.

But when I search "javascript context call stack", there are lots of articles describe the context is pushed to the stack when function runs and  the context created. It's really weird.
