### ISSUE TITLE
Suggestion: Will there be any courses for React and Node.js (Paid or Free)

### ISSUE THREAD

**Issue by pritam2510** [javascript-tutorial/en.javascript.info#1960]
Hi,
Will there be any courses for React and Node.js in the near future?
We will be really grateful if there are courses for React and Node.js as well, even if those are paid courses.
Thanks

**Comment by iliakan** [comment]
Only if someone will take care of them, besides me =) 
It takes enough time to ensure the current JS scope is good and modern.
