### ISSUE TITLE
optional chaining

### ISSUE THREAD

**Issue by dagolinuxoid** [javascript-tutorial/en.javascript.info#1961]
> The optional chaining ?. is not an operator, but a special syntax construct, that also works with functions and square brackets.

But according to MDN it's an operator. 

> The optional chaining operator (?.) permits reading the value of a property located deep within a chain of connected objects without having to expressly validate that each reference in the chain is valid. The ?. operator functions similarly to the . chaining operator, except that instead of causing an error if a reference is nullish (null or undefined), the expression short-circuits with a return value of undefined. When used with function calls, it returns undefined if the given function does not exist.

Are there any JS spec evangelists who can claim precisely what the *thing* is ? =)

**Comment by iliakan** [comment]
Read the spec, ok? And tell us! I have my opinion, but mistakes are always possible.

**Comment by dagolinuxoid** [comment]
Folks at *tc39* refer to it as an operator as well.

> The Optional Chaining operator is spelled ?.

https://github.com/tc39/proposal-optional-chaining#syntax

**Comment by iliakan** [comment]
It's the proposal, not the spec.

**Comment by iliakan** [comment]
You know where to find the spec, right? ;)

**Comment by dagolinuxoid** [comment]
sure :)

This specification, the 11th edition, introduces adding two new syntax features to improve working with “nullish” values (null or undefined): nullish coalescing, a value selection operator; and optional chaining, a property access and function invocation operator that short-circuits if the value to access/invoke is nullish.

It's a bit confusing and I'm not 100% convinced but to me it seems like an operator ( now I'm regretting that I opened the issue and struggling with the spec rather than spending time to build react app ) 
btw. congrats upon reaching 10k stars!

**Comment by iliakan** [comment]
@dagolinuxoid maybe ask TC39 directly? In their issues or alike?

**Comment by iliakan** [comment]
@dagolinuxoid they might just answer and save our time =)

**Comment by iliakan** [comment]
Here: https://es.discourse.group/t/optional-chaining-the-syntax-or-the-operator/366

**Comment by dagolinuxoid** [comment]
You did the work for me. And I glad you did it. You asked right questions even though yet it turns out there is no 'strict right' answer to point that the `?.` either an operator or not.  Your term syntax is more general so I'm convinced it's appropriate to use, but probably the strong claiming that `?.` it's not an operator is a bit reckless I would say.

**Comment by iliakan** [comment]
We have the answer now, "syntax" seems better to the spec author. It also seems better to me, as operators have defining features, such as precedence, that are to be specified if it's an operator, but they are not.
