### ISSUE TITLE
[Focusing: focus/blur] Add focused class to e.target not form

### ISSUE THREAD

**Issue by kumiko-haraguchi** [javascript-tutorial/en.javascript.info#1965]
@iliakan First of all, thank you for your great work. This is helping us tremendously!

---
**Where**
2.Focusing: focus/blur [https://javascript.info/focus-blur](https://javascript.info/focus-blur)

---
**Problem**
As for the sample code of two ways to excuse event delegation, they don't seem to work as expected.

**Current behavior:**
![before](https://user-images.githubusercontent.com/28984604/85201521-1978a200-b33b-11ea-9146-4720b0ee8175.png)

---
**Suggestion**
I think you need to add focused class to `e.target` not form element.

```
// use capture
form.addEventListener("focus", (e) => e.target.classList.add('focused'), true);
form.addEventListener("blur", (e) => e.target.classList.remove('focused'), true);

// use focusin/focusout
form.addEventListener("focusin", (e) => e.target.classList.add('focused'));
form.addEventListener("focusout", (e) => e.target.classList.remove('focused'));
```
**After:**
![after](https://user-images.githubusercontent.com/28984604/85201524-1c739280-b33b-11ea-864b-80316274e6c5.png)

**Comment by joachimklug** [comment]
Hi @kumiko-haraguchi,

thanks for the detailed report. However the code is working as intended.

The article wants to show that **focus** and **blur** events don't bubble. To do so the target is to draw a border around the **form** when one of the input fields are on focus. (Not to draw a border on the input field itself) And the form around the box looks exactly like the the box in your first screenshot.

**Comment by kumiko-haraguchi** [comment]
@joachimklug I see, I totally mistook the intention of the section. Thank you for clarifying it :-) I'll close this issue!
