### ISSUE TITLE
Misspelling of re-targeted as retarteted in Pointer events page

### ISSUE THREAD

**Issue by Ravichandra-C** [javascript-tutorial/en.javascript.info#1966]
In [Pointer events](https://javascript.info/pointer-events) Page under [pointer capturing](https://javascript.info/pointer-events#pointer-capturing) section ,in the below part of the explanation 

> Pointer capturing provides an alternative solution: we can call thumb.setPointerCapture(event.pointerId) in pointerdown handler, and then all future pointer events until pointerup will be **retarteted** to thumb.

retargeted is misspelled as retarteted.

**Comment by iliakan** [comment]
Make a PR?

**Comment by iliakan** [comment]
Thank you!
