### ISSUE TITLE
Format errors in alerts.

### ISSUE THREAD

**Issue by vplentinax** [javascript-tutorial/en.javascript.info#1971]
Are including characters such as   ```   or   *" "*   that break the format of the rest of the document within the headers of the alerts. Example:

<a href="https://ibb.co/X3xQKHK"><img src="https://i.ibb.co/s69fN7N/Screenshot-from-2020-06-26-13-36-23.png" alt="Screenshot-from-2020-06-26-13-36-23" border="0"></a>

**Comment by iliakan** [comment]
Can't you check on the site?

**Comment by iliakan** [comment]
Should be all right..

**Comment by vplentinax** [comment]
On site appears to render correctly. I guess then it's not a problem.
