### ISSUE TITLE
Related to class fields

### ISSUE THREAD

**Issue by vivek1394Git** [javascript-tutorial/en.javascript.info#1979]
Hello there,
It is written in class field section(https://javascript.info/class):
"Technically, they are processed after the constructor has done it’s job, and we can use for them complex expressions and function calls:
`class User {
  name = prompt("Name, please?", "John");
}

let user = new User();
alert(user.name); // John`
"

I've checked it using this code.
`class User {
  name = prompt("Name, please?", "John");
  constructor() {
    alert("I was here later!");
  }
}

let user = new User();
alert(user.name); // John`

And as I had expected "prompt" was called before "alert", because I think "Class fields are processed before constructor."
I've been learning from your awesome tutorials since some days and they are really awesome.
I want to thank you for these awesome articles!!!

**Comment by iliakan** [comment]
Please re-read: "Technically, they are processed **after** the constructor"

**Comment by vivek1394Git** [comment]
If they are processed after then why prompt is prompted before alert in the constructor?

**Comment by iliakan** [comment]
prompt is processed immediately, but `name =` - only after constructor.

**Comment by vivek1394Git** [comment]
Please take a look at this article from proposal.
https://github.com/tc39/proposal-class-fields#execution-of-initializer-expressions

> When field initializers are evaluated and fields are added to instances:
> Base class:" At the beginning of the constructor execution", even before parameter destructuring.

Thank you!

**Comment by iliakan** [comment]
Please don't look at the proposal. The proposal is irrelevant.

Look at the specification instead.

**Comment by vivek1394Git** [comment]
Could you please look at this code!
`class User {
  constructor() {
    alert(this.name) // this works
    //constructor is still executing....
  }
  name = "Name"
}

let user = new User();`

**Comment by iliakan** [comment]
Tomorrow I'll add more details about that.

**Comment by iliakan** [comment]
Indeed, not well-explained.

**Comment by vivek1394Git** [comment]
Great, thanks!

**Comment by iliakan** [comment]
Thank you for being persistent with the issue!

**Comment by vivek1394Git** [comment]
Thank you for creating this great website!!!
