### ISSUE TITLE
Epub ebook missing all code blocks in Apple Books

### ISSUE THREAD

**Issue by rmercer33** [javascript-tutorial/en.javascript.info#1988]
Hi, 

The epub version displayed by Apple Books (Catalina), in Parts 1, 2, and 3, are missing all code blocks. Where the code blocks should be is just empty. PDF files are just fine.

Here's the part 1 PDF.

<img width="828" alt="part1-pdf" src="https://user-images.githubusercontent.com/274678/86405556-48511b00-bc4d-11ea-94b5-549cf825ae12.png">

Here's the part 1 epub.

<img width="983" alt="part1-epub" src="https://user-images.githubusercontent.com/274678/86405619-5dc64500-bc4d-11ea-94f8-0300dd8ab4f6.png">

I'd love to have a working epub version, the content is awesome!

**Comment by iliakan** [comment]
Hi,

That's a rare bug in ibooks ;(
---
Best Regards,
Ilya Kantor
https://javascript.info

**Comment by iliakan** [comment]
Fixed!
