### ISSUE TITLE
Change an expression of "numbers" page

### ISSUE THREAD

**Issue by minseokkang8571** [javascript-tutorial/en.javascript.info#1991]
Here's part of the number page.
![image](https://user-images.githubusercontent.com/60080746/86525584-f239dd00-bec3-11ea-8862-05ecce63747b.png)

I want to ask what it is like to have a small change.
In the example, 0.1 and 0.2 are multiplied and divided by 10. But, It is mentioned, "the numbers by 100 (or a bigger number)".
How about changing "number by 100" to "powers of 10"?

**Comment by iliakan** [comment]
sure, we can change that, send a PR?

**Comment by minseokkang8571** [comment]
Thanks, I'll do it
