### ISSUE TITLE
Indo-European	Bosnian	bosanski jezik	bs	bos	bos	bos [ Translation ]

### ISSUE THREAD

**Issue by aiyodev** [javascript-tutorial/en.javascript.info#2022]
I can start translating, at least one or two chapters per day, as it is my native language. I know a lot of Balkan people are interested in programming and this may be suitable ( the Bosnian language can be read by Serbians and Croatians also, so that is for 3 countries already ). Hope I will get the access, peace

Username: @aiyodev
Email: aiyodev@hotmail.com

**Comment by iliakan** [comment]
Which language, which code? Choose one please.

**Comment by aiyodev** [comment]
Sorry, I just pasted the entire row from Wikipedia, I want to translate Bosnian language ( Bosanski jezik ) ISO 639-1 - bs. Greetings

**Comment by aiyodev** [comment]
@iliakan will I get the repo to start with this translation?

**Comment by iliakan** [comment]
Yes, soon.

**Comment by aiyodev** [comment]
@iliakan I comment on the issue with the translation, and also afterwards fork it on my profile, then commit to master with the translation in a text file? Do you have discord?

**Comment by iliakan** [comment]
I'll make a fork, after I update my code to the latest octokit release. Soon.

**Comment by aiyodev** [comment]
Can I already make a repo on my profile, and start with the translation with the same folder structure as on en.javascript.info, and when you fork I just pull request there? And when approximately will the code be updated, also do you have discord?

**Comment by iliakan** [comment]
You can, of course.

**Comment by iliakan** [comment]
I hope to update it today, 1-2 hours if nothing goes wrong.

**Comment by iliakan** [comment]
Done!
