### ISSUE TITLE
this is the object “before dot” --- can fail

### ISSUE THREAD

**Issue by lumosmind** [javascript-tutorial/en.javascript.info#2033]
In this [article ](https://javascript.info/object-methods)and some other article use a technique to explain 'this' keyword like this

> The value of `this `is the object “before dot”, the one used to call the method.

But in this situation the explanation is not enough.
```
const arr = [];
arr[0] = function(){ return this.length; }; // 1
arr[0]();
```

there is no **dot** and `this `refers to `arr`.

**Comment by iliakan** [comment]
That's why I've put quotes around "before dot".

**Comment by lumosmind** [comment]
This can be more clear maybe

**Comment by iliakan** [comment]
There should be tasks and more examples about it, not enough?
