### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by joepie91** [javascript-tutorial/en.javascript.info#2034]
Hi,

There seem to be a number of issues with the licensing/presentation of this project:

1. The license states "The license is basically CC-BY-NC, revocable and exclusive", but this is incorrect; the CC-BY-NC license, like all Creative Commons licenses, is *irrevocable* and *non-exclusive* (and this is also still what the full license text claims).
2. It also states "please get a permission from Ilya Kantor" - but, you are accepting outside contributions, and do not seem to have a Contributor License Agreement (or equivalent) in place, which means that the copyright to those contributions is owned by those making them - and permission to use them *cannot* legally be granted by you, only by the original authors.
3. The site states "The content of this tutorial is open source", but this is incorrect - while CC-BY-NC is a Creative Commons license, it is not an *open-source* license, as it violates point 6 of the [Open-Source Definition](https://opensource.org/osd-annotated).

Point 1 can be resolved by simply removing the "revocable and exclusive" remark, as the full license text itself already includes the correct text.

Points 2 and 3 can be resolved by either a) switching to an actual open-source license (eg. CC0, CC-BY, CC-BY-SA, or GFDL), or by b) adding a CLA and removing the "open-source" claim while sticking with the current license. Note that changing the license will also require permission from past contributors whose contributions you want to relicense.

Please let me know if there's anything I can help to clarify!

**Comment by iliakan** [comment]
Hi,

1. That's why there's word "but" in there. Also, the word "basically". We can rephrase it of course, I just put it short there.
2. There's CLA for contributors on github.
3. We can rephrase if indeed. I just mean that the content is on github, where anyone can read it. We're not talking about "open source software" here.

P.S. As of now, I never denied licensing requests for educational and non-commercial use.
