### ISSUE TITLE
Consider replacing all instances of `alert` with `console.log`

### ISSUE THREAD

**Issue by Pomax** [javascript-tutorial/en.javascript.info#2035]
As a modern tutorial on modern JS, please consider replacing all instances of the legacy `alert()` function with `console.log`. Especially for a work with the aim to teach proper JS and modern patterns, showing (let alone teaching) `alert` hampers learners by teaching them a function that no one should be using anymore. Looking at the dev console is an integral part of learning modern JS, and the Console API has been a much better friend to learners and seasons devs alike since 2010 than `alert` ever was.

**Comment by MuhammedZakir** [comment]
I second this! A chapter about console is already there in introduction -  https://javascript.info/devtools.

**Comment by Pomax** [comment]
It really isn't: all sane mobile development platforms have remote debugging _which you should teach_ in a tutorial on modern JS. The `alert` function, as a _process blocking low level call that can't even show anything except forced toString evaluations_ has no place here, and is exactly the kind of legacy baggage that should absolutely be pruned from anything that calls itself "The Modern JavaScript Tutorial".

`alert` is not modern JS. It's not even modern back when ES5 was modern. `alert comes to use from when Jaascript versioning started with "1", and should never, ever be taught anymore. Use the console API, and if you need to do mobile debugging: use modern mobile debugging.

Or stop calling it "The Modern JavaScript Tutorial" of course. Either works. But removing `alert` is by far the more correct course of action.

**Comment by iliakan** [comment]
Oh, sure, using "alert" for alerts makes the tutorial not modern. Come on! (irony mode off).

I just explained the exact reason why `alert` is used - for convenience of users. 

Closing this, unless you'd like to offer something that doesn't remove this convenience.

**Comment by Pomax** [comment]
a) it locks the browser.
b) it cannot print anything other than strings

If your rationale is "it's easier on mobile": cool, and also really weird, because if we're making sites for mobile, we're doing that in something that lets us test _everything_ we write, and you should teach that. That includes remote debugging,

**Comment by iliakan** [comment]
Strings are ok for the tutorial. Blocking is a minus, but not having to open devtools is a plus.

**Comment by Pomax** [comment]
Dev tools is the biggest friend of modern JS work: not just because of the console, but because it lets you check all the things you think you did: event listeners on HTML elements, breakpoints in scripts, etc. Not teaching that as one of the first steps after the syntax basics would be really weird? It's there because it _helps_ you do Javascript, rather than impair it.

**Comment by MuhammedZakir** [comment]
Remote debugging is only viable if there is one more device. So for users reading from mobile, console is not an option. I presume this is what @iliakan is saying.

> Dev tools is the biggest friend of modern JS work: not just because of the console, but because it lets you check all the things you think you did: verify event listeners on HTML elements, set and remove breakpoints in scripts, check that the JS you're trying to load from file even makes it across the network etc. Not teaching that as one of the first steps after the syntax basics would be really odd? It's the most important tool in your arsenal right after your preferred code editor.
> 
> It's there because it helps you get JS (and a lot else of course) right, rather than make it harder.

I don't think all these should be presented before understanding JS. These should be in debugging part. However, I do agree console logging must be used **if** possible.

A solution that's coming to my mind is to output console log in a box or something, similar to stackoverflow. I am not sure if this is a "good" idea or how feasible it is [1], but they will get the message - "log to console when inspecting." We can add a chapter at the beginner with a brief explanation.

[1] Displaying an object, checking object properties and all those basic console stuffs.

**Comment by iliakan** [comment]
We can, indeed,

**Comment by MuhammedZakir** [comment]
> We can, indeed, show a "console box" below the example.
> 
> Is it better than alerts?

In my opinion, yes! `alert` is probably more than sufficient for inspecting in this tutorial, but users may think this is the tool for inspecting and this might lead to future problems.  For example, logging an object. So if it is possible, we must use console.

**Comment by iliakan** [comment]
No need to inspect stuff in the examples. IF someone really needs a full-fledged UI, there's a button to open the example in plnkr.

**Comment by MuhammedZakir** [comment]
Not examples, but when coding. What I am telling is because all these examples use `alert` for logging, they will think this is ***the*** tool for inspecting and they may use it for things like object. Instead of that, we want them to think "if you want to inspect, use console logging", from the get go.

**Comment by iliakan** [comment]
Do you mean tasks?

**Comment by MuhammedZakir** [comment]
> Do you mean tasks?

Not just tasks, but in general; whenever they write JS.

**Comment by Pomax** [comment]
This is a pretty good idea - back when we were still working on Processing.js, we have a console "div" that was able to print information there, without blocking the thread or needing the dev tools, so giving users a prebuilt "if you're going to play along with our tutorials, make sure to include this js file: ... " would be a pretty solid solution too.

**Comment by iliakan** [comment]
We'll be planning a total rework of the task system, and there'll be `console.log` there.
