### ISSUE TITLE
Chrome console update (debugging in chrome). Should we change the explanation?

### ISSUE THREAD

**Issue by ArnoldGee** [javascript-tutorial/en.javascript.info#2036]
The Chrome console breakpoints are now red, not blue. Maybe we should change the image or update the explanation.

![image](https://user-images.githubusercontent.com/66358043/89106249-8e55f600-d428-11ea-80b6-1dae3a9af2f8.png)

Part of the course: https://javascript.info/debugging-chrome

**Comment by iliakan** [comment]
We can, although I don't think that matters, the very minor change.
