### ISSUE TITLE
Websocket: Data Transfer, incorrect property

### ISSUE THREAD

**Issue by Autotonic** [javascript-tutorial/en.javascript.info#2037]
```js
socket.bufferType = "arraybuffer"
```
Should be:
```js
socket.binaryType = "arraybuffer"
```

[in Websocket#Data Transfer](https://github.com/javascript-tutorial/en.javascript.info/blob/master/5-network/11-websocket/article.md#data-transfer)

**Comment by iliakan** [comment]
Fixed, thanks.
