### ISSUE TITLE
Mixins - EventMixin - Example description is misleading

### ISSUE THREAD

**Issue by arcticmatt** [javascript-tutorial/en.javascript.info#2039]
The description of the example code says the following:

> After adding the mixin, an object user will be able to generate an event "login" when the visitor logs in. And another object, say, calendar may want to listen for such events to load the calendar for the logged-in person.
> 
> Or, a menu can generate the event "select" when a menu item is selected, and other objects may assign handlers to react on that event. And so on.

However, based on my understanding of the example code, these type of cross-object use cases are not supported.

For example, if you run the example code, `_eventHandlers` is stored on the objected referenced by `menu`. So if you created another `Menu` object, the two will not be able to interact via events.

**Comment by iliakan** [comment]
Can you please show me the problem that you see? Maybe a piece of code?
Everything should be ok.

**Comment by arcticmatt** [comment]
```
let eMixin = {
  /**
   * Subscribe to event, usage:
   *  menu.on('select', function(item) { ... }
  */
  on(eventName, handler) {
    if (!this._eventHandlers) this._eventHandlers = {};
    if (!this._eventHandlers[eventName]) {
      this._eventHandlers[eventName] = [];
    }
    this._eventHandlers[eventName].push(handler);
  },

  /**
   * Cancel the subscription, usage:
   *  menu.off('select', handler)
   */
  off(eventName, handler) {
    let handlers = this._eventHandlers?.[eventName];
    if (!handlers) return;
    for (let i = 0; i < handlers.length; i++) {
      if (handlers[i] === handler) {
        handlers.splice(i--, 1);
      }
    }
  },

  /**
   * Generate an event with the given name and data
   *  this.trigger('select', data1, data2);
   */
  trigger(eventName, ...args) {
    if (!this._eventHandlers?.[eventName]) {
      return; // no handlers for that event name
    }

    // call the handlers
    this._eventHandlers[eventName].forEach(handler => handler.apply(this, args));
  }
};

// Make a class
class Menu {
  choose(value) {
    this.trigger("select", value);
  }
}
// Add the mixin with event-related methods
Object.assign(Menu.prototype, eMixin);

let menu = new Menu();

// add a handler, to be called on selection:
menu.on("select", value => alert(`Value selected: ${value}`));

// triggers the event => the handler above runs and shows:
// Value selected: 123
menu.choose("123");

let menu2 = new Menu();
// This does nothing
menu2.choose("123");
```

@iliakan the last two lines are what I'm talking about. The lines above are taken from the article.

**Comment by iliakan** [comment]
So, what's wrong, please explain?

**Comment by arcticmatt** [comment]
It's not necessarily wrong, just inconsistent with the description of the code.

>After adding the mixin, an object user will be able to generate an event "login" when the visitor logs in. And another object, say, calendar may want to listen for such events to load the calendar for the logged-in person.
>
>Or, a menu can generate the event "select" when a menu item is selected, and other objects may assign handlers to react on that event. And so on.

This makes it sound like you can do something like:
```
calendar.on("login", name => alert(`${name} logged in`));
user.trigger("login", "bob");
```

but that doesn't work with the code provided.

**Comment by iliakan** [comment]
Please suggest a PR to fix it?

**Comment by arcticmatt** [comment]
Sure, I'll put one up this weekend :)
