### ISSUE TITLE
Hebrew Translation

### ISSUE THREAD

**Issue by ElchananBS** [javascript-tutorial/en.javascript.info#2041]
Hello, I'd to help with the creation of a Hebrew version of the tutorial. to be honest, I don't know if I fit to the description as _"...know JavaScript well enough to translate and review pull requests of others"_, but I believe that even a proper and initial translation of some of the chapters may be very beneficial to a lot of Hebrew readers. 
Language Code: 
He
My github nick: 
ElchananBS
You can contact me by:
elchan@outlook.co.il

**Comment by iliakan** [comment]
Repo created, invite sent!
