### ISSUE TITLE
Coordinates article needs an update

### ISSUE THREAD

**Issue by maksumi** [javascript-tutorial/en.javascript.info#2049]
Hi, @iliakan 
There is a warning box on line 91 of the article ['Coordinates'](https://github.com/javascript-tutorial/en.javascript.info/edit/master/2-ui/1-document/11-coordinates/article.md), which explains that IE and Edge browsers do not support x / y values. But Edge [currently does](https://caniuse.com/#search=getBoundingClientRect).

**Comment by iliakan** [comment]
PR plz?

**Comment by maksumi** [comment]
Ok! I'll send it
