### ISSUE TITLE
Small typo in this tutorial's last task: https://javascript.info/operators#fix-the-addition

### ISSUE THREAD

**Issue by iJeanPaul** [javascript-tutorial/en.javascript.info#2070]
I think this is a typo, it should be "What we should do is...". See this screenshot:

![typo-screenshot](https://user-images.githubusercontent.com/17973161/90595830-888b3f00-e1a2-11ea-8bd0-3f1ef9139b74.PNG)

**Comment by MuhammedZakir** [comment]
You're right! I'll include it in my PR!
