### ISSUE TITLE
[Word Modification] Part 2. Window size and scrolling

### ISSUE THREAD

**Issue by benz-e-class** [javascript-tutorial/en.javascript.info#2079]
Hi!
I'm ko.javascript contributor member.

in Part 2. Window size and scrolling

<img src="https://i.imgur.com/cJF9ia8.jpg"></img>

I think "elem.scrollLeft/scrollTop" words will confuse the people who is study.

So, I suggest revising this sentence to "element.scrollLeft/scrollTop"

have a nice day ^^

**Comment by iliakan** [comment]
Please make a PR?

I'd suggest:
"DOM elements have their current scroll state in their `scrollLeft/scrollTop` properties."

P.S. If you post like that, please add a link to the article =) Makes it simpler to fix.
