### ISSUE TITLE
setTimeout limitations

### ISSUE THREAD

**Issue by moisheschwartz** [javascript-tutorial/en.javascript.info#2080]
In [this](https://javascript.info/settimeout-setinterval) article there is an information box with the header **Zero delay is in fact not zero (in a browser)** when in fact 1 or 2 delay (up to 5) is not 1 or 2 delay as well.

It can confuse some readers that this behavior is only when a time is not set at all, but if a time is set (even less than 5 ms) it would work as expected.

![image](https://user-images.githubusercontent.com/17932167/91185818-45f2c680-e6bc-11ea-934e-36775979e292.png)

**Comment by moisheschwartz** [comment]
The information is correct, I just thought that this title might be misleading as someone can think that this behavior only happens when a time is not specified at all.

**Comment by iliakan** [comment]
The first line in the block is more precise about it. Quoting HTML5 spec =)
