### ISSUE TITLE
3-1 popups - possible issue?

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/en.javascript.info#2083]
3-frames-and-windows/01-popup-windows/article.md
I don't know if it is an issue in english
it is an important safety concept and tne translator got it wrong, 

18 
A popup is a separate window with its own independent JavaScript environment. So opening a popup with a third-party non-trusted site is safe.

I reviewed to something like

...So it is safe opening an OWN popup FROM a third-party non-trusted site .

**Comment by iliakan** [comment]
Right, fixed!
