### ISSUE TITLE
Size Unit Fix

### ISSUE THREAD

**Issue by C17AN** [javascript-tutorial/en.javascript.info#2085]
Hi! I'm a true lover of your Project

in [Cookies, document.cookie](https://javascript.info/cookie), 
![image](https://user-images.githubusercontent.com/26535030/91372660-2dff7c00-e84f-11ea-9dc0-0026e7efb0da.png)

it seems "4kb" means 4 kilobit, but it should point 4 kiloByte.

It may be a little change, But someone may be confused on it :)

**Comment by iliakan** [comment]
Sure, thanks!
