### ISSUE TITLE
Maintainer permissions request for pl.javascript.info repository.

### ISSUE THREAD

**Issue by Fjollsfinn** [javascript-tutorial/en.javascript.info#2089]
Hello,
I would like to become a maintainer of [https://github.com/javascript-tutorial/pl.javascript.info](url) repository. I have already started Polish translations, but there is only one maintainer of the repository, and he doesn't respond since a week.  There are some PR that are hanging since month, and needs CR. I see that there are still some people that want to works on translations. I believe that granting me a maintainer will help to get a milestones and complete finish Polish translations.
Sincerely,
Bartłomiej Tuchowski

**Comment by iliakan** [comment]
Done!
