### ISSUE TITLE
IIFE example (let --> var)

### ISSUE THREAD

**Issue by minho-kim-uos** [javascript-tutorial/en.javascript.info#2098]
Isn't it more appropriate to use "var" instead of "let" in IIFE examples to make a point?

**Comment by MuhammedZakir** [comment]
+1! Also, I think IIFE's heading level should be H2 rather than H3.

**Comment by iliakan** [comment]
You mean some place in the tutorial? Put a link here?

**Comment by MuhammedZakir** [comment]
> You mean some place in the tutorial? Put a link here?

This is in "The old var" chapter - https://javascript.info/var#iife. I have made some changes to this and added it in my PR #2081.

**Comment by iliakan** [comment]
Please don't use `var`, it's an outdated language feature. There's no reason to use `var` there. I don't understand the issue at all.

**Comment by iliakan** [comment]
Can fix it there, right. @MuhammedZakir you fix that in #2081?

**Comment by minho-kim-uos** [comment]
> > You mean some place in the tutorial? Put a link here?
> 
> This is in "The old var" chapter - https://javascript.info/var#iife. I have made some changes to this and added it in my PR #2081.

As far as I understand, the whole point of the "IIFE example" https://javascript.info/var#iife is to show that we can "emulate" the "block scope" for "var" variables.
"let" variables do not need IIFE trick.

**Comment by MuhammedZakir** [comment]
> Can fix it there, right. @MuhammedZakir you fix that in #2081?

Yes! https://github.com/javascript-tutorial/en.javascript.info/pull/2081/commits/69e7f6f0e132c38b7f3de2cd1d514d3a8d940615#diff-a28a5a6e5f04ce8e5867757c61407e99R219

> Are we on the same page?
> Can I edit the title of this issue to "let --> var"?

You can!
