### ISSUE TITLE
Thanks to javascript.info I'm from zero to hero in JS

### ISSUE THREAD

**Issue by Gadrawingz** [javascript-tutorial/en.javascript.info#2130]
I started tutorial on javascript.info from June 2019 to September 2020 
I'm done with whole doc. thanks I think I am master (zero to hero)

**Comment by MuhammedZakir** [comment]
1. https://github.com/getify/You-Dont-Know-JS
2. https://johnresig.com/apps/learn/ (**must read**)
3. https://github.com/getify/Functional-Light-JS/
4. https://github.com/sorrycc/awesome-javascript#worth-reading

You should also check websites linked in intermediate level and advanced level in JS tutorial -- https://developer.mozilla.org/en-US/docs/Web/Tutorials#Intermediate_level_3.

Pit your skill
  * https://johnresig.com/apps/learn/
  * https://www.freecodecamp.org/learn/ - interactive tutorial
  * https://github.com/sudheerj/JavaScript-Interview-Questions [1]
  * https://github.com/MaximAbramchuck/awesome-interview-questions#javascript [1]

[1] Don't try to memorize them. Try to solve them! And, it's okay if you don't know the answer for some of them. Interview questions are **meant to trip YOU**! 😅

**Comment by iliakan** [comment]
Thanks. That's not an issue though! I can't leave it's open :(
