### ISSUE TITLE
Additional elaboration/explanation idea

### ISSUE THREAD

**Issue by jeffnesselhuf** [javascript-tutorial/en.javascript.info#2132]
I am using this textbook for my community college Javascript course and am happy that it is the primary textbook. However, as I am a beginner, I find some examples truly hard to understand by just reading the examples and I sometimes search  google and/or youtube for additional explanations. That made me come up with an idea.

Why doesn't this textbook offer automatic links to some "preferred" additional explanations. In fact, it would be great if they were in the form of embedded videos, if I really wanted to be lazy about seeking more explanations. Compensation for the added explanation could be in the form of ad revenue or any other measurably financial incentive.

However, this is just a thought.

**Comment by iliakan** [comment]
Hi, thanks for the feedback!

Could you provide some examples of what’s causing difficulties?

**Comment by jeffnesselhuf** [comment]
No difficulties at all. This is a very helpful book. I just thought adding easily accessible video explanations could help the reader, like me.   So, for instance, a inserted a screenshot of a section that I was finding difficult to grasp at first. After I watched a video on youtube, I then fully understood the concept after reading your section again.  

Hope that makes sense, 

Jeff 

<img width="855" alt="Screen Shot 2020-09-20 at 10 42 16 AM" src="https://user-images.githubusercontent.com/31998915/93715275-fcb45c00-fb2d-11ea-9ffd-2c3575da7c26.png">

**Comment by iliakan** [comment]
![image](https://user-images.githubusercontent.com/349336/93722951-307d9900-fba3-11ea-9388-ce6312e034fe.png)

**Comment by iliakan** [comment]
what else should I elaborate here...

**Comment by iliakan** [comment]
I heavily modified the article, hope it helped. Closing due to no feedback.
