### ISSUE TITLE
Tutorial map hiding scrollbar

### ISSUE THREAD

**Issue by NasratTalash** [javascript-tutorial/en.javascript.info#2135]
Hi
The tutorials map on the website is hiding the scrollbar which eventually hides the thumb of the scrollbar when page is on the starting point. I applied margin-right to tutorial-map__filter div and it seems to work. I could not figure out how to fix it, since I didn't find the CSS file on GitHub. 
I wish someone fix it.
thanks
![thumb](https://user-images.githubusercontent.com/52889417/93711365-e4126900-fb62-11ea-8c28-c01e06175183.jpg)

**Comment by GSemikozov** [comment]
Hi @NasratTalash ,
Could you please specify what kind of device do you use? On my macbook chrome browser I don't have any problems with scrollbar:


<img width="1089" alt="Screenshot 2020-09-26 at 13 22 25" src="https://user-images.githubusercontent.com/6191270/94338493-54096f00-fffb-11ea-8d51-d91f8ff0aeb4.png">

**Comment by NasratTalash** [comment]
Hey 👋
I am using windows machine and I had this problem in both chrome and
firefox browsers.
The tutorial search field div is taking the whole width of screen, even it
goes on scrollbar. Using developer tools, I applied margin-right to div and
it solved the problem.

Thanks

**Comment by GSemikozov** [comment]
okey, thanks, I will check on windows
