### ISSUE TITLE
Comparing '0'==[]

### ISSUE THREAD

**Issue by rahulrajanpk** [javascript-tutorial/en.javascript.info#2136]
Can we add a topic on this famous JS meme that even if
>>0==[]
true
>>0=='0'
true

but
>>'0'==[]
false 

it is an interesting topic where JS complier cannot coerce to same data type

**Comment by iliakan** [comment]
Maybe suggest a PR, add a task or to an existing task? :)

**Comment by rahulrajanpk** [comment]
Sure I will create a PR but should it be under the topic  'Comparison' or 'Array' ?

**Comment by iliakan** [comment]
Somewhere where people know enough to understand :) Not comparison definitely, maybe object type conversions.

**Comment by rahulrajanpk** [comment]
Object conversion is before the Array. I request to be it in the topic 'Arrays'

**Comment by rahulrajanpk** [comment]
Hi @iliakan , I have created a new PR for the same #2150

**Comment by iliakan** [comment]
Thank you, I've read it and updated the tutorial.
