### ISSUE TITLE
Confusion around already settled promises on the website

### ISSUE THREAD

**Issue by arpitsr91** [javascript-tutorial/en.javascript.info#2137]
On  [this page](https://javascript.info/promise-basics), it says that already settled promises have their handlers executed immediately. This is very confusing because if there is any synchronous line of code after promise.then, it will be executed first even if the promise is settled already. Referring to the code below, taken from the website - 

```
// the promise becomes resolved immediately upon creation
let promise = new Promise(resolve => resolve("done!"));

promise.then(alert); // done! (shows up right now)
```

if there is an `alert('this first')` after the `promise.then(alert)` line, 'this first' is alerted first.
Correct me if I'm wrong, I'm just learning promises and tried out in JS environments as well.

**Comment by rahulrajanpk** [comment]
hey @arpitsr91 , not sure if you got it resolved but if you are still looking for an answer then go the chapter  'Event loop:microtasks and macrotasks' under 'Macrotasks and Microtasks' you will get your answer why alert was executed before promise.

**Comment by iliakan** [comment]
I changed the text there.
