### ISSUE TITLE
Try out editor

### ISSUE THREAD

**Issue by kenliten** [javascript-tutorial/en.javascript.info#2153]
I was wondering what way can this project be improved, and then I got it (sorry about this intro block).

My idea is to give the user an inline try-it-out editor, so the user can edit the script of build a new one to practice the things is learning, and this way avoid to go to the installed editor, and setup a server, and finally see the result in a browser (Yeah, i'm talking about me here).

I think that something like a jsFiddle embed editor can work.

Regards!

**Comment by iliakan** [comment]
We're working on it ;)
