### ISSUE TITLE
String comparison - potential typo in examples

### ISSUE THREAD

**Issue by Kaos-Industries** [javascript-tutorial/en.javascript.info#2166]
I'm having trouble understanding [string comparison](https://javascript.info/comparison#string-comparison), and I'm not sure if it's just because of this potential typo in the examples:

```
Example 3: alert( 'Bee' > 'Be' ); // true
```

The solution says:

```
3. o is greater than e. Stop here. The first string is greater.
```

However, there is no `o` anywhere to be seen in that example.

I found this particular section to be quite confusing as a whole, including the algorithm. To ensure I've understood it correctly, is it saying that a longer string is always greater than a shorter string, regardless of the characters?

**Comment by iliakan** [comment]
Updated.
