### ISSUE TITLE
Rest parameters / spread with objects

### ISSUE THREAD

**Issue by yousefelgoharyx** [javascript-tutorial/en.javascript.info#2167]
At the end of this article:
https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/06-advanced-functions/02-rest-parameters-spread
it says that you could also use **Rest parameters / Spread** with objects, however, objects are not itreables.
I hope you could clarify this by saying that **Rest parameters / Spread** with objects are still a proposal Ii suppose

[](https://github.com/tc39/proposal-object-rest-spread)

**Comment by iliakan** [comment]
It's in the spec, no?

**Comment by MuhammedZakir** [comment]
> Rest/spread for objects in the 2020 spec, no?

Yes. It was included in 2018.

https://tc39.es/ecma262/:
> ECMAScript 2018 introduced support for asynchronous iteration via the AsyncIterator protocol and async generators. It also included four new regular expression features: the dotAll flag, named capture groups, Unicode property escapes, and look-behind assertions. **Lastly it included object rest and spread properties.**

**Comment by iliakan** [comment]
Is there anything to do here then? Reopen if so.

**Comment by iliakan** [comment]
Thanks, @MuhammedZakir
