### ISSUE TITLE
Add "hacktoberfest" topic to the repository

### ISSUE THREAD

**Issue by Arnau-Ninerola** [javascript-tutorial/en.javascript.info#2169]
Hello! As you may or may not know in this month of October there is an even called Hacktoberfest going on all through the month of October. The motivations behind are to bring attention to open source and motivate new contributions to projects you like or benefit from, as well as to bring new and experienced developers to participate. With that in mind, and with the help of some sponsors like DigitalOcean, Dev and others, they give away some small tokens for meeting the requirements (making 4 pull requests to open source projects) like some stickers and a T-shirt. This is the 7th consecutive year of the event.

I would like to ask as a suggestion if it is possible to add "hactkoberfest" as the topic of the repository, to bring new contributions and to count this pull requests towards earning that goal and small "prize". For this reaons I have asked to the maintainers of es.javascript.info repo if they could add it, since I make contributions to that repository. After some discussion, they have indicated to me that this responsability falls to you @iliakan. So I would like to ask if this is possible.

Thanks beforehand!

**Comment by iliakan** [comment]
Hi there!

Added!

**Comment by Arnau-Ninerola** [comment]
Thanks a lot! Very appreciated

**Comment by dorelljames** [comment]
Hello @iliakan, it seems like the added topic is incorrect. I was about to create an issue. Glad I've found this. So I think you have mispelled it "hactkoberfest". See below.

![image](https://user-images.githubusercontent.com/977413/95555840-f6d2dc00-0a44-11eb-8494-79776a5038f0.png)

It should be "hacktoberfest". Thank you. 😊

**Comment by iliakan** [comment]
Sorry, typo. Ok now?

**Comment by dorelljames** [comment]
Yep. Thanks @iliakan. I'll look into adding some exercises. 😊
