### ISSUE TITLE
I would like to become a maintainer of the Vietnamese version

### ISSUE THREAD

**Issue by tunggnu** [javascript-tutorial/en.javascript.info#2170]
@iliakan Hi, I would like to participate in speeding up the progress of the Vietnamese translation project. Currently, I see some [pull requests](https://github.com/javascript-tutorial/vi.javascript.info/pulls) without any reviews. I want to apply for the maintainer position. I'm a Vietnamese programmer with some JavaScript experience (4 kyu on [Codewars](https://www.codewars.com/users/tunggnu)).

**Comment by iliakan** [comment]
Done!=)
