### ISSUE TITLE
Polyfills - rewrite needed

### ISSUE THREAD

**Issue by Kaos-Industries** [javascript-tutorial/en.javascript.info#2173]
From [here](https://javascript.info/polyfills):

"New language features may include **new built-in functions** and syntax constructs. The transpiler rewrites the code, transforming syntax constructs into older ones. But as for **new built-in functions**, we need to implement them."

This is ridiculously confusing - what does it actually mean? The article is as a whole not in keeping with the quality of the previous sections of the tutorial, but this passage really stands out to me because it seems to directly contradict itself in the space of two sentences, not to mention the lack of clarity (relative to previous sections). I'm powering through but I hope it's a problem that fixes itself over time rather than a downward trend, which would mean I would have to look for yet another resource to learn JavaScript, which I really don't want to do after having already switched from Eloquent JS.

**Comment by iliakan** [comment]
Rewrote that article.
