### ISSUE TITLE
[Bug] - CSS margin effect Collapsing

### ISSUE THREAD

**Issue by C17AN** [javascript-tutorial/en.javascript.info#2186]
Hi!

I've recognized an CSS error in [modifying-document](https://javascript.info/modifying-document), the code result is violating its' origin code area.

Due to my poor English, I'll add some Photos.

### [Ideal Screen]
![image](https://user-images.githubusercontent.com/26535030/95685765-d79aa100-0c34-11eb-9089-b0ff9dbe40ac.png)

### [Current Screen]
![image](https://user-images.githubusercontent.com/26535030/95685774-e84b1700-0c34-11eb-9db9-a02a4a9a5f4b.png)

I think it's related with `server\modules\styles\blocks\code-example\code-example.styl`, and `.code-example__result` 's is the origin of this matter.

One Weird thing is, I couldn't find value of "margin-top: -21px" or "-21" in entire repository..

![image](https://user-images.githubusercontent.com/26535030/95685818-424bdc80-0c35-11eb-9c16-ba80eb526305.png)

![image](https://user-images.githubusercontent.com/26535030/95685844-660f2280-0c35-11eb-92db-15d5c499b033.png)

So Weird bug, I think..

**Comment by iliakan** [comment]
Fixed.

**Comment by iliakan** [comment]
Thanks!
