### ISSUE TITLE
Fetch: Download progress  code

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/en.javascript.info#2216]
I am not sure it is an issue, It's not my expertise (mostly sql).
I's just... a sniff.

Fetch: Download progress
The lines (whole VS chunks)...

```
// for string
chunksAll = new Uint8Array(selectedLength)
// for binary
let blob = new Blob(chunks);
```

...are creating a solid and maybe big object in memory instead of working with the small chunks.
I feel it's not the way.

1) Am I missing something? Maybe those obj are prepared to handle this  
2) Can it be avoided?
3) If not, should we consider the size of the final object before attempting it?

**Comment by iliakan** [comment]
In practice, we usually know whether the object is big or small.

In theory, one may want to check the size, but I've never seen one do that in real apps.

**Comment by joaquinelio** [comment]
I was thinking about it

What if a user wants an 8 GB movie in a 4 GB w10 notebook. Blob size is 8 GB?  I'm pretty sure Blob obj and OS paging would do an ok job,  but it sounds against JS philosophy / multitasking I try to nail. 

Server... ok, you don't do dwnl progress server side.
anyway, Node warns against ANY cpu/mem intensive use.

thanks!

**Comment by iliakan** [comment]
Surely, devs should think about that, if that may be the case. And if they work with user data (not canvas e.g.).

**Comment by iliakan** [comment]
Maybe add a warning into the text.

**Comment by joaquinelio** [comment]
Warning in the blob case.

If text, it is probably small, and you'll likely be using it in the next steps,  
if blob, probably you dont need blob at all, just catch and, say write to disk/send to another app

But this is a tutorial, it would be nice to mention the... pattern?  
Catch the ball, show it, pass it, forget it and free the hands for the next catch:   Think small =)
