### ISSUE TITLE
Edit the Object section

### ISSUE THREAD

**Issue by ariain** [javascript-tutorial/en.javascript.info#2254]
I would like to suggest that you should add deep cloning section "Warning for Deep Clone" from this MDN link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign to the last section in here https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/04-object-basics/02-object-copy/article.md instead of suggesting a big library like `lodash` to do such a small task...

It suggests too use `JSON.parse(JSON.stringify(obj))` for deep cloning...

**Comment by iliakan** [comment]
JSON.parse/stringify works in simple cases, it's less reliable overall.
