### ISSUE TITLE
Can the <script> tag inserted to any place of the HTML page?

### ISSUE THREAD

**Issue by bruncsak** [javascript-tutorial/en.javascript.info#2263]
It is an excelent tutorial, thanks! It is so good, that's why I take the effort to open this issue.
The page https://javascript.info/hello-world tells that:
`JavaScript programs can be inserted into any part of an HTML document with the help of the <script> tag.`
For me the javascript is a brand new stuff, so I was doing the first exercise, and I put (acidentaly, not voluntarily) the javascript code in between the opening and closing <TITLE> tag in the header. The code was shown in the title, instead of executing. May be you want to change the text to be someting like:
`JavaScript programs can be inserted into an HTML document with the help of the <script> tag. However, there is certain restriction for the location of the code in the HTML page.`
Here is my code which is failing on Firefox 82.0.2 (browser specific issue?):
````
<!DOCTYPE html>
<HTML>
<HEAD>
<TITLE>
<SCRIPT>
    alert("I'm JavaScript!");
</SCRIPT>
Javascript workshop
</TITLE>
</HEAD>
<BODY>
<H1>
Javascript workshop
</H1>
</BODY>
</HTML>
````
If I put the JavaScript code outside of the `Title` tag, it is executing as expected.

**Comment by VictorHPereira** [comment]
Hello bruncsak

In order to execute your code inside a script tag you need to place it
inside the BODY
It's good practice to use it at the body bottom before </body> tag

I'm also new at Javascript and if my explanation it's not suitable please
feel free to correct me.
Keep the good work,

Best regards,
Victor Hugo Pereira


bruncsak <notifications@github.com> escreveu no dia terça, 3/11/2020 à(s)
09:58:

**Comment by bruncsak** [comment]
> 
> Hello bruncsak In order to execute your code inside a script tag you need to place it inside the BODY It's good practice to use it at the body bottom before </body> tag I'm also new at Javascript and if my explanation it's not suitable please feel free to correct me. Keep the good work, Best regards, Victor Hugo Pereira 

Dear Victor Hugo,
Thank you for your comment. It is very useful for me, since (as I already mentioned) I am beginner in JavaScript, good to know where is the best place to put the JavaScript code inside the HTML page.
However, I opened this issue to bring attention to a small inaccuracy in the tutorial itself.

**Comment by iliakan** [comment]
Looks like `<title>` is an exception. I never tried to put JS there. I'll adjust the text.
