### ISSUE TITLE
Data types - Array methods - split and join

### ISSUE THREAD

**Issue by icecream17** [javascript-tutorial/en.javascript.info#2282]
In array methods, https://javascript.info/array-methods, under header "split and join" it shows
![image](https://user-images.githubusercontent.com/58114641/98719312-36972700-2355-11eb-8bc4-166bcafe9f42.png)

I think it was supposed to say:  
Calling `split` with an empty string will split the string into an array of letters

**Comment by iliakan** [comment]
Yes, an empty string. Anything wrong? Please submit a PR if so =)

**Comment by icecream17** [comment]
Ohhh, somehow I thought it said ```split call(s)``` instead of  ```split(var)```, nevermind
