### ISSUE TITLE
callback count

### ISSUE THREAD

**Issue by lumosmind** [javascript-tutorial/en.javascript.info#2287]
> There can be only one callback.

in this [article](https://javascript.info/promise-basics)

but we can send many callback functions in an array.
```
function loadScript(src, callbackList){

  const result = .....

  callbackList.forEach(callback => callback(null, result));
}
```

**Comment by lumosmind** [comment]
I got what does it mean. But it can cause misunderstanding.

**Comment by iliakan** [comment]
I think people get it. The convention says about one callback that gets the result.

Of course we can pass a composition of function as a callback. But then what if we need to add 1 more callback later?

**Comment by lumosmind** [comment]
if producing code is not settled and we have reference to the array, we can add more functions. 
I think there must be more explanation.

**Comment by iliakan** [comment]
I've never seen people doing that even in the old times.

**Comment by lumosmind** [comment]
I have just urged the situation. I know it is weird:)
