### ISSUE TITLE
Danish Translation

### ISSUE THREAD

**Issue by ockley** [javascript-tutorial/en.javascript.info#2299]
I may start up on the danish translation. It seems like no one is actively doing that.

**Comment by iliakan** [comment]
Sure, I'll make you the maintainer.

**Comment by ockley** [comment]
I am not acing Github yet, but I think I am up for it.

**Comment by iliakan** [comment]
Done!

**Comment by ockley** [comment]
@iliakan You have added me to the Dutch translation. I will be of better use in the Danish translation :-)

**Comment by iliakan** [comment]
Ouch! I'm so sorry.
