### ISSUE TITLE
Not clear: "The const fixes the value of user, but not its contents."

### ISSUE THREAD

**Issue by designBuildShipSoftware** [javascript-tutorial/en.javascript.info#2306]
In "Objects: the basics" section, "The const fixes the value of user, but not its contents." is confusing. What do "value" and "contents" mean here? 
In JavaScript, objects are a reference type. Unlike value types, a reference type doesn't store its value directly. Instead, it stores the address where the value is being stored. In other words, a reference type contains a pointer to another memory location that holds the data.
Thus, it is better to say "The const fixes the contents of user, but not its contents' value". Or to make it clearer, just introduce reference type.

**Comment by iliakan** [comment]
Fixed,
