### ISSUE TITLE
On register dialog, Google Plus icon is coming as an option to get registered however it is obsolete as google shutdown it. There should be an icon for google account.

### ISSUE THREAD

**Issue by amarbansal28** [javascript-tutorial/en.javascript.info#2312]
On register dialog, Google Plus icon is coming as an option to get registered however it is obsolete as google shutdown it. There should be an icon for google account.

![js issue](https://user-images.githubusercontent.com/20499516/100112972-dac0b800-2e95-11eb-9314-35866d8f2f2b.png)

**Comment by iliakan** [comment]
@tadjik1

**Comment by amarbansal28** [comment]
@tadjik1
do connect me if any help requried

**Comment by tadjik1** [comment]
hi @amarbansal28 ! thanks a lot for reporting this, I've replaced g+ button with google one
