### ISSUE TITLE
Error to rerun the test on selection-range

### ISSUE THREAD

**Issue by kellywoo** [javascript-tutorial/en.javascript.info#2328]
https://javascript.info/selection-range#range-methods

While I was translating it into Korean I found the example fails when user tries to rerun the test.
![image](https://user-images.githubusercontent.com/25073979/100544508-7d63a700-3299-11eb-872f-9d979afad663.png)

Since  `range` and `methods` variables are declared on global scope and rerun the test 
it tries to  redeclare let variable. 
It needs refresh the DOM.

By the code I checked on developer tool, we can add `data-refresh` attribute to delete the DOM and recreate the iframe, but couldn't find the way to put it. 
![image](https://user-images.githubusercontent.com/25073979/100544440-f1ea1600-3298-11eb-9227-71efb9a19987.png)

**Comment by iliakan** [comment]
Sure, which example fails exactly?

**Comment by kellywoo** [comment]
it is the one under `Range methods`

**Comment by iliakan** [comment]
Fixed.
