### ISSUE TITLE
Minor grammatical fixes

### ISSUE THREAD

**Issue by annasong20** [javascript-tutorial/en.javascript.info#2335]
In **en.javascript.info/9-regular-expressions/15-regexp-catastrophic-backtracking**,

Under **Simplified example**,

1. The first line reads "What’s the matter? Why the regular expression hangs?" I assume the second question should be "Why **does** the regular expression hang?"

2. In the 2nd paragraph under the 1st example, shouldn't "we can use pattern:\d+" be "we can use pattern:\d*"? Because the asterisk in "(\d+)*" indicates 0 or more, so technically empty string should also be allowed.

3. In the next paragraph, "Indeed, the regexp is artificial, we got it by simplifying the previous example" should probably be "Indeed, the regexp is artificia**l; w**e got it by simplifying the previous example"?

4. The 2nd sentence under Step 4 reads "Backtracking generally works like this: the last greedy quantifier decreases the number of repetitions until it can." Shouldn't the last word be "can't"?

Under **Lookahead to the rescue!** ,

1. In the 2nd paragraph, "The pattern to take as much repetitions of \w" should be "take as **many** repetitions".

Lastly, the long string, that causes JS to hang, used in the examples is "An input string that takes a long time or even makes this regexp **to** hang!" It would be grammatically correct if you removed the "to".

**Comment by iliakan** [comment]
Hopefully fixed. Please make a PR next time! Thanks!
