### ISSUE TITLE
Typo in 1.5.8 WeakMap and WeakSet

### ISSUE THREAD

**Issue by FantasqueX** [javascript-tutorial/en.javascript.info#2339]
I found a typo in the article line 287.

It should be "collector" rather than "colector".

I fix it in PR #2338 .

**Comment by iliakan** [comment]
Thanks!

**Comment by FantasqueX** [comment]
As for now, the typo hasn't changed.
It's my first pr, and I don't know what I did wrong.
Should I make a pull request again? @iliakan

**Comment by iliakan** [comment]
Sorry, my fault while resolving a conflict. Should be fine now! Thanks again!
