### ISSUE TITLE
Use of sexualized imagery in gallery examples

### ISSUE THREAD

**Issue by orionrush** [javascript-tutorial/en.javascript.info#2345]
https://javascript.info/ is a mind-blowing resource, just incredible, and so needed and so valuable. 

As such wouldn't it be great if it were a welcoming resource for everyone? And yet a gallery example featuring a girl in a bikini?! It kinda points to a `bro centric` developer community no?  I realise the images are stylised illustrations, but they 
1. only depict women as subjects 
2. only depict one _kind_ of idealised woman
3. in all three examples, the ladies are not wearing much. 

Im working on building a community coding group, and I use javascript.info quite a bit for my own learning and as a resource for others. But I'm uncomfortable with this example because I don't feel great pointing to it especially in groups that have younger girls as members -- it just sends the wrong message. It's a total foot-gun 👣 🔫

This is coming from a position of respect for the great work done here from a married guy who thinks you #can_do_better #must_do_better #code_is_political

https://javascript.info/default-browser-action#image-gallery
https://javascript.info/task/image-gallery

**Comment by iliakan** [comment]
You're working with young girls who get confused with that image? Is that a problem or something else?

May I wonder what country are you from? Is bikini forbidden in your country?

**Comment by iliakan** [comment]
P.S. Feel free to suggest a PR with better images.

**Comment by orionrush** [comment]
It's not culturally forbidden in the UK _per se_, it's just that in educational contexts these kinds of images are unlikely to be appropriate, and when working with vulnerable groups, we have to be especially mindful. For the purposes of the demo [Unsplash](https://unsplash.com/) is a great resource of [free to use imagery](https://unsplash.com/license).

Happy to submit a PR, though, given the number of translations, how is this best done?

**Comment by iliakan** [comment]
Please submit the PR to this repo, and then it'll be synced to translations.

Images should be safe-made or the license should allow to use them like this.

Thank you for caring.

**Comment by iliakan** [comment]
Closing it as inactive. If anyone really cares, I'm open to a PR. If not, then I won't bother too =)
