### ISSUE TITLE
Strange output in example

### ISSUE THREAD

**Issue by vsemozhetbyt** [javascript-tutorial/en.javascript.info#2348]
https://javascript.info/js-animation#using-requestanimationframe

In the last code example, the first number is always < 0 (for example: `-51 49 33 16 16 16 16 16 16 16 16`).

Reduced code:

```js
const prev = performance.now();
requestAnimationFrame(now => console.log(now - prev));
```

The number is always negative. Why `now` is always less than `prev` for the first call?

**Comment by vsemozhetbyt** [comment]
Some info:
https://stackoverflow.com/a/64289656/2625560
https://stackoverflow.com/a/57549862/2625560

**Comment by iliakan** [comment]
Indeed, the Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=919408#c_ts1559905904

Untrigated, I Chrome devs don't care. Should we mention it?

**Comment by vsemozhetbyt** [comment]
Not sure, feel free to close) The topic seems complicated enough as it is)
