### ISSUE TITLE
Else clause definition

### ISSUE THREAD

**Issue by kengruven** [javascript-tutorial/en.javascript.info#2367]
Currently, the Else documentation says: "The if statement may contain an optional “else” block. It executes when the condition is false."

This should be "...when the condition is falsy", right?

**Comment by mrvivacious** [comment]
Further nitpick, " It executes when the condition is false." -> "The **else block** executes when the if condition is **falsy**."

**Comment by iliakan** [comment]
Please send a PR?

**Comment by mrvivacious** [comment]
[PR](https://github.com/javascript-tutorial/en.javascript.info/pull/2387)

**Comment by iliakan** [comment]
I changed the word ;) Thanks.

**Comment by mrvivacious** [comment]
Good work :P
