### ISSUE TITLE
Issue with colored underlining in RegExp articles

### ISSUE THREAD

**Issue by vsemozhetbyt** [javascript-tutorial/en.javascript.info#2380]
[RegExp articles](https://javascript.info/regular-expressions) use this style for variously special parts:

![0](https://user-images.githubusercontent.com/10393198/101791796-9cb9ca00-3b0c-11eb-8a32-1eac59a13c30.png)

In desktop browsers, with big line spacing, these underlining emulations seem OK. But in some mobile browsers or in browsers with narrower line spacing, the code spans overlap, and parts of underlining disappear.  Here are screenshots from Google Chrome Stable (87) for Android:

<details>
<summary>Screenshots :</summary>

![1](https://user-images.githubusercontent.com/10393198/101792474-6af53300-3b0d-11eb-9dd9-8ce931b83b9d.png)
![2](https://user-images.githubusercontent.com/10393198/101792477-6b8dc980-3b0d-11eb-8cef-354135fdc02c.png)
![3](https://user-images.githubusercontent.com/10393198/101792478-6c266000-3b0d-11eb-99b5-eb22d09c9b97.png)
![4](https://user-images.githubusercontent.com/10393198/101792481-6c266000-3b0d-11eb-9e12-d7a162cf58fe.png)

</details><br>

Not sure if this is worth fixing, so feel free to close if not.

**Comment by iliakan** [comment]
@gsemikozov please take a look.

**Comment by GSemikozov** [comment]
should be done @iliakan
