### ISSUE TITLE
String.prototype.replaceAll()

### ISSUE THREAD

**Issue by vsemozhetbyt** [javascript-tutorial/en.javascript.info#2382]
[`String.prototype.replaceAll()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) seem [supported](https://caniuse.com/?search=replaceAll) in all main modern browsers. Maybe it is worth adding or mentioning in the [Methods of RegExp and String](https://javascript.info/regexp-methods).

**Comment by iliakan** [comment]
Indeed. Will you make a PR or suggest me to do it?

**Comment by vsemozhetbyt** [comment]
I think your English is significantly much better than mine, so your variant is preferable)
If you have not enough time to do it in the near future, please, let me know here and I will make a try)
