### ISSUE TITLE
an error in 1-js/06-advanced-functions/03-closure/5-function-in-if

### ISSUE THREAD

**Issue by aruiyao** [javascript-tutorial/en.javascript.info#2392]
https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/06-advanced-functions/03-closure/5-function-in-if

Only "use strict", the result is an error. But, this task not "use strict"

**Comment by vsemozhetbyt** [comment]
See https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/02-first-steps/03-strict-mode/article.md#should-we-use-strict

> All examples in this tutorial assume strict mode unless (very rarely) specified otherwise.
