### ISSUE TITLE
Fetch API: wrong information about `redirect`?

### ISSUE THREAD

**Issue by ClementParis016** [javascript-tutorial/en.javascript.info#2394]
In the Fetch API page, there is a section about `redirect` (https://javascript.info/fetch-api#redirect):
https://github.com/javascript-tutorial/en.javascript.info/blob/a43c18ff18eb6a770d996b5ba699c872c6861fce/5-network/06-fetch-api/article.md#L166-L174

From my own understanding of the Fetch API, I think the details about how the `manual` value works are wrong: `response.url` doesn't hold the new URL and `response.redirected` is not `true` but `false`.

I think it's actually the Fetch API that is misleading in that regard, this has been reported here: https://github.com/whatwg/fetch/issues/763
And it's described as follows in the spec:
![image](https://user-images.githubusercontent.com/5601687/102480760-0a13b080-4061-11eb-9d1a-5348ea3fd523.png)
https://fetch.spec.whatwg.org/#requests

I'd be happy to update that but I'd like other point of views just to be sure I'm not missing something :)

**Comment by iliakan** [comment]
The issue https://github.com/whatwg/fetch/issues/763 was closed.

Was the spec updated? Is the information correct at https://fetch.spec.whatwg.org/#requests ?

Otherwise, it may be that the particular implementation is wrong.

**Comment by ClementParis016** [comment]
Yes, the discussion has been continued (and is still opened) at https://github.com/whatwg/fetch/issues/601.

From my own experience this is really how it works, at least in Chrome, Firefox & Safari. The official spec is by definition the source of truth for what the **correct** implementation should be so I think this can be trusted :)

**Comment by iliakan** [comment]
That's a good thing to note!

Could you make a PR then? :)

**Comment by iliakan** [comment]
Fixed, thanks!
