### ISSUE TITLE
Top-level await supported (V8, at least)

### ISSUE THREAD

**Issue by octavian-nita** [javascript-tutorial/en.javascript.info#2401]
Apparently, top-level `await` has been supported for more than a year now (at least in V8, so everything Chrome, Chrome -based, Node).

https://v8.dev/features/top-level-await#:~:text=Top-level%20await%20enables%20developers,they%20start%20evaluating%20their%20body.

Thus, I guess the nice section on `async/await` needs a bit updated.

**Comment by iliakan** [comment]
The article being 1 year old doesn't mean the feature is supported.

Top-level await, as illustrated at your link, is supported at Chrome 89+. The current version of Chrome is 87. 

I added a note about that.

**Comment by octavian-nita** [comment]
Thanks for the update.

Of course, I was only referring to the time since the V8 announcement to highlight that enough time has passed, and I would consider it worth mentioning this change :)
