### ISSUE TITLE
Function name inside function expression

### ISSUE THREAD

**Issue by Georgy-Losenkov** [javascript-tutorial/en.javascript.info#2403]
Could you clarify case when name is used inside expression, like the following:
`let func = function showMessage(message) { alert(message); };`

**Comment by iliakan** [comment]
Which article causes questions?

**Comment by lumosmind** [comment]
I remember that is related Named Function expression

24 Ara 2020 Per 10:06 tarihinde Ilya Kantor <notifications@github.com> şunu
yazdı:

**Comment by Georgy-Losenkov** [comment]
This one
https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/02-first-steps/16-function-expressions/article.md
I got answer much later. So it would be fine to mention such possibility and refer to another article

**Comment by iliakan** [comment]
I don't see any named function expressions in that article.
