### ISSUE TITLE
looping infinity

### ISSUE THREAD

**Issue by dharmatv** [javascript-tutorial/en.javascript.info#2407]
In Garbage collection topic, we have a interlinked objects subtopic, below of the subtopic one example available, that example will go into infinity I don't why can u please correct if that is wrong

Please correct me If I am wrong

**Comment by vsemozhetbyt** [comment]
Do you mean this example?

```js
function marry(man, woman) {
  woman.husband = man;
  man.wife = woman;

  return {
    father: man,
    mother: woman
  }
}

let family = marry({
  name: "John"
}, {
  name: "Ann"
});
```

From my test, it has no issues. Can you add more details?

**Comment by vsemozhetbyt** [comment]
If you mean that trying to unfold/access all the property of the `family` recursively would end up in infinite recursion, it is true. However, just logging out of the object is OK, as the `console.log()` would do that lazily, it does not try to output all the circular infinite links at once.

**Comment by dharmatv** [comment]
Why looping happens here without calling any function recursively 
This is stupid/small question but I didn't understand
please enlighten on me

**Comment by vsemozhetbyt** [comment]
Sorry, I do not understand what do you mean by looping. Can you describe the steps that lead you to confusion?

**Comment by dharmatv** [comment]
Sorry for that

Why and How recursion happens here ??

**Comment by vsemozhetbyt** [comment]
Recursion can happen only if you try to access all the properties step by step into depth — either programmatically or by interacting with `console.log(family)` output.

**Comment by dharmatv** [comment]
Didn't understand, can you please elaborate.

**Comment by vsemozhetbyt** [comment]
For example, if you try to run the example in the console, output it and unfold it by clicking, there will be infinite unfolding:

![1](https://user-images.githubusercontent.com/10393198/103151946-6f675000-478b-11eb-9e05-c4b4df3355b9.png)

**Comment by dharmatv** [comment]
I know this, but I am asking how it is recurring

**Comment by iliakan** [comment]
You're correct.
