### ISSUE TITLE
Serbian Translation

### ISSUE THREAD

**Issue by joannaaldebaran** [javascript-tutorial/en.javascript.info#2408]
I would like to translate this into serbian language, The code  ISO 639-2 = 'srp' .
maintainers : joannaaldebaran , jovanap96@live.com.

**Comment by iliakan** [comment]
Did you change your mind?

**Comment by joannaaldebaran** [comment]
No, I'm sorry. I accidentally closed it.

**Comment by iliakan** [comment]
Hi, Sorry for the delay! New Year issues took my time ;( I've created the translation and sent you the invite!
