### ISSUE TITLE
Happy New Year!

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/en.javascript.info#2415]
Yey! =)

**Comment by Violet-Bora-Lee** [comment]
Happy New Year :)

**Comment by iliakan** [comment]
Let's hope it'll be a great year! We have lotsofplans (c).

**Comment by Violet-Bora-Lee** [comment]
Lots of! 😮 Could you share the info about the v2 repository btw?

**Comment by iliakan** [comment]
Oh, you saw this one? ;) 

We develop new-style tasks, with embedded code editor. Planned this long ago, and actively working on it now.

I'll give a preview once it's ready.

**Comment by kavehsaket** [comment]
Happy new year! Do you have any plans to publish your Node.js course in English? @iliakan

**Comment by iliakan** [comment]
We have something already, but the progress is slow @kavehsaket

**Comment by lumosmind** [comment]
> We have something already, but the progress is slow @kavehsaket

Where do you publish your courses. Google hide you very well :)

**Comment by iliakan** [comment]
@kavehsaket probably talks about the screencast. We do some online-teaching in Russian, but don't plan to do the same in English.

**Comment by lumosmind** [comment]
It can be good to see you on Udemy.

**Comment by kavehsaket** [comment]
@iliakan Yes correct. So I should start to learn Russian then. 😜
