### ISSUE TITLE
one line IF style 

### ISSUE THREAD

**Issue by lumosmind** [javascript-tutorial/en.javascript.info#2418]
In this article there is a recommendation
> We recommend wrapping your code block with curly braces {} every time you use an if statement, even if there is only one statement to execute. Doing so improves readability.

and next [article](https://javascript.info/logical-operators) there is an example snippet
```
let x = 1;
if (x > 0) alert( 'Greater than zero!' );
```
these two articles conflict with each other.

And also [airbnb style guide](https://github.com/airbnb/javascript#blocks) allows one line IF statements.

**Comment by iliakan** [comment]
Surely, for any style solution, there's a style guide with it =)

Nothing is set in stone.

**Comment by lumosmind** [comment]
but javascript.info's artciles conflict with each other. one of them says use curly braces and another one does not use.

**Comment by iliakan** [comment]
That article rewrites a && B into if (a) B.

I don't use curly braces to make the similarity as obvious as it can be, that's why.
