### ISSUE TITLE
Typo: 3.1 Debugging in Chrome

### ISSUE THREAD

**Issue by sarscode** [javascript-tutorial/en.javascript.info#2421]
![image](https://user-images.githubusercontent.com/69062301/104045891-83756d80-51df-11eb-97b4-e02bccf2046e.png)

Found a typo, see screenshot: 
> Similar to the previous the “Step” command, . . .  

Instead:

> Similar to the previous “Step” command, . . .

**Comment by iliakan** [comment]
Thanks
