### ISSUE TITLE
Translation PT-BR (Portuguese-Brazilian)

### ISSUE THREAD

**Issue by distromari** [javascript-tutorial/en.javascript.info#2439]
ISO/IEC 8859-1

marianamorais(moraismariana83@gmail.com)
mbignotto(matheus.bignottodev@gmail.com)

**Comment by iliakan** [comment]
Right now we, just like Wikipedia, have only one language (PT)
https://github.com/javascript-tutorial/pt.javascript.info

What's good for Wikipedia must be good for us.

How about to join it?

**Comment by lpolon** [comment]
@iliakan is it OK to translate as we would write in portuguease from brazil?

**Comment by iliakan** [comment]
@lpolon Yes, but please try to write in a way that both Brazil and Portuguese people can understand ;)

**Comment by iliakan** [comment]
We follow Wikipedia rule here:

> Portuguese articles can contain variations of writing, as European Portuguese and Brazilian Portuguese have differences in vocabulary and usage. Articles can contain written characteristics of one or the other variant depending on who wrote the article.

**Comment by BM-BrunoMarques** [comment]
I am a native Portuguese Portugal speaker. If you wish we can do some collaboration on this @lpolon @distromari

**Comment by iliakan** [comment]
Closing, hope you worked it out!
