### ISSUE TITLE
Turkish Translate

### ISSUE THREAD

**Issue by bilgedemirkaya** [javascript-tutorial/en.javascript.info#2452]
Hi, I have translated mouse events into Turkish however it has not been reviewed. I want to continue on translating. Could you add me to list? 

https://github.com/bilgedemirkaya

Thanks

**Comment by iliakan** [comment]
@sahinyanlik?
@aliemir?

Are you available?

**Comment by iliakan** [comment]
@bilgedemirkaya Done! Got an invite?

**Comment by bilgedemirkaya** [comment]
Thanks!
