### ISSUE TITLE
Missing an example in 1-js/02-first-steps/11-logical-operators/article.md

### ISSUE THREAD

**Issue by Dorin-David** [javascript-tutorial/en.javascript.info#2455]
Hello everyone. I was reviewing the italian translation of the above [article](https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/02-first-steps/11-logical-operators/article.md) when I've found  (at line 126) the following statement about the OR operator functionality :
*That importance of this feature becomes obvious if an operand isn't just a value, but an expression with a side effect, such as a variable assignment or a function call.*  
The feature is the so called 'short-circuit' functionality. However, no examples follows the above statement. I think it may be confusing for a newcomer (especially considering that the article is quite at the beginning of the tutorial). What about adding a trivial example? Like the following
``
let importantData = {username: 'Admin', password: '*****'}
console.log(importantData = null||importantData) //importantData was not changed
``
We could pick any of the falsy values, of course. I think that a trivial example like the above may help the reader in understanding the meaning of the sentence I quoted. What do you think? 
Best regards,
Dorin

**Comment by iliakan** [comment]
There's an immediate example right below it:

```
    *!*true*/!* || alert("not printed");
    *!*false*/!* || alert("printed");
```

**Comment by iliakan** [comment]
![Uploading image.png…]()
