### ISSUE TITLE
Missing semi collon

### ISSUE THREAD

**Issue by scottyb34** [javascript-tutorial/en.javascript.info#2477]
Your function in the tasking at the end is missing a semicolon after yes(), in the set up and the solution.  Otherwise really enjoying the tutorials and is helping me a ton.  Thank you.

**Comment by MuhammedZakir** [comment]
Which chapter?

**Comment by scottyb34** [comment]
Are sorry, Arrow Functions, the basics.[cid:6c734119-473b-4c57-9d04-4705eecbce48]

Benjamin M Scott
229-630-6700

________________________________

**Comment by MuhammedZakir** [comment]
There are few statements in Arrow Functions article [1] where semi colon is missing. But, I couldn't find the one you mentioned - after `yes()`. Are you sure it is not in a different article?

[1] https://javascript.info/arrow-functions

**Comment by scottyb34** [comment]
Should be the "Task" at the end of Arrow Functions, The Basics<https://javascript.info/arrow-functions-basics>



Benjamin M Scott
229-630-6700

________________________________

**Comment by MuhammedZakir** [comment]
> Should be the "Task" at the end of Arrow Functions, The Basics<https://javascript.info/arrow-functions-basics> Benjamin M Scott 229-630-6700

Found it. Thanks! I will open a pr for this.

**Comment by shreenanda-8** [comment]
#2520
