### ISSUE TITLE
Example in static-properties and methods is wrong

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [javascript-tutorial/en.javascript.info#2479]
In the example  in (https://javascript.info/static-properties-methods)
```
class Rabbit extends Object {
  constructor(name) {
    this.name = name;
  }
}

let rabbit = new Rabbit("Rab");

alert( rabbit.hasOwnProperty('name') ); // Error
```

you mentioned it will return error.  However it is returning true.  
Please find the output here
[Link To Code Here](https://www.typescriptlang.org/play?noImplicitAny=false&target=1&jsx=0#code/MYGwhgzhAEBKYCMEEsAu0CmAPVGB2AJjAPIIBWGw6A3gFDTTAD2eEqATgK5VPsAUeMAFsMASmh0GDVAAtkEAHSCR0ALzRlGANz1oAX1oHaIDOnaIU6dXgwB3OBbR8ARPATPRO2mBPtUfaHMkNAUZSGJbPAAFdiYABww-AE8+AHJNVPFPaCA)

Please let me know in case I am missing anything.

**Comment by vsemozhetbyt** [comment]
I think there are no errors because your code is transpiled. If you run this code as is, you wil get:

```
Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
```

**Comment by aditya-padhi-kbl** [comment]
I agree.  Just checked you are correct.
https://jsbin.com/gatawagupa/edit?js,console

I am not sure whether I should practice code with Typescript or not.
