### ISSUE TITLE
using setAtribute(name, value ) to specify an entity code as the value

### ISSUE THREAD

**Issue by GoldenNerd** [javascript-tutorial/en.javascript.info#2490]
Please answer this question on your article:
Is there a way to use setAttribute(name, value ) to specify an entity code as the value?
Example:
 \<input type="button"  id="my-input" value = "entity-code "\>
to set the entity-code as backspace, using:
setAtribute("value", "\&#x232b;") ;
won't work. 
My solution was to temporarily change my html code to:
\<input type="button"  id="my-input" value = "\&#x232b; "\>
I then use some javascript code to console.log the result of myInputBtn.getAtribute("value") to the console. 
I then copy the symbol that was printed on the console and pasted it as the value of the setAtribute() method as below:
setAtribute("value", "pasted-symbol") ; 
It worked for me,  but I guess there must be a better way.

**Comment by iliakan** [comment]
Not a tutorial issue, sorry for not answering.
