### ISSUE TITLE
Cookies, document.cookie setCookie max-age

### ISSUE THREAD

**Issue by Tealk** [javascript-tutorial/en.javascript.info#2491]
Hello,

I am trying to save a cookie for 30 days, but whenever the cookie is created, it only lasts until the end of the session.
I use this function: https://javascript.info/cookie#appendix-cookie-functions
`setCookie('CookieConsent', 'DoNotTrack', { 'max-age': 2592000 });`

**Comment by iliakan** [comment]
Just checked. Works for me.
