### ISSUE TITLE
Quick Question: Website Template

### ISSUE THREAD

**Issue by bdaley** [javascript-tutorial/en.javascript.info#2497]
Apologies if this is the wrong place for this question, but I was just wondering what template (if any) you are using for the website design. 

I'm a huge fan of the layout and UI controls/components. It reminds me a little bit of Gitbook, but much better.

**Comment by iliakan** [comment]
@Bezart, these compliments are for you, I guess 😊

**Comment by iliakan** [comment]
Custom-made by our best chief-designer @Bezart
