### ISSUE TITLE
typo in data-types, Arrays, last task

### ISSUE THREAD

**Issue by Dorin-David** [javascript-tutorial/en.javascript.info#2501]
link: https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/05-data-types/04-array/10-maximal-subarray/task.md

In the last task, there is a snippet of code where two comments are missing the comment tag.

**Comment by Akash2002** [comment]
I am unsure what you mean. Everything seems fine according to the [website](https://javascript.info/task/maximal-subarray). If there is really an issue, please feel free to elaborate. Thank you!
