### ISSUE TITLE
Urdu translation for Pakistanis and Indians

### ISSUE THREAD

**Issue by realshoaib** [javascript-tutorial/en.javascript.info#2510]
As I've learnt a lot from "javascript.info", I'm excited to contribute to the Pakistani and Indian community through helping to translate this useful site in Urdu. Collaborate and cooperate everyone from the sub-continent. And the loved maintainer team, let me know ASAP.

**Comment by iliakan** [comment]
Which language is it?

**Comment by realshoaib** [comment]
I don't know the code for Urdu as it wasn't given on "javascript.info".
Kindly create some code for Urdu and provide it's translation as well.

**Comment by iliakan** [comment]
Ready! Got an invite?
