### ISSUE TITLE
Problem with payment by PayPal

### ISSUE THREAD

**Issue by kamil-kielczewski** [javascript-tutorial/en.javascript.info#2517]
Hi, I try to buy PDF JS Modern Tutorial (18$)  but I have following error on PayPal - here is screenshot:

https://imgur.com/HaSzpVc

We se there messages:

1. ИП Кантор Илья Александрович

2. Niestety, w tej chwili nie możemy sfinalizować tego zakupu
3. Transakcja została odrzucona ze względu na wymóg spełnienia przepisów prawnych.

English translation for 2 & 3 is:

2. Unfortunately, we are unable to complete this purchase at this time
3. The transaction was rejected due to legal requirements.

I try to pay from POLAND. Any idea?

**Comment by iliakan** [comment]
Can you please try Stripe?

**Comment by iliakan** [comment]
Closing it as possibly resolved, let me know if it's not so.

P.S. Paypal has issues indeed ;(
