### ISSUE TITLE
test error message with "Create new Calculator"

### ISSUE THREAD

**Issue by petzi53** [javascript-tutorial/en.javascript.info#2518]
I've got a test error message in the plunker sandbox with the task [Create new Calculator](https://javascript.info/task/calculator-constructor). The error message appears after the program has returned all values correctly. 

If I change my variable names to the same name as in test.js ('a' and 'b'), there is no error.

I have prepared a screenshot and a [public plunk](https://plnkr.co/edit/S31Nk7xmUNC0DazZ).

![test-error-message](https://user-images.githubusercontent.com/24394304/111030289-984dc780-8401-11eb-93c1-069f22ed600c.png)

**Comment by iliakan** [comment]
Here's the correct solution: https://plnkr.co/edit/JLQ5r3ENdvM5Mwyi

Also, no need to run calculator (lines 23 and below), the tests do that.
