### ISSUE TITLE
elem.onlick() without selector in example

### ISSUE THREAD

**Issue by CreaTorAlexander** [javascript-tutorial/en.javascript.info#2521]
https://javascript.info/introduction-browser-events
```
<input id="elem" type="button" value="Click me">
<script>
  elem.onclick = function() {
    alert('Thank you');
  };
</script>
```

Why there is no need for a selector in the examples?

like `document.getElementById('elem').onclick  ` ?

**Comment by vsemozhetbyt** [comment]
Elements with `id` create properties in the `window` global object with this id. So here `elem` is the same as `window.elem`.

**Comment by CreaTorAlexander** [comment]
Thank you for the explanation, that is good to know.
