### ISSUE TITLE
Image of coffee machine not showing

### ISSUE THREAD

**Issue by ademik** [javascript-tutorial/en.javascript.info#2529]
https://javascript.info/private-protected-properties-methods#a-real-life-example

There's a blank space, after inspecting it, seems like the img element is set to display: none !important;

**Comment by PrashantIndurkar** [comment]
Hi, @ademik 
I think it is now visible. 
sdfdsfsdfsdf
fd
fds
fsd
fsdf
d

**Comment by abhijit-hota** [comment]
It's probably an issue with your ad-blocker. This the same issue with me.

**Comment by iliakan** [comment]
Let me know if I can do anything.

**Comment by ademik** [comment]
@abhijit-hota You're right, it's the ad blocker
