### ISSUE TITLE
Data types count

### ISSUE THREAD

**Issue by OmarioHasan** [javascript-tutorial/en.javascript.info#2544]
In this [Part](https://javascript.info/types#summary) it is mentioned that `There are 8 basic data types in JavaScript.`
in MDN it says that it's 9 [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#data_and_structure_types)

**Comment by iliakan** [comment]
According to the language specification, there is no function type. I believe, that’s MDM-specific treatment of the specification.
