### ISSUE TITLE
ePub Links 

### ISSUE THREAD

**Issue by nguyen-chris** [javascript-tutorial/en.javascript.info#2546]
Hi,

Last night I purchased your ePub/PDF packages and the ePub links do not look right when I viewed.  Please review the attached screenshot and advise.

Thank you and have a great day!

-Chris

![image](https://user-images.githubusercontent.com/26823955/112352714-62320280-8ca1-11eb-9510-44fe6b07d34e.png)

![2021-03-24_12-59-42](https://user-images.githubusercontent.com/26823955/112352667-56464080-8ca1-11eb-8a60-d1c7d0756a6b.png)

**Comment by iliakan** [comment]
Hi,

What's the software that you use to view ePub?
Can you please try iBooks or Calibre?
---
Best Regards,
Ilya Kantor
https://javascript.info

**Comment by joaquinelio** [comment]
Odd:

I see the Freda+ reader logo there
I had the same issue (wrong fields) with Bazaar reader free from windows store (who knows, could be the same code...) 
Then I installed Calibre from its web site, 

Now Calibre & Bazaar are working fine.
It looks like it was an app issue, solved in my case.

**Comment by iliakan** [comment]
Yes, epub readers are not very compatible, unfortunately.
