### ISSUE TITLE
6 1 cookie article - samesite option

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/en.javascript.info#2560]
6-1-cookie article lines 250-255 "samesite" option

I would drop "2017" being prehistoric, but I wouldn't be comfortable with the result
it's security, not ugly formats

What about Opera Mini? is tracking attention and caniuse says it does not support it
https://caniuse.com/same-site-cookie-attribute

**Comment by iliakan** [comment]
I'd keep 2017, people still have old PCs, you know :/

**Comment by joaquinelio** [comment]
> I'd keep 2017, people still have old PCs, you know :/

hey, 
this very notebook is from 2016  🚀  (w10 & linux up to date) 
so

1 2017 browser is criminal.  Ok, they may exist.

2 opera mini  (and potentially any future vendor light version) 
 I didnt put PR because I dont know opera mini, maybe is not capable to even run good js and fancy soft at all

**Comment by iliakan** [comment]
Yeah, but people also use IE. Especially in China.

Unfortunately, 2017 browsers are still a thing for some people.

**Comment by iliakan** [comment]
You know, bank software and some other security-related stuff is sometimes really outdated.
