### ISSUE TITLE
How does ?? produce mistakes?

### ISSUE THREAD

**Issue by lumosmind** [javascript-tutorial/en.javascript.info#2563]
> The limitation is surely debatable, it was added to the language specification with the purpose to avoid programming mistakes, when people start to switch from || to ??.
from: [nullish-coalescing-operator](https://javascript.info/nullish-coalescing-operator#comparison-with)

How can it be possible to produce mistake while changing `||` to `??` . There is not any other operator between their precedence order.

> 

Precedence | Operator type | Associativity | Individual operators
-- | -- | -- | --
7 | Logical AND (&&) | left-to-right | … && …
-- | -- | -- | --
6 | Logical OR (\|\|) | left-to-right | … \|\| …
5 | Nullish coalescing operator (??) | left-to-right | … ?? …

from : [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table)

**Comment by iliakan** [comment]
Maybe you'd better look for reasons and ask at the forum https://es.discourse.group/ ?

I have my guesses, but may be wrong :/

**Comment by joaquinelio** [comment]
better to mention it here:
#2836 ?
