### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by wuyudi** [javascript-tutorial/en.javascript.info#2576]
https://github.com/javascript-tutorial/en.javascript.info/blob/master/6-data-storage/02-localstorage/article.md#strings-only

```js
sessionStorage.user = {name: "John"};
alert(sessionStorage.user); // [object Object]
```

Is there  `localStorage` instead of `sessionStorage` ? Since `sessionStorage` appear in the epilogue.

**Comment by joaquinelio** [comment]
methods are the same

I wouldn't bother changing (and test plunker) them, because
maybe the author could prefer to relocate them:
 
local...
session...
in common...

**Comment by wuyudi** [comment]
Got it. Thanks for such a nice tutorial.

**Comment by joaquinelio** [comment]
> Got it. Thanks for such a nice tutorial.

Hey, just my opinion (I usually put issues like yours); the real creators may differ... 
The issue is valid, and Ilya may want to fix it.

I just pointed that the solution depends on the author's taste
so fixing examples by us could be a waste of time in this particular case

**Comment by wuyudi** [comment]
Ok, I reopen this.

**Comment by iliakan** [comment]
Fixed, thanks!
