### ISSUE TITLE
Portuguese translation for brazilians

### ISSUE THREAD

**Issue by filipespadetto** [javascript-tutorial/en.javascript.info#2587]
Greetings, @iliakan and team.

I'd like to contribute with you translating all the material in javascript.info to Brazilian developers.
The pt.javascript.info repository and is uncompleted. I can collaborate on extending the JavaScript for Brazilians.

P.S.: as the Portuguese/Brazilian language is different from Portuguese/European and has its peculiarities would interesting to create another repository like BR. Feel free to get in touch with me and visit my repository.

Regards, @filipespadetto.

**Comment by iliakan** [comment]
Wikipedia has a single PT version, both for EU/Portuguese and Brazil. 
What's good for Wikipedia should be good for us =)

Just please try to write in a way that both PT/EU and PT/BR people understand.
