### ISSUE TITLE
Suggestion: highlight the difference between function parameters and arguments

### ISSUE THREAD

**Issue by Shamann** [javascript-tutorial/en.javascript.info#2590]
[Parameters](https://javascript.info/function-basics#parameters):

> We can pass arbitrary data to functions using parameters (also called function arguments) .

Strictly speaking, there is a subtle difference between function parameters and arguments, which, perhaps, should be mentioned:
* https://developer.mozilla.org/en-US/docs/Glossary/Parameter
* https://codeburst.io/parameters-arguments-in-javascript-eb1d8bd0ef04

**Comment by iliakan** [comment]
Hopefully fixed.

**Comment by KLaurence** [comment]
Sadly not fixed. The latest commit in [the Functions file](https://github.com/javascript-tutorial/en.javascript.info/blob/6ab384f2512902d74e4b0ff5a6be60e48ab52e96/1-js/02-first-steps/15-function-basics/article.md) is from April 10, which is a typo fix.

**Comment by iliakan** [comment]
Check now.
