### ISSUE TITLE
Fix this bug..

### ISSUE THREAD

**Issue by Manik2375** [javascript-tutorial/en.javascript.info#2594]
Ok, so as you can see due to `position: absolute`  you can't see this when you are offline 
![image1](https://user-images.githubusercontent.com/71554953/116653377-a8673980-a9a4-11eb-8e99-ec253c705abe.png)
 So, you have done `z-index 9999` to fix that..
![Capture](https://user-images.githubusercontent.com/71554953/116653397-b87f1900-a9a4-11eb-8231-14b8c8efa46c.PNG)
so, in order to fix that just add `z-index: -1` in _page-footer_ :point_down: 
![image](https://user-images.githubusercontent.com/71554953/116653465-e19fa980-a9a4-11eb-981a-dd431832255e.png)
And it will be fixed! 
Thank you.

**Comment by iliakan** [comment]
Please tell me more how to reproduce the problem.

**Comment by Manik2375** [comment]
> Please tell me more, how to reproduce the problem?

Ahh with reproduce you mean ?

**Comment by GSemikozov** [comment]
this should be fixed. FYI @iliakan

**Comment by iliakan** [comment]
Thanks!
