### ISSUE TITLE
Translation to Finnish (FI)

### ISSUE THREAD

**Issue by jnsjknn** [javascript-tutorial/en.javascript.info#2597]
List of Maintainers:
- jnsjknn (joonas.jokinen@aol.com)

**Comment by iliakan** [comment]
Sorry for the delay. 
Still want to translate?

What's the language code?

**Comment by jnsjknn** [comment]
@iliakan Sure, no problem. The language code is FI

**Comment by iliakan** [comment]
Created! Invite sent =)
