### ISSUE TITLE
Something wrong in Prototypes, inheritance->F.prototype->Tasks

### ISSUE THREAD

**Issue by marshcat0** [javascript-tutorial/en.javascript.info#2600]
[Link here](https://javascript.info/task/new-object-same-constructor)
At the end, it says 
> At the end, we have let user2 = new Object('Pete'). **The built-in Object constructor ignores arguments, it always creates an empty object, similar to let user2 = {}**, that’s what we have in user2 after all.

but [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/Object) says:
> The Object constructor creates an object wrapper for the given value.
Test in Chrome: 
<img width="281" alt="未命名" src="https://user-images.githubusercontent.com/17940935/118105309-ce61f480-b40e-11eb-867d-704ccf8a5391.png">

**Comment by iliakan** [comment]
That's an interesting point indeed!

I created an issue at https://es.discourse.group/t/the-behavior-of-new-object-value-are-implementations-wrong/789.

Please write if you have any ideas about why's that?

P.S. MDN, with all due respect, is not a language specification.
