### ISSUE TITLE
Minor error in an example

### ISSUE THREAD

**Issue by John-Wheater** [javascript-tutorial/en.javascript.info#2603]
Chrome 90.0.4430.93

OSX 10.15.3

Your PDF page 16:

    If you’re curious to see a concrete
     example of such an error, check 
     this code out:
    ...
    Now if we run the code, only the first
    alert is shown and then we have an error!

Not so with the versions above, the offending lines are just ignored, with no message.

With many thanks for a clear and useful tutorial,

John

**Comment by iliakan** [comment]
Sorry, I'm not getting. What's the error exactly? Please elaborate.

**Comment by John-Wheater** [comment]
Sorry, it's a minor point, but the error (at the point of the quoted text)
is only reported if you've loaded the console, and the beginner has not
been told of this.

Do close it if you don't feel this matters.

**Comment by iliakan** [comment]
Thanks, I changed the text, could you please read it now?

**Comment by iliakan** [comment]
Here: https://javascript.info/structure#semicolon

**Comment by John-Wheater** [comment]
I looked at your github note on this 'issue', and downloaded the pdf using
the link you sent earlier.  The new file is a little bigger, but does not
contain the text "it may also be hidden".  The text I first drew attention
to is unchanged.

I really regret raising this trivial point, especially as I now see that
you do mention the console in the Introduction.

If you're still interested, the best thing would be to put something like

    "you won't see the error message unless you have loaded the console,
     see page xx".

I'm still curious to know what the change is in the new pdf.

**Comment by iliakan** [comment]
The PDF will be updated with the new text on the next rebuild.   

I don’t menton the console because beginners don’t know this word yet, so I just mention that the error can be hidden.

Best regards,
Ilya Kantor

> 17 мая 2021 г., в 10:07, John-Wheater ***@***.***> написал(а):
> 
> ﻿
> I looked at your github note on this 'issue', and downloaded the pdf using
> the link you sent earlier. The new file is a little bigger, but does not
> contain the text "it may also be hidden". The text I first drew attention
> to is unchanged.
> 
> I really regret raising this trivial point, especially as I now see that
> you do mention the console in the Introduction.
> 
> If you're still interested, the best thing would be to put something like
> 
> "you won't see the error message unless you have loaded the console,
> see page xx".
> 
> I'm still curious to know what the change is in the new pdf.
>

**Comment by John-Wheater** [comment]
But you yourself give an excellent introduction to the console in the Introduction.

And, do we normally get notified of new builds?  I ask because the pdf I downloaded (from  https://javascript.info/download/1ptav5g/tutorial.zip.)
differs from the one I downloaded 5 days ago.

Finally, I shall not comment further on this issue.  But if you would like to see any other minor comments, please give me an email where they could be sent.

**Comment by iliakan** [comment]
Thank you for your comments, I highly appreciate them.

I added a note about the console, and also rebuilt the PDF version.

Please create an issue, whether you notice other places for improvements.
