### ISSUE TITLE
Multiple Ternary Operator explanation is wrong 

### ISSUE THREAD

**Issue by codeitram** [javascript-tutorial/en.javascript.info#2607]
On this [page](https://javascript.info/ifelse#multiple) there is example for multiple ternary operator, which assumes it to be left associative and explains it in the same way, but in reality it's right associative so the explanation is wrong. Here is [mdn reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator).

**Comment by iliakan** [comment]
I just checked, the example behaves exactly as intended.

If the explanation is wrong, please send a PR to fix it. It would be very welcome!

**Comment by iliakan** [comment]
Please also take a look at: https://plnkr.co/edit/tYAEm7pMVsN7rC08

If the execution goes right-to-left, then `alert(1)` would be executed, but it's not.

**Comment by codeitram** [comment]
Yeah that's correct. I got confused in associativity, order of evaluation and I treated ternary as some sort of arithmetic operator rather than conditional. There is no issue in explanation, it's fine.
