### ISSUE TITLE
'U+20331' should be '𠌱' instead of '佫'

### ISSUE THREAD

**Issue by moposx** [javascript-tutorial/en.javascript.info#2608]
In [5.3 Strings, section "Special characters"](https://javascript.info/string#special-characters), the code comment says:
```javascript
alert( "\u{20331}" ); // 佫, a rare Chinese hieroglyph (long Unicode)
```
But `U+20331` is actually "𠌱" which is in CJK Unified Ideographs Extension B block (Hanazono font is required to be installed to display this character correctly), instead of "佫" which is not that uncommon and is in Unicode BMP.

Here is a screenshot of it grabbed from <http://unicode.org/charts/PDF/U20000.pdf>

![Screenshot_20210525_135929](https://user-images.githubusercontent.com/15135544/119446855-a7d28080-bd61-11eb-9fc7-8b46700122ea.png)

**Comment by iliakan** [comment]
In the hexadecimal system, 20331 is 4f6b.

Here's the correct UTF page: https://www.fileformat.info/info/unicode/char/4f6b/index.htm
