### ISSUE TITLE
Permission to become maintainer of Georgian version.

### ISSUE THREAD

**Issue by 109149** [javascript-tutorial/en.javascript.info#2609]
@iliakan, Hi. I see that there is no progress in Georgian translation version, so I would like to become maintainer of https://github.com/javascript-tutorial/ka.javascript.info and help to speed up translation process.

**Comment by iliakan** [comment]
Changed your mind?

**Comment by 109149** [comment]
I think it will be time consuming, but I guess I will manage some time. So, can I still get permission? I've re-change my mind xd.

**Comment by iliakan** [comment]
Done!

**Comment by 109149** [comment]
Great, thank you.
