### ISSUE TITLE
Not in "binary form"

### ISSUE THREAD

**Issue by 109149** [javascript-tutorial/en.javascript.info#2617]
[File](https://github.com/javascript-tutorial/en.javascript.info/blob/master/4-binary/03-blob/article.md)
```javascript
// create Blob from a typed array and strings
let hello = new Uint8Array([72, 101, 108, 108, 111]); // "Hello" in binary form

let blob = new Blob([hello, ' ', 'world'], {type: 'text/plain'});
```

Comment says `// "Hello" in binary form`, but it's not binary but ASCII instead.

**Comment by iliakan** [comment]
It's char codes for "Hello". I'm assuming UTF here, but you may think of it as of ASCII if you want.
