### ISSUE TITLE
Outdated info about Microsoft Edge JavaScript engine

### ISSUE THREAD

**Issue by AhnafAhamed** [javascript-tutorial/en.javascript.info#2625]
[article link](https://javascript.info/intro)

> Different engines have different “codenames”. For example:
> V8 – in Chrome and Opera.
> SpiderMonkey – in Firefox.
> 
> …There are other codenames like “Chakra” for IE, “ChakraCore” for Microsoft Edge, “Nitro” and “SquirrelFish” for Safari, etc

.

This statement is false since Microsoft Edge is using the v8 engine since January 15, 2020.

[reference](https://github.com/chakra-core/ChakraCore/issues/5865)

**Comment by iliakan** [comment]
Fixed. Thanks.
