### ISSUE TITLE
The examples for "consts" on variables page should be hard to remember

### ISSUE THREAD

**Issue by lawki** [javascript-tutorial/en.javascript.info#2634]
On this [page](https://javascript.info/variables), it says that 

"use constants as aliases for difficult-to-remember values that are known prior to execution"

but the examples are about how to write red, green or blue in hex format. These are primary colors. So the examples should be chosen so as they're made up of primary colors e.g. magenta, purple or any other combination that is hard to remember.

**Comment by iliakan** [comment]
```
const COLOR_ORANGE = "#FF7F00";
```

Hard enough for me :/

**Comment by lawki** [comment]
Maybe I did't explain better.

> const COLOR_ORANGE = "#FF7F00";

is hard to remember, however following example const declarations aren't really hard to remember.

>const COLOR_RED = "#F00";
const COLOR_GREEN = "#0F0";
const COLOR_BLUE = "#00F";


In place of these three examples, maybe we can give an example of ACCENT_COLORS/ THEME_COLOR etc. that are made up of a combination of Red, Green and Blue like `COLOR_ORANGE` itself.

e.g.

> APP_SECONDARY_COLOR = "#EFACDD";
APP_THEME_PRIMARY = "#99ACFE";
WINE_RED = "#C30E0E";

**Comment by iliakan** [comment]
I believe, the article is clear enough, as it is =) I hope you agree, people have no understanding problem there.

**Comment by lawki** [comment]
@iliakan  It's a 50/50 in my opinion. The wordings and concepts are fine, but the examples are not good enough.

Declaring `const RED="#F00"`(let's say type-1) and `const BG_COLOR="#F00"`(type-2) are different. 
People can and have taken the 1st type of declaration to mean that they have to hard code RED color when they should be defining it as that color is used e.g. if it's  background color i.e. type-2 declaration.

I've had people referring to this documentation to justify why type-1 declaration is fine. But I frankly I think variables should be defined how they going to be used and not what they are.

**Comment by iliakan** [comment]
It's ok to use type-1 declaration. I've seen that many times.

Making a const for a complex color is fine.

**Comment by lawki** [comment]
I myself have seen type-1 declaration many times. But that doesn't necessarily make it better.

If I wanted to change a theme colour for a website then type-1 will be more error prone -

1. Besides being used a theme colour, `RED` might be used somewhere else in the code as well.
2. If I needed to update theme colour I'd need to find all instances of `RED` where it's used as theme. If I miss one instance or mis-identify an instance, then that would be a bug.
3. Finding all instances of `RED` and modifying it will take more time compared to type-2 declaration because in a typical JS project, its usage will be across multiple files.

If I use type-2 declaration then I just have to update it at one place.

`const THEME_COLOR="#ABC";`

to

`const THEME_COLOR="#DEF";`

and it'll affect everywhere, by changing it at one place.

**Comment by iliakan** [comment]
How about `const THEME_COLOR = COLOR_RED` ?

**Comment by lawki** [comment]
I'd prefer `const THEME_COLOR = "#F00";`

defining `const RED="#F00"` is like defining `const TWENTY=20`; it's not useful, it's just redundant.

**Comment by lawki** [comment]
@iliakan that was just my thought. What do you think of defining `const TWENTY=20;`?

**Comment by iliakan** [comment]
@lawki sorry I have no further comments.
