### ISSUE TITLE
Mention performance concerns of CSS animations on properties other than opacity and transform

### ISSUE THREAD

**Issue by ZYinMD** [javascript-tutorial/en.javascript.info#2652]
The CSS `opacity` and `transform` properties are the only 2 best candidates for animation, because they don't trigger repaint. All other properties are less performant. Many articles talk about this fact, for example [this one](https://web.dev/animations-guide/#triggers).

In many examples and tasks in `7-animation/2-css-animations`, properties like `left` or `height` are being animated. They're fine being examples, but I think it'd be great if we could mention that they can usually be replaced by `transform: translate` and `transform: scale`.

**Comment by iliakan** [comment]
That'd be a good note. Could you propose a PR please?

**Comment by ZYinMD** [comment]
Sure I could try.
