### ISSUE TITLE
Destructuring is not explained but used in lesson 5.9

### ISSUE THREAD

**Issue by squivix** [javascript-tutorial/en.javascript.info#2658]
The syntax in the Transforming objects example of lesson 5.9 confused me. So I googled it and it uses [Destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) which was not covered in the tutorial up to that point. Maybe add a footnote explaining it in a previous lesson?
EDIT: I just noticed it's covered in the very next lesson. Maybe don't use it in that example then. Closing issue.

**Comment by iliakan** [comment]
@squivix why did you close it? I fixed the text.

**Comment by squivix** [comment]
Because I have no idea what I'm doing lol. New to the platform.
