### ISSUE TITLE
Serbian translation - cyrillic script

### ISSUE THREAD

**Issue by Vojnuk** [javascript-tutorial/en.javascript.info#2659]
Hello, 
I know there is already a [serbian translation](https://github.com/javascript-tutorial/sr.javascript.info), but it's written in Latin script. I recently joined there, might also become a maintainer as the last commit from @joannaaldebaran was six months ago, so she is probably not active.

I don't know if there is some kind of feature to switch between Latin and Cyrillic script, if not, it's better to start a new repository.

Lang code: sr, but sr-Cyrl or sr-cyrl is better for categorization ( [ISO_15924](https://en.wikipedia.org/wiki/ISO_15924) )
Maintainer: Vojnuk martel.gillgames@gmail.com

**Comment by iliakan** [comment]
I guess, we should use only 1 script for the translation. Which one is mostly used?

**Comment by Vojnuk** [comment]
Nobody has an answer :). Looking country and people culturally then probably Cyrillic, but wherever market interest is more important then probably Latin (because of some ex-Yu countries). So when we take a look at books about programming then it's mostly if not all in Latin script.

Anyway, you can guess my preference :). Partly, my motivation for translating stems from the above-mentioned lack of resources on Cyrillic, the other part is that I learned a lot thanks to this tutorial.

**Comment by iliakan** [comment]
Does everyone understand both cyrillic and latin?

**Comment by Vojnuk** [comment]
Yes, language used is completely same, so it's just preference.

**Comment by Vojnuk** [comment]
And of course, both scripts are used interchangeably.

**Comment by Vojnuk** [comment]
A little from more official side taken from [Serbian Cyrillic alphabet - Wikipedia](https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet):

> In Serbia, Cyrillic is seen as being more traditional, and has the official status (designated in the Constitution as the "official script", compared to Latin's status of "script in official use" designated by a lower-level act, for national minorities). It is also an official script in Bosnia-Herzegovina and Montenegro, along with Latin.

We learn both scripts in school, so in reality it's preference of individual. Some like one, some other, some don't care. So it would be really lovely if we could have both scripts :). There are probably some tool for converting  from one to another, and anyway it won't be problem to keep booth repos in sync.

**Comment by iliakan** [comment]
There's some already translated files. Will we junk them?

**Comment by Vojnuk** [comment]
Are there really no option for creating new repo for "sr-Cyrl"  and leaving the old  "sr" one for Latin unchanged?  Also, if I might just become the maintainer for "sr" to try keep both repos in sync as much as possible. No need to delete anything.

The positive side with such a solution will be that no one would create new issues about that, also considering great similarities between Croatian, Bosnian, Serbian and Montenegrin languages (which are almost the same but let's not go into that direction :) ) future translators could reuse and adapt content from both scripts whatever is more preferable.

**Comment by iliakan** [comment]
Hi,

I'm concerned about the translation that will be better supported. 
And it seems, Latin is the one, isn't it?

I recall, Crotian uses Latin, and Bosnian also mostly Latin.

**Comment by Vojnuk** [comment]
Ok.

**Comment by iliakan** [comment]
Should I make you the maintainer of the current sr translation?

**Comment by Vojnuk** [comment]
No, I'm not interested anymore. Thank you for your time.
