### ISSUE TITLE
online tutorial-map "show tasks" chkbox behaviour 

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/en.javascript.info#2660]
(Is there a metaserver? I couldn't find the code)

The option is very useful.
But links for the first two task don't work 

Others work ok. I didnt test them all, maybe they are the only 2 failing. I bet.

maybe?
/task/hello-alert path being used by the script instead of opening  task.md
or
Those 2 are the only ones with index.html in the same folder.
I dont know the code, I bet it' justa matter of structure

**Comment by iliakan** [comment]
What's a metaserver? I don't think there's one.

What exactly doesn't work? A screenshot, maybe?

**Comment by joaquinelio** [comment]
1) just kidding, a server over the server... 
I mean, you cant open tutorial-map from local server clon
I really need to stop doing stupid jokes nobody get

2) most tasks links open task.md   I love it!!!
but the first 2 open the index html instead

![image](https://user-images.githubusercontent.com/6558304/123881137-7cbbed80-d91a-11eb-8bda-b03065fb9f2a.png)

the 1st one shows the alert:

![image](https://user-images.githubusercontent.com/6558304/123880831-d4a62480-d919-11eb-8360-b0f8142274ce.png)

**Comment by joaquinelio** [comment]
silly issue
