### ISSUE TITLE
Issue with the alternative of ?? 

### ISSUE THREAD

**Issue by vandana1499** [javascript-tutorial/en.javascript.info#2668]
As written in the article,
    We can rewrite result = a ?? b using the operators that we already know, like this:
    result = (a !== null && a !== undefined) ? a : b;
    
It should not be strict checking(!==) but should be (!=).
For eg,
let res;
res = null ?? 7; // -> 7 
res will be 7 but ideally its undefined .Its not null .Hence null coalescing does not do strick checking.
As we can see below null is not equal to undefined
let check;
console.log(check == null); // true
console.log(check === null); // false
console.log(check == undefined); //true
console.log(check === undefined); //true

**Comment by iliakan** [comment]
We keep things as clear as possible here.
