### ISSUE TITLE
No "hello.js" file in articles/debugging chrome section 3.1

### ISSUE THREAD

**Issue by le-anne** [javascript-tutorial/en.javascript.info#2676]
Hello, I'm currently reading through javascript.info and found that there is no file named "hello.js" and cannot follow along with the session.

https://javascript.info/debugging-chrome

**Comment by vsemozhetbyt** [comment]
Are you opening https://javascript.info/article/debugging-chrome/debugging/index.html ?

![s](https://user-images.githubusercontent.com/10393198/126380163-35ddd879-6c2d-4ff8-b7e8-754b10198ffd.png)
