### ISSUE TITLE
Is `window.onload` really the same as `window.addEventListener('load', ...)` ?

### ISSUE THREAD

**Issue by abitrolly** [javascript-tutorial/en.javascript.info#2678]
https://javascript.info/onload-ondomcontentloaded#window-onload says that `window.onload` is the same as `window.addEventListener('load', ...)`. I though that assigning `window.onload` kills all previous handlers, while `window.addEventListener('load', ...)` keeps them.

**Comment by iliakan** [comment]
It doesn't say "the same".

Also, general even handling is well-discussed in previous chapters.

**Comment by abitrolly** [comment]
@iliakan it literally says "same as", which I guess is equivalent.

![image](https://user-images.githubusercontent.com/8781107/126747517-7d546959-476a-4b7e-af96-67d786a6edbb.png)

**Comment by iliakan** [comment]
Removed the comment.

**Comment by abitrolly** [comment]
Now there is no reference for `window.addEventListener('load', ...)` at all.

**Comment by iliakan** [comment]
Now better?

**Comment by abitrolly** [comment]
Yep. But I would move it out of the comment and mention which way is recommended.

**Comment by iliakan** [comment]
There're no specific recommendations here. The same as for all events. 

One can read the tutorial chapters about events for that.

**Comment by abitrolly** [comment]
If there is no direct pointer, I doubt users would do that, especially those with this keyboard. :D

![image](https://user-images.githubusercontent.com/8781107/126750096-0afb7f9f-6d77-4533-b88c-87309334674c.png)

Part of learning process. Whatever.
