### ISSUE TITLE
markup is troubled !Fix it ⚠️

### ISSUE THREAD

**Issue by siddiqkaithodu** [javascript-tutorial/en.javascript.info#2681]
![IMG_20210726_160208](https://user-images.githubusercontent.com/35549603/126975231-3f37033a-afaf-4b8b-b130-f1415484b88b.jpg)

but now👇

![IMG_20210726_160102](https://user-images.githubusercontent.com/35549603/126975433-b1e9c099-e335-419a-b715-e31516c021c0.jpg)

The markup is not behaving as expected.
I am not familiar with markups so sombody fix it
https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/02-first-steps/06-alert-prompt-confirm/article.md

**Comment by joaquinelio** [comment]
online site looks ok

you are watching the article inside github, it doesn't support nested blocks the way tutorial server does.

**Comment by siddiqkaithodu** [comment]
Ok.
