### ISSUE TITLE
Language change menu cut-out when user selected the Urdu  language

### ISSUE THREAD

**Issue by asif-simform** [javascript-tutorial/en.javascript.info#2699]
![The Modern JavaScript Tutorial 2021-08-17 14-41-40](https://user-images.githubusercontent.com/62657766/129698153-d0129d8a-3be2-4c35-a893-7591d268cc9e.png)
![image](https://user-images.githubusercontent.com/62657766/129698162-1b868a73-1cfe-474c-9396-25a219899e57.png)

When the user changes the language to Urdu the menu moves to the right side. But when re-open the menu it is cut out.

**Comment by iliakan** [comment]
@gsemikozov

**Comment by GSemikozov** [comment]
@iliakan https://github.com/iliakan/javascript-nodejs/pull/1457

**Comment by iliakan** [comment]
Thank you, @GSemikozov!
