### ISSUE TITLE
Articles wrongly numerated in section 2.3

### ISSUE THREAD

**Issue by Float07** [javascript-tutorial/en.javascript.info#2702]
It looks like the articles in the [section 2.3](https://github.com/javascript-tutorial/en.javascript.info/tree/master/2-ui/3-event-details) are wrongly numerated. They go 1,3,4,6,7 and 8, while in the [website](https://javascript.info/) it appears in order, as shown bellow:
![image](https://user-images.githubusercontent.com/39651883/130336755-3fc39810-2668-4d93-8f9a-1b55b85c6e4a.png)

**Comment by iliakan** [comment]
In repo, only relative order matters. We avoid extra renumerations, because those are confusing for translators.
