### ISSUE TITLE
Kazakh Translation

### ISSUE THREAD

**Issue by kenzhemir** [javascript-tutorial/en.javascript.info#2706]
Hey! I would like to start translating tutorial to Kazakh language.

Language code: [kk](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=kk) 
Maintainer: @kenzhemir, kenzhemir@gmail.com

**Comment by iliakan** [comment]
Sorry, missed.

Still enthusiastic?

**Comment by kenzhemir** [comment]
Yes!

**Comment by iliakan** [comment]
Created! Got the invite?

**Comment by kenzhemir** [comment]
Yep, accepted

**Comment by iliakan** [comment]
Good luck!

**Comment by iliakan** [comment]
Open the issue in case of any problems with the translation.
