### ISSUE TITLE
A suggested improvement for the range checking exercise

### ISSUE THREAD

**Issue by KutanaDev** [javascript-tutorial/en.javascript.info#2709]
Here's the [range checking exercise](https://javascript.info/logical-operators#check-the-range-between).

The solution suggests code that looks like this…

` if (age >= 14 && age <= 90)`

…but I think it would be clearer to express it like this…

` if (14 <= age && age <= 90)`

…because the min and max values are at the left and right hand ends of the expression and the `age` value lies within the range bounded by min and max.

**Comment by iliakan** [comment]
Sorry, don't think so.
