### ISSUE TITLE
Duplicate diagrams

### ISSUE THREAD

**Issue by KutanaDev** [javascript-tutorial/en.javascript.info#2713]
On this page, in the Internal Algorithms section,
[https://javascript.info/garbage-collection](url)
the _same_ diagram appears more than once, with a different title each time. Surely each diagram should only appear once?

**Comment by iliakan** [comment]
Can you provide a screenshot please?

Best regards,
Ilya Kantor

**Comment by KutanaDev** [comment]
My mistake, the diagrams are different; I just hadn't studied carefully enough.
