### ISSUE TITLE
Content: Missing Number.isFinite and Number.isNaN

### ISSUE THREAD

**Issue by imba-tjd** [javascript-tutorial/en.javascript.info#2714]
https://javascript.info/number

The traditional `isFinite` and `isNaN` have defects that they will firstly convert the value to Number.

ES6 introduced `Number.isFinite` and `Number.isNaN`, which are better.

**Comment by iliakan** [comment]
Closed, not sure about how useful these methods are.

**Comment by imba-tjd** [comment]
```
isFinite("15")  // true
Number.isFinite("15") // false

isNaN("str")  // true
Number.isNaN("str")  // false
```

If you prefer == than ===, then you have the reason to say it's not useful.

**Comment by iliakan** [comment]
Theoretically, there's the difference. In real code, I never ever saw these new methods.

After some search on github.com, I also have such impression.

**Comment by imba-tjd** [comment]
🆗 it's up to you
