### ISSUE TITLE
Number.isNaN() should be preferred instead of isNaN()

### ISSUE THREAD

**Issue by princeraju** [javascript-tutorial/en.javascript.info#2715]
Issue link: https://javascript.info/number#tests-isfinite-and-isnan

From MDN (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN) :
"The isNaN() function determines whether a value is NaN or not. Because coercion inside the isNaN function can be surprising, you may alternatively want to use Number.isNaN()."

**Comment by iliakan** [comment]
Maybe, but I don't think that's really beneficial to know :/

**Comment by joaquinelio** [comment]
what about the smartheader few lines below,  object.is() for edge cases.
this could be one

isNaN("nonumeric") = true
Number.isNaN ("nonumeric")= false
Objet.is(NaN, "nonumeric") = false

**Comment by joaquinelio** [comment]
just bringing to atention,
you know better than anyone the right criteria :)

**Comment by iliakan** [comment]
This is a pretty rare method.

About very rare methods, I’m not sure we should include them into the book.

Best regards,
Ilya Kantor

**Comment by iliakan** [comment]
Closing for now.
