### ISSUE TITLE
Currying example is not correct

### ISSUE THREAD

**Issue by madeindjs** [javascript-tutorial/en.javascript.info#2722]
In [Currying section](https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/99-js-misc/03-currying-partials/article.md), we have an example with the following logger:

~~~js
const {curry} = require('lodash');

function log(date, importance, message) {
  alert(`[${date.getHours()}:${date.getMinutes()}] [${importance}] ${message}`);
}

const logCur = curry(log);

let logNow = logCur(new Date());
~~~

But `logNow` is wrong because `new Date` is evaluated only once. So if I try to log each minutes, I got same log:

~~~js
setInterval(() => logNow('INFO', 'message'), 60_000);
// => [9:15] [INFO] message
// => [9:15] [INFO] message
// => [9:15] [INFO] message
// ...
~~~

**Comment by joaquinelio** [comment]
setInterval

**Comment by iliakan** [comment]
This behavior is explicitly mentioned and explained.

**Comment by iliakan** [comment]
P.S. read the first commend above `logNow`.

**Comment by madeindjs** [comment]
@iliakan , I undesrstood that behavior is explained but IMO:

- `logNow` naming is confusing because it display a past date(not "now")
- this is not a good example of usage because this is useless in real script

What do you think about this sample to demonstrate usability of currying:

~~~js
const {curry} = require('lodash');

function log(name, importance, message) {
  const date = new Date();
  alert(`[${date.getHours()}:${date.getMinutes()}] [${name}] [${importance}] ${message}`);
}

const curryLogger = curry(log);

const defaultErrorLogger = curryLogger('default')('ERROR');
defaultErrorLogger('An error occur');
// => [17:37] [default] [ERROR] An error occur

const applicationDebugLogger = curryLogger('app')('DEBUG');
applicationDebugLogger('Hello world');
// [17:39] [default] [DEBUG] Hello world
~~~

**Comment by iliakan** [comment]
The concept of error logger may be unknown to people.

It's a good example for people who got used to error levels etc, but not to those new to such thing.
