### ISSUE TITLE
Psychological perception of the example "Unreachable Island" of the textbook

### ISSUE THREAD

**Issue by Wulf305** [javascript-tutorial/en.javascript.info#2727]
Good afternoon. I apologize in advance, but I think that the example with the deletion of the concept of "family" in the paragraph "memory management" in the textbook is incorrect. Language is not only a way of describing data and a way of information exchange, language, first of all, is a way of thinking of the one who uses it. A programmer studying JS calmly accepts such an example, for the brain it is marked as normal, then the habit of this representation begins with common logic, i.e. there is a process of organizing neurons in such a way that they are combined into stable chains according to concepts, at the same time it turns out that such an example, perceived, is correctly imprinted by the brain, summing up with the neural cloud of ideas about the family. Is there any way you can change "family" to something else?

**Comment by iliakan** [comment]
What exactly is wrong?

**Comment by iliakan** [comment]
There's a concept of the family in most societies, as of now.

Some people accept same-gender families, some do not.

Some people accept families of more than two, some do not.

Here, on this site we have a particular example of a family, that is accepted most widely.

**Comment by Wulf305** [comment]
What I mean is that it demonstrates that removing the concept of "family" is a normal process.

**Comment by iliakan** [comment]
As a programmer, I would never think this way.

In programming we often manipulate on data, including people. 

When `family = null`, it means we remove the variable content, not the concept.

I hope that people, by the time they get to read this, will solve some tasks and their brains will adapt enough to programming. 

When I write `user = null` (that I do quite often!), it doesn't mean I'm remove a concept of users.

**Comment by iliakan** [comment]
When I write `cart = null`, it doesn't remove a concept of a product cart from my head and heads of all the other people who  read my code.

**Comment by Wulf305** [comment]
This is true, but it is obvious only for the logical layer of the brain. The human brain consists of three conditionally existing layers: logical, emotional and reflex. At the same time, only two of them work at the same time (Mark Goulston, Just Listen). For the brain, given the existence of such an example and the presence of an attribute of acceptability, it does not matter that it is not associated with the life of society, it will replace the attribute in this sense as well.

**Comment by Wulf305** [comment]
The brain works as an adder, it does not know the reaction of itself to the information that it processes, with multiple use of a site, the brain summarizes similar areas. To our regret, the younger generation perceives information differently than we do, and the process of processing it takes less time, so such an example in the future may lead to unforeseen consequences.
