### ISSUE TITLE
Applying for the position 'Maintainer' at bn.javascript.info

### ISSUE THREAD

**Issue by mrpmohiburrahman** [javascript-tutorial/en.javascript.info#2730]
Hi,
I think the number of maintainers should increase as we can see that there are [40 PR's](https://github.com/javascript-tutorial/bn.javascript.info/pulls) need to be reviewed ( starting from 26 April ).
That's why I am applying to be one of the Maintainers on the repo [bn.javascript.info](bn.javascript.info).

Also, in this month, [Hactober Fest](https://hacktoberfest.digitalocean.com/) is happening and I want to use this opportunity to inspire others to contribute to that repo.

**Comment by iliakan** [comment]
Ok, you're invited to join.

Please give up hacktoberfest. We tried a year ago, all commits were such crap. Not worth time spent.
