### ISSUE TITLE
cut, copy, paste events handler issues

### ISSUE THREAD

**Issue by songhn233** [javascript-tutorial/en.javascript.info#2738]
[The cut, copy prevention demo](https://javascript.info/events-change-input#events-cut-copy-paste) failed to show anything for `event.clipboardData.getData('text/plain')`

![image](https://user-images.githubusercontent.com/47357585/136668749-06ef582a-83e6-4f37-9538-f55554ced664.png)

Change the code to the following and it will work

```js
<input type="text" id="input">
<script>
  input.onpaste = function(event) {
    alert(event.type + ' - ' + event.clipboardData.getData('text/plain'));
    return false; // Equal to `event.preventDefault()`
  };
  input.oncut = input.oncopy = function(event) {
    alert(event.type + '-' + document.getSelection());
    return false;
  }
</script>
```

In addition, as mentioned above, `We can also use event.preventDefault() to abort the action`, so `return false` code should be added with a description equivalent to `event.preventDefault()`.

Related issue: javascript-tutorial/zh.javascript.info#956

**Comment by joaquinelio** [comment]
👍 

mdn defines getData for paste only
 
i guess cut/copy falls under "ClipboardAPI: user safety restrictions" below
clipboard may have data from anywhere

**Comment by joaquinelio** [comment]
the original text seems odd, i put a PR 

single change
"Alternatively, the code below also prevents all such events and additionally shows what we are trying to cut/copy/paste:"

I think your code should be added
