### ISSUE TITLE
Wrong example for Basic operators!

### ISSUE THREAD

**Issue by bittnitt** [javascript-tutorial/en.javascript.info#2742]
Hi
In the example here is a mistake
https://javascript.info/operators#chaining-assignments
![IMG_20211011_060339](https://user-images.githubusercontent.com/85654461/136725315-b8fe45b8-43a2-48d9-9b80-dad1d01779b7.jpg)
The equivalent of the first code, for better readability, should be written this way
`c = 2 + 2;`
`b = c;`
`a = b;`
![IMG_20211011_061010](https://user-images.githubusercontent.com/85654461/136725735-b79f18d2-6cc8-43d2-8a16-b894376f3d08.jpg)
The current equivalent is wrong!

**Comment by mikitachyzhyk** [comment]
The current equivalent is definitely not wrong! This is just an example of assignment chaining to better understand how the assignment operator works.

**Comment by bittnitt** [comment]
> The current equivalent is definitely not wrong! This is just an example of assignment chaining to better understand how the assignment operator works.

How is your assignment chain example evaluated?
![IMG_20211011_060339](https://user-images.githubusercontent.com/85654461/136757585-dc237ceb-f05d-457d-ad4d-84e5b8bc4a47.jpg)
First => c = 4 (2 + 2)
Second => b = c 
Third => a = b
it's true?
![IMG_20211011_061010](https://user-images.githubusercontent.com/85654461/136758843-c0e1c55d-3b5b-47bc-b18d-a6280cc1c412.jpg)
Well, then why did you put it this way?
Why does C come twice?
So where did B go?
I hope you understand what I mean :D

**Comment by joaquinelio** [comment]
`273 a = b;`
