### ISSUE TITLE
Confusing Queue image on Event Loop Article

### ISSUE THREAD

**Issue by atakanzen** [javascript-tutorial/en.javascript.info#2772]
Hey, the "macrotask queue" image that is on the "Event Loop" article might confuse the readers regarding the following paragraphs. By taking a look on the arrows on the image and reading the second paragraph on the image that I provided here, this image seems more like a stack rather than a queue. If the tasks were ordered from top to bottom as: `setTimeout` -> `mousemove` -> `script`, it would be much more compatible with the given second paragraph. The current image with the current statement on the article, looks much more like a LIFO rather than FIFO.
<img width="817" alt="Screen_Shot_2021-11-03_at_4 16 42_PM" src="https://user-images.githubusercontent.com/59116264/140090923-5cf2fbcd-3a37-47ec-8794-1e0cf8efc093.png">

**Comment by iliakan** [comment]
There's no way to make this picture non-confusing for everyone. 

Both orders have their proponents.

**Comment by atakanzen** [comment]
What about changing the directions of the arrow? Anti-clockwise instead of clockwise. Because, it still feels that this image is a representation for a stack with the following statement: 

"_When the engine browser is done with the script, it handles mousemove event, then setTimeout handler, and so on._"

**Comment by iliakan** [comment]
Same. I tried, there are always people who think in the reverse direction.
