### ISSUE TITLE
Incorrectly interpreted fenced code blocks

### ISSUE THREAD

**Issue by dejansdev** [javascript-tutorial/en.javascript.info#2779]
https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/02-first-steps/15-function-basics/article.md

Within the chapter "Returning a value" markdown displays:

````smart header="A function with an empty return or without it returns `undefined`" If a function does not return a value, it is the same as if it returns `undefined`:

I failed to discover the reason.

**Comment by joaquinelio** [comment]
It may sound ambiguous  
maybe
"A function without the return command, or a return without an explicit value, returns undefined"
or just
"Without an explicit return value, it becomes undefined "

**Comment by dejansdev** [comment]
The problem is not in understanding the given text. 

The problem is that if you go to a given link, that line of text, as well as everything that comes after it, is not properly formatted in the markdown file.

**Comment by joaquinelio** [comment]
oh!
github dont understand nested md
the site looks ok  https://javascript.info/function-basics
![image](https://user-images.githubusercontent.com/6558304/144470855-600f00a7-a0ed-4a3e-8da8-78dfc13d0e69.png)

**Comment by iliakan** [comment]
Site markdown is a bit richer than github in some aspects. 

Can't see a problem on the site, so closing.
Please reopen if such problem exists!

**Comment by dejansdev** [comment]
So that's up to GitHub. Thanks for the clarification.
