### ISSUE TITLE
promise-chaining article is useless

### ISSUE THREAD

**Issue by gitcnd** [javascript-tutorial/en.javascript.info#2785]
Nobody ever writes production code without .catch()

The article make no use or mention of that whatsoever - and I suspect almost everything in it will not work when you try to incorporate these exceptions.

How do you chain .then() and .catch() and/or .finally() using the same techniques you've shown? Can you?  I suspect not.

Article needs to be re-written to:-

1. Include typical production code scenario (with exceptions)

2. Not use recursive setTimeout silliness - you're trying to teach something here - it makes no sense to rely on an esoteric recursive call for something that nobody would ever do, in order to try and educate us newbies about something else - use a normal situation - e.g. where a web-app calls something XHR to get registration status, which is needs to make decisions with in order to call some action, which it needs to wait on results from to call some other action - all with error handling - etc... you know - SOMETHING REAL.

**Comment by iliakan** [comment]
Read the next article, it's about error handling.

And actually people DO write production code without catch. In case when an error is so fatal that it makes no sense to catch it.

Closed, because the author obviously is in the middle of the tutorial, and complains that everything isn't covered yet.

**Comment by gitcnd** [comment]
The topic intro said this:-

" we have a sequence of asynchronous tasks to be performed one after another — for instance, loading scripts. How can we code it well?

Promises provide a couple of recipes to do that.

In this chapter we cover promise chaining.

It looks like this:
"

Then you inserted an esoteric example based on a quirk of setTimeout()'s without any error handling, which has nothing to do with loading scripts.

And even before that - this page OPENS with this: "Let’s return to the problem mentioned in the chapter Introduction: callbacks: " - and if you go back and look at exactly that, you can see that it handles every result AND EVER ERROR from every load independently.



Please do not unilaterally close this issue without proper consolation, or addressing every problem I mention.

You might be an expert at javascript, but we are not, and it's rare that anyone like us bothers to educate you to your own oversights in the area of EDUCATING US.

First, and most important: You need to NOT USE ESOTERIC and OBSCURE QUIRKS when trying to train us about something.  the repeating nature of a timeOut might be a cool trick, but it has no place in an article about promise-chaining.  Save the tricks for someplace else where smartypants coders might want to go to be amused.

Second - Put a "Previous" or a "Next" button conspicuously on the page.  Google exists these days - nearly everyone visiting your site arrives directly into a page, and a tiny little ">" miles away from the content is never going to get noticed (I'm not the only person with a 32" 4K monitor).

Third - Github issues are not a place for an argument or expressing opinions - they are where people who have found mistakes you've made, get the chance to help you fix them.  Try to understand what we are saying, why we are saying it, what ALL YOUR USERS LIKE US are likely to be experiencing on this same topic/issue, and THINK about what you need to do to fix your problems.  Never argue - you didn't suffer the problem, because you already know the topic - we did, and we took the time to tell you.

"Promise Chaining" is complicated - and in most production situations, error handling is going to be needed (yes, whether or not you can dream up situation when it isn't, and whether or not your boss lets you skip that so users stare at a broken dysfunctional web-app just because their phone switched from 4G to wifi in the middle of something, or whatever).

While I appreciate (now I've been told that there's actual a series to these tings, and the hidden ">" means "next")  that the article "promise chaining" is followed by an article about errors - the problem remains.  There's no actual working examples of real-life promise-chaining with error handling in either of those articles.  (Yes, I see you did partially cover a situation where it's might be OK to catch every error with just one catch - but there's nothing that mirrors the full functionality of your first chapter-intro example, or in general, that offers us insight into how to actually write production-quality chained-promises readably).

Also - I think your concept of "next" is wrong or at least misleading in all your descriptions - .catch() works fine when place *above* the then() - so "first .catch" and "second .catch" might be better wording?  Keep in mind: you're the expert, not me - I just see things I know you did get wrong.
