### ISSUE TITLE
typeof is not a function

### ISSUE THREAD

**Issue by bruce-c-liu** [javascript-tutorial/en.javascript.info#2788]
https://javascript.info/types#type-typeof

It's a common misconception that typeof can be used as a function. It can ONLY be used as an operator.

See below for explanation of what typeof(x) actually means: 
https://stackoverflow.com/questions/2797517/typeof-is-an-operator-and-a-function

**Comment by iliakan** [comment]
I'm sorry to hear that the article causes a misunderstanding here.

Please check the updated version.

**Comment by bruce-c-liu** [comment]
Looks great. Thanks for the hard work!
