### ISSUE TITLE
Correct Options headers

### ISSUE THREAD

**Issue by Manik2375** [javascript-tutorial/en.javascript.info#2793]
[Here](https://javascript.info/fetch-crossorigin#:~:text=A%20preflight%20request%20uses%20the%20method%20OPTIONS%2C%20no%20body%20and%20two%20headers%3A) As you can see, it says `OPTION` have 2 headers, but actually it have 3. [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request#:~:text=It%20is%20an%20OPTIONS%20request%2C%20using%20three%20HTTP%20request%20headers%3A%20Access%2DControl%2DRequest%2DMethod%2C%20Access%2DControl%2DRequest%2DHeaders%2C%20and%20the%20Origin%20header.)

Later yes, it's told that it have 3 headers, but I think why not tell that before also, just for those who are making notes? 

(I might add a PR to get reviewed) :smile:

**Comment by iliakan** [comment]
Will review this now.
