### ISSUE TITLE
Become a maintainer

### ISSUE THREAD

**Issue by mahdiHash** [javascript-tutorial/en.javascript.info#2797]
Hi, @iliakan.
I would like to be a maintainer of [Persian branch](https://github.com/javascript-tutorial/fa.javascript.info) of javascript-tutorial.
@mahdyar is already a maintainer and it would be the best if he tells me his opinion.

**Comment by mahdyar** [comment]
I agree.

**Comment by iliakan** [comment]
Sure! Sorry for the delay. Done!
