### ISSUE TITLE
A typo in https://javascript.info/arrow-functions-basics#multiline-arrow-functions

### ISSUE THREAD

**Issue by atakndogn** [javascript-tutorial/en.javascript.info#2809]
There is a small typo related with comma at the start of the sentence in "As you can, see". It could be corrected with changing the place of comma after "see", IMO.

> As you can, see (a, b) => a + b means a function that accepts two arguments named a and b.

**Comment by arafatjamil01** [comment]
Can you please provide the link of that document.  I am willing to fix this issue for you. But I can't really find it. even after doing a full document search.
