### ISSUE TITLE
Object methods, "this": Missing appropriate tests for chaining exercise

### ISSUE THREAD

**Issue by Omid-Heidarzadeh** [javascript-tutorial/en.javascript.info#2826]
### Article
[Object methods, "this"](https://javascript.info/object-methods#chaining)

There are missing tests for the "chaining" exercise on the "Object methods, this" article to ensure that the showStep method returns this. 

Suggested tests:
 ```javascript
  it('showStep() should return this', function() {
    assert(ladder.showStep(), ladder);
  });

  it('up().up().down().showStep().down().showStep()', function () {
    assert.equal(ladder.up().up().down().showStep().down().showStep().step, 0)
  })
```

**Comment by iliakan** [comment]
Might be good. Make a PR, please?
