### ISSUE TITLE
hotkeys for multiline comments in win10

### ISSUE THREAD

**Issue by 11201010** [javascript-tutorial/en.javascript.info#2830]
In part 1 chapter 2.2 "[Code structure](https://javascript.info/structure#code-comments)", it says:
> In most editors, a line of code can be commented out by pressing the `Ctrl+/` hotkey for a single-line comment and something like `Ctrl+Shift+/` – for multiline comments (select a piece of code and press the hotkey). 

I'm using VSCode in Win10, trying to use multiline comments (`/*...*/`) by pressing `Ctrl+Shift+/`, but it didn't work.

So I go to the VSCode official website and I found the following results:

* [Keyboard shortcuts for Windows](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf)
* [Keyboard shortcuts for Linux](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf)
* [Keyboard shortcuts for macOS](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf)

I've summarized the shortcuts related to comments:

| | Windows | Linux | macOS |
| --- | --- | --- | --- |
| Add line comment | `Ctrl+K` `Ctrl+C` | `Ctrl+K` `Ctrl+C` | `⌘K` `⌘C` |
| Remove line comment | `Ctrl+K` `Ctrl+U` | `Ctrl+K` `Ctrl+U` | `⌘K` `⌘U` |
| Toggle line comment | `Ctrl+/` | `Ctrl+/`  | `⌘/` |
| Toggle block comment | `Shift+Alt+A` | `Ctrl+Shift+A` | `⇧⌥A` |

I've noticed that there's no such hotkeys as `Ctrl+Shift+/`, instead, I found the hotkey for toggle block comment (`Shift+Alt+A`), and it works.

Why? Is it because that `Ctrl+Shift+/` is hotkey for other code editors?

**Comment by iliakan** [comment]
The tutorial specifically talks about a commented "line of code", and the hotkey is correct ;)

About why VS Code has such other hotkeys, really should ask them.
