### ISSUE TITLE
Project property keys can be number, not only string or symbol

### ISSUE THREAD

**Issue by Huthaifah-kholi** [javascript-tutorial/en.javascript.info#2849]
with object chapter at  [https://javascript.info/symbol](https://javascript.info/symbol) at the beginning, we can use numbers as object property keys, not just string or Symbol. as mentioned at the link.

**Comment by mikitachyzhyk** [comment]
Nope. Just try this:
```javascript
let obj = {1: '1', 2: '2', '3': 3, name: 'name'}
for (key in obj) console.log(typeof key)
```

**Comment by Huthaifah-kholi** [comment]
Yes, what I missed is that Javascript converts any non (`string`) key property to `string `implicitly. Just `Symbol `stays `Symbol`.

**Comment by joaquinelio** [comment]
Perfect time to sell Map()
