### ISSUE TITLE
Rewrite Async Task is broken

### ISSUE THREAD

**Issue by takinabradley** [javascript-tutorial/en.javascript.info#2858]
https://javascript.info/async-await
The first task in the following article seems to be broken. Clicking the "open in sandbox" button and running it gives an error other than "Error: 404" before making any changes. It works properly when making changes outside the sandbox or in the console.

The solution I came up with also doesn't yield the expected result within the sandbox, but does outside of it.

Error it throws: 
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

Solution I wrote and works outside of sandbox:
```
async function loadJson(url) {
  let response = await fetch(url)

  if (response.status == 200) {
    return response.json()
  } else {
    alert (new Error(response.status))
  }
}

loadJson('no-such-user.json')
```

Directory this issue concerns:
https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/11-async/08-async-await

**Comment by iliakan** [comment]
Fixed

**Comment by iliakan** [comment]
thanks!
