### ISSUE TITLE
Error in Demo file server.js in WebSocket document

### ISSUE THREAD

**Issue by umakantv** [javascript-tutorial/en.javascript.info#2870]
While going through the [WebSocket](https://javascript.info/websocket) document, I attempted to run the  given [server.js](https://github.com/javascript-tutorial/en.javascript.info/edit/master/5-network/11-websocket/demo.view/server.js) file in Node.js.  
I established the connection and sent a message.
But there was an error `message.match is not a function` which caused the program to close.
I inspected the error, the `message` variable is a `Buffer` object.
I fixed it by converting that into a `String`.

**Comment by iliakan** [comment]
Thank you!
