### ISSUE TITLE
Wrong units @ https://javascript.info/js-animation

### ISSUE THREAD

**Issue by adamnar** [javascript-tutorial/en.javascript.info#2932]
It says: "The callback gets one argument – the time passed from the beginning of the page load in **microseconds**. This time can also be obtained by calling performance.now()."

https://developer.mozilla.org/en-US/docs/Web/API/Performance/now says: "The performance.now() method returns a [DOMHighResTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp), measured in milliseconds."

The units are milliseconds, not microseconds.

**Comment by Rnbsov** [comment]
thank you for your report 👾

**Comment by iliakan** [comment]
Thanks, fixed!
