### ISSUE TITLE
Explanation for why Symbol() constructor does not use "new" operator

### ISSUE THREAD

**Issue by pan-alex** [javascript-tutorial/en.javascript.info#2939]
The Symbol() constructor is introduced in [https://javascript.info/symbol](https://javascript.info/symbol). In the first example a new symbol is declared without the "new" keyword. 

```
// id is a new symbol
let id = Symbol();
```

This would appear to contradict the convention about constructors introduced 2 topics earlier in [https://javascript.info/constructor-new](https://javascript.info/constructor-new).

The explanation provided in the MDN is as follows:

>The Symbol() constructor returns a value of type symbol, but is incomplete as a constructor because it does not support the syntax "new Symbol()" and it is not intended to be subclassed."

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/Symbol)

I don't actually understand what this explanation means (I'm a noob), and it seems like something that I don't need to worry about yet. But I think it would benefit readers like myself to provide an explanation for why the convention isn't followed for the Symbol() constructor.

**Comment by iliakan** [comment]
Added more words about symbols being primitives.
