### ISSUE TITLE
The website is breaking when I zoom it.

### ISSUE THREAD

**Issue by akshayaparida** [javascript-tutorial/en.javascript.info#2943]
Please solve the zooming issue on this website.

**Comment by iliakan** [comment]
Which issue?

**Comment by akshayaparida** [comment]
Sorry sir, for late reply, what happened in April when I zoomed the webpage to read, the side content timeline overlapped with main content. The issue solved within two days, but I just saw your reply today, because I am not active that time much. And I want to Thank You for this great JS website.
