### ISSUE TITLE
Sidebar Navigation doesn't close on mobile

### ISSUE THREAD

**Issue by S-triemer** [javascript-tutorial/en.javascript.info#2946]
On my mobile phone as well as on my tablet the sidebar is overflowing the content of the page and not disappearing.
I'm using the Google Chrome App to access the Site.
![Screenshot_20220411-221416_Chrome.jpg](https://user-images.githubusercontent.com/62814975/162824837-d7556263-73a1-46da-a581-c6987486cfff.jpg)

If you need more Information please let me know.

**Comment by joaquinelio** [comment]
touch hamburger menu icon

**Comment by S-triemer** [comment]
Sorry I just realised that there're two Hamburger Icons. 
The Hamburger that is opening the sidebar is overflowing the content in a way that makes it hard to find though.

![20220412_122430.jpg](https://user-images.githubusercontent.com/62814975/162941739-7d179b06-d5c4-46e3-beb6-e1b27fb3e490.jpg)

![20220412_123006.jpg](https://user-images.githubusercontent.com/62814975/162941772-da549096-999f-431a-b44b-57bda2446e63.jpg)
