### ISSUE TITLE
Improving the format of updated date in Japanese site.

### ISSUE THREAD

**Issue by KenjiI** [javascript-tutorial/en.javascript.info#2955]
Currently, the format of updated date is below's picture, like "2日 一月 2021" in Japanese site.
![image](https://user-images.githubusercontent.com/6941841/163695283-3c7119ad-f80d-4a97-a53c-e0de5e869d25.png)

That format is not easy to read, because
* we are used to using that format as "YYYY年MM月DD日"
* Number and Chinese number are mixed in current format.  "2日 一月 2021" on "一", which is meaning "1"

We'd like to display dates, like "2021年1月2日"

If there is anything I can do, please let me know.
Thank you!

**Comment by iliakan** [comment]
Sure, I'll try to fix it. Do you mean this?

<img width="1212" alt="Screenshot 2022-04-17 at 09 32 48" src="https://user-images.githubusercontent.com/349336/163703536-a4d84dba-02a4-404a-a553-d5bc7471034b.png">

**Comment by KenjiI** [comment]
Thank you! Yes, it’s right there.

**Comment by iliakan** [comment]
I mean, on this picture, is the format correct or not?

**Comment by iliakan** [comment]
Hopefully, fixed ;)
