### ISSUE TITLE
Incorrect tooltip

### ISSUE THREAD

**Issue by smith558** [javascript-tutorial/en.javascript.info#3031]
![image](https://user-images.githubusercontent.com/44023416/171038331-29345c66-132b-45c9-a24d-fd08b062d59b.png)

![image](https://user-images.githubusercontent.com/44023416/171038284-74a5f5c3-d297-4bb2-90de-e8bd7745e150.png)

Should be "Last updated **on** [date]" instead of "Last updated **at** [date]"

**Comment by iliakan** [comment]
Thanks, fixed!
