### ISSUE TITLE
Home page counter bug

### ISSUE THREAD

**Issue by Manik2375** [javascript-tutorial/en.javascript.info#3033]
Hi! It seems like in chrome we are getting a bug in homepage, firefox seems fine 
![image](https://user-images.githubusercontent.com/71554953/171464661-fcaf2b38-2ab0-4ee4-89b7-f50b6f56bf6a.png)

I did a sneak peak, and it looks like every counter is getting same top value perhaps.

Thank you.

**Comment by ericchase** [comment]
![image](https://user-images.githubusercontent.com/30473157/171505839-5546a7e2-21e4-4a51-97fc-906e3d7d72e7.png)

**Comment by ericchase** [comment]
That said. `inline-block` breaks other things. But I believe this issue is specifically due to a bug in chrome when the UL elements are displayed as blocks.

**Comment by ericchase** [comment]
Also note that this issue occurs when the elements are split int columns using the css `columns` property.

The better solution would be to use css grid:
![image](https://user-images.githubusercontent.com/30473157/171506517-c3ee67ee-8c4e-423e-b9a0-60c821658e69.png)

**Comment by ericchase** [comment]
Ok, I've looked very closely, and now it appears that problem happens when using `position: relative;` on the element while using `position: absolute;` on the element's `:before` pseudo-element.

divs made into columns using css `columns`:
![image](https://user-images.githubusercontent.com/30473157/171515858-eac0e20a-8bbd-4d49-bc3e-563305c67272.png)

---

the corresponding dom:
![image](https://user-images.githubusercontent.com/30473157/171515869-959dfea6-029c-4ca2-951b-0147415f662b.png)

---

the culprit:
![image](https://user-images.githubusercontent.com/30473157/171515878-af0c8ec2-259e-4af8-afa4-e8e3363b6f28.png)

**Comment by ericchase** [comment]
@iliakan 

I believe we are using Chrome 102. It seems like this bug was just introduced

**Comment by ericchase** [comment]
A test page to demonstrate the issue:
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <style>
        #col {
            column-count: 2;
        }

        #col div div {
            position: relative;
        }

        #col div div:before {
            position: absolute;
            content: '__1';
        }
    </style>

    <title>Using multi-column layouts - example_1 - code sample</title>
</head>

<body>
    <div id="col">
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
        <div>
            <div>a</div>
        </div>
    </div>
</body>

</html>
```

**Comment by joaquinelio** [comment]
chrome 102 on android fails too

**Comment by iliakan** [comment]
Wow! I updated to 102 and now I have the bug!
Good old times! Browsers introduce bugs, and devs need to work around.

Did you find a good fix, @ericchase ?

**Comment by joaquinelio** [comment]
![image](https://user-images.githubusercontent.com/6558304/171623538-41bd8057-c40d-40a6-881a-d65483059f88.png)

Edge 102 
🤣

**Comment by Manik2375** [comment]
A workaround I found, remove `position: absolute` from `::before` 

![image](https://user-images.githubusercontent.com/71554953/171689866-8659e220-8499-45f5-9907-4dd024a46e72.png)

Seems like position-relative isn't working in parent... this solution has a problem that bigger text isn't aligned properly, wish we could use subgrid :sweat_smile:
