### ISSUE TITLE
Maintainers of the Dutch translation don't respond

### ISSUE THREAD

**Issue by illright** [javascript-tutorial/en.javascript.info#3050]
I submitted a PR two weeks ago, but didn't get a response yet.

https://github.com/javascript-tutorial/nl.javascript.info/pull/63

**Comment by iliakan** [comment]
Can you be a maintainer? @ChiefChingu isn't active.

**Comment by illright** [comment]
I'm only learning Dutch (which is why I hoped someone with actual Dutch knowledge would review my translations), so I'm slightly afraid to take on this endeavour. If you think that could still better than no maintainers, I could take it on.

**Comment by iliakan** [comment]
Thank you @illright, but it must be a native Dutch speaker.

We need to ensure the quality of the translation.

**Comment by iliakan** [comment]
Maintainer is in, @illright ;)

**Comment by illright** [comment]
@iliakan The new maintainer didn't seem to take care of any open PRs, can we assign a new one?
