### ISSUE TITLE
Fix link in (2.18)Javascript specials

### ISSUE THREAD

**Issue by nintendoit** [javascript-tutorial/en.javascript.info#3052]
The link of bitwise operator to MDN docs is broken.It takes to the correct page but not to bitwise operator permalink.

Link given:    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#Bitwise
Correct link:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#bitwise_operators

**Comment by iliakan** [comment]
Thank you!
