### ISSUE TITLE
one of the examples in the "real-life analogy" is missing quotation

### ISSUE THREAD

**Issue by tursynay** [javascript-tutorial/en.javascript.info#3055]
Thank you for the tutorial.

<!DOCTYPE html>
<script>
"use strict";

let hello = 'Hello world!';

let message;

// copy 'Hello world' from hello into message
message = 'hello';

// now two variables hold the same data
alert(hello); // Hello world!
alert(message); // Hello world!
</script>

**Comment by iliakan** [comment]
what's missing
