### ISSUE TITLE
Mistake: Map.keys return an iterator, not an iterable 

### ISSUE THREAD

**Issue by ritwaldev** [javascript-tutorial/en.javascript.info#3063]
In https://javascript.info/map-set:

> map.keys() – returns an iterable for keys,
map.values() – returns an iterable for values,
map.entries() – returns an iterable for entries [key, value], it’s used by default in for..of.

I think this should be **"iterator"** instead. As, by definitions from https://javascript.info/iterable:

> **iterator** – an object with the method next

and 

> **Iterable** - an object that implement the Symbol.iterator method.

Either definitions in https://javascript.info/iterable are wrong,  usage in https://javascript.info/map-set is wrong, or I am missing something.

**Comment by iliakan** [comment]
The question is quite interesting.
To answer correctly, we need to check the language specification, as the ultimate source of truth.

The for-of evaluation spec is here: https://tc39.es/ecma262/#sec-runtime-semantics-forinofloopevaluation.

```
ForInOfStatement : for ( LeftHandSideExpression of AssignmentExpression ) Statement
   1. Let keyResult be ? ForIn/OfHeadEvaluation(« », AssignmentExpression, iterate).
   2. Return ? ForIn/OfBodyEvaluation(LeftHandSideExpression, Statement, keyResult, iterate, assignment, labelSet).
```

1. `ForIn/OfHeadEvaluation` is basically a `GetIterator` call for the value of `AssignmentExpression`. It returns the result of its `Symbol.iterator` method. This is the iterator.
2. The `ForIn/OfBodyEvaluation` then calls `.next()` method of this iterator object.

So, in `for(item of map.keys())` the `map.keys()` object must have the `Symbol.iterator`. In other words, `map.keys()` must return an iterable.

Now let's look at the `map.keys()` method spec: https://tc39.es/ecma262/#sec-map.prototype.keys.

It's basically a call to `CreateMapIterator` https://tc39.es/ecma262/#sec-createmapiterator.

Here's a quote from its spec: "The abstract operation CreateMapIterator takes arguments map (an ECMAScript language value) and kind (key+value, key, or value) and returns either a normal completion containing a Generator or a throw completion". 

So when we call `map.keys()`, the result should be a `Generator`.

But in fact, when I call it in browser console, that's not a generator.

Here, in Firefox (Chrome is somewhat similar):

<img width="365" alt="image" src="https://user-images.githubusercontent.com/349336/174427003-41c9e63b-3eb5-47c1-981d-f0f0eae6acce.png">

That's an object, not a generator. And it has both `.next` and `Symbol.iterator` methods.

So it looks like browsers deviate from the spec.... Or do they? Am I mistaken somewhere?

**Comment by ritwaldev** [comment]
From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/keys: 
> The keys() method ***returns a new iterator object*** that contains the keys for each element in the Map object in insertion order. In this particular case, ***this iterator object is also an iterable***, so a for...of loop can be used.

Also, from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#generator_functions
> When called, generator functions do not initially execute their code. Instead, they return **a special type of iterator, called a Generator**

Also, from https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-generator-objects
> A Generator is an instance of a generator function and conforms to *both the Iterator and Iterable interfaces*.

The **Iterable** Interface Required Properties:
> `@@iterator` >> a function that returns an Iterator object	

The **Iterator** Interface Required Properties:
> `next` >> a function that returns an IteratorResult object

From the above definitions, it seems to me that a `Generator` must have both, an `@@iterator` (since it must conform to the iterable interface) and `next()` (since it must conform to the iterator interface).

When you quoted the definition of  `CreateMapIterator()`, you left out the rest of the definition:
> The abstract operation CreateMapIterator takes arguments map (an [ECMAScript language value](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-language-types)) and kind (key+value, key, or value) and returns either a [normal completion containing](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-completion-record-specification-type) a Generator or a [throw completion](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-completion-record-specification-type). ***It is used to create iterator objects for Map methods that return such iterators.***

It almost seems like the docs are sometimes using `Generator` and `Iterator` interchangeably, which might explain why Firefox is calling it an `iterator` instead.

Its late here and there is a serious possibility I am wandering way off tracks here.

**Comment by iliakan** [comment]
> From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/keys:
> ...

Please don't reference MDN, as it's not a specification and may be sometimes be wrong about in-depth technical matters.

The specification is much better.

> Also, from https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-generator-objects
> 
> > A Generator is an instance of a generator function and conforms to _both the Iterator and Iterable interfaces_.

Yes, agree.
 
> Also, from https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-iteration:
> 
> The **Iterable** Interface Required Properties:
> 
> > `@@iterator` >> a function that returns an Iterator object
> 
> The **Iterator** Interface Required Properties:
> 

`@@iterator` is the same as Symbol.iterator. It just says that an iterable must have `Symbol.iterator`, same as in the tutorial.
The spec uses `@@` instead of the `Symbol.` prefix.

> > `next` >> a function that returns an IteratorResult object
> 
> From the above definitions, it seems to me that a `Generator` must have both, an `@@iterator` (since it must conform to the iterable interface) and `next()` (since it must conform to the iterator interface).

Actually, it seems I was missing the thing.

In the previous letter I said that `MapIterator` isn't a `Generator`. But actually it *is*. Sorry. No deviation from the spec.

And, we both agree that generators are iterable, the site is also correct.

These calls:
- map.keys() – returns an iterable for keys,
- map.values() – returns an iterable for values,
- map.entries() – returns an iterable for entries [key, value], it’s used by default in for..of.

All return iterables (generators).

That said, closing the issue, reopen if in doubts.
