### ISSUE TITLE
[Bug]: Image shade isn't changing

### ISSUE THREAD

**Issue by Manik2375** [javascript-tutorial/en.javascript.info#3082]
Hi there! 
I was looking at https://javascript.info/size-and-scroll#clienttop-left, here the image even in dark mode has that white shade which doesn't seem to match the color scheme. 

![image](https://user-images.githubusercontent.com/71554953/175553581-ed98ae53-b669-4f80-aa08-53e62c4af6a7.png)

Tried it in both firefox and chrome, the bug persists. I wonder if there should be a dark shade/shadow here

**Comment by iliakan** [comment]
Thank you, @Manik2375 !

I improved my SVG-theming code to include gradients into theming also, and the problem seems to have gone away.
