### ISSUE TITLE
Missing closing tags

### ISSUE THREAD

**Issue by ritwaldev** [javascript-tutorial/en.javascript.info#3124]
On the example: https://javascript.info/event-delegation#behavior-counter

```
Counter: <input type="button" value="1" data-counter>
One more counter: <input type="button" value="2" data-counter>
```
No closing tags. They don't throw an error because browser will fix them, but I think they should be fixed none the less.
```
Counter: <input type="button" value="1" data-counter />
One more counter: <input type="button" value="2" data-counter />
```

**Comment by romanstetsyk** [comment]
According to the [spec](https://html.spec.whatwg.org/multipage/syntax.html#start-tags) the trailing slash is optional in void elements, so this is not an error.

> Then, if the element is one of the [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), or if the element is a [foreign element](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), then there may be a single U+002F SOLIDUS character (/). This character has no effect on [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), but on [foreign elements](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements) it marks the start tag as self-closing.

In addition, some HTML/CSS Style Guides advice not to include the trailing slash in self-closing elements (e.g. [link](https://google.github.io/styleguide/htmlcssguide.html#Document_Type), [link](https://codeguide.co/#html-syntax))

**Comment by iliakan** [comment]
not an error
