### ISSUE TITLE
Variables, Task 1: Change the "name" variable to avoid ambiguity for deprecated naming

### ISSUE THREAD

**Issue by aseiis** [javascript-tutorial/en.javascript.info#3126]
The first task of the [variables page](https://javascript.info/variables) suggest to declare and use two variables : 
`admin` and `name`.

Using `name` as the name of the variable can be confusing and code editors will show a warning: 'name' is deprecated.ts(6385)
lib.dom.d.ts(17693, 5): The declaration was marked as deprecated here. (VSCode)

`name` variable should be renamed

**Comment by joaquinelio** [comment]
I didnt try...
but it is not a reserved word,
 "let name" scope should override the global "name".
editors shouldnt warn I think.

anyway, userName would comply with article recommendations

**Comment by ego-edesse** [comment]
I gave the warning VSCode gave me above (`name` variable was crossed out).
Yup, I agree: `username` would better fit I believe!

**Comment by alisha-takkar** [comment]
#3299
