### ISSUE TITLE
String.prototype.substr() is "Deprecated. Not for use in new websites" according to MDN

### ISSUE THREAD

**Issue by romanstetsyk** [javascript-tutorial/en.javascript.info#3132]
According to MDN, String.prototype.substr() is deprecated and no longer recommended.
I'd suggest mentioning it or completely removing the references to this method.

Found in [Part 1. Chapter 5.3](https://javascript.info/string#getting-a-substring)

**Comment by iliakan** [comment]
MDN isn't a spec. They may be mistaken. 

I didn't hear about the deprecation, so closing this.
