### ISSUE TITLE
Sec-WebSocket-Key provides no security

### ISSUE THREAD

**Issue by ThetaEdra** [javascript-tutorial/en.javascript.info#3162]
The Tutorial on https://javascript.info/websocket states about Sec WebSocket Key "a random browser-generated key for security." but this is false. The Key makes sure the Session gets setup properly but adds no additional security.

See the wikipedia entry or https://stackoverflow.com/questions/18265128/what-is-sec-websocket-key-for and the linked RFCs.

**Comment by iliakan** [comment]
You misunderstood the SO.
```
7.   The request MUST include a header field with the name
        |Sec-WebSocket-Key|.  The value of this header field MUST be a
        nonce consisting of a randomly selected 16-byte value that has
        been base64-encoded (see [Section 4 of [RFC4648]](https://datatracker.ietf.org/doc/html/rfc4648#section-4)).  The nonce
        MUST be selected randomly for each connection.
```

**Comment by ThetaEdra** [comment]
While thats true as far as i see it is not used to provide any security only because its a nonce. Its only function is to make sure that the Session gets setup properly

**Comment by iliakan** [comment]
Why is it a random value, not just something hardcoded?

**Comment by ThetaEdra** [comment]
the server replies with a hash of the key in the Sec-WebSocket-Accept header. This is intended to prevent a caching proxy from re-sending a previous WebSocket conversation

**Comment by iliakan** [comment]
The session key is a random value for security.

**Comment by iliakan** [comment]
btw, for caching proxies - there are caching headers

**Comment by iliakan** [comment]
bad proxies  may ignore them, but there are few such proxies nowadays.

**Comment by ThetaEdra** [comment]
See https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake

Also See https://datatracker.ietf.org/doc/html/rfc6455#section-11.3.1

   The |Sec-WebSocket-Key| header field is used in the WebSocket opening
   handshake.  It is sent from the client to the server to provide part
   of the information used by the server to prove that it received a
   valid WebSocket opening handshake.  This helps ensure that the server
   does not accept connections from non-WebSocket clients (e.g., HTTP
   clients) that are being abused to send data to unsuspecting WebSocket
   servers.

You can read about the handshake here

https://datatracker.ietf.org/doc/html/rfc6455#section-1.3

The way it is implemented the Sec-WebSocket-Key is random but it adds no security to the communication at all. It only makes sure the Session is correctly created. If you want a secure connection you <need> to use Secure Websockets.

**Comment by iliakan** [comment]
Ok =) Thanks, does it look better now?

**Comment by ThetaEdra** [comment]
yeah i think thats better, thanks for changing the wording :)
