### ISSUE TITLE
Possible wrong format for splice syntax

### ISSUE THREAD

**Issue by ngchrbn** [javascript-tutorial/en.javascript.info#3163]
[Splice part](https://javascript.info/array-methods#splice)

The syntax is written as follow:

`arr.splice(start[, deleteCount, elem1, ..., elemN])`

But on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#syntax), the syntax is as follow:

`splice(start, deleteCount, item1, item2, itemN)`

**Comment by iliakan** [comment]
not an issue
