### ISSUE TITLE
At section “Escaping, special characters”, I found an inconsistency between code and its description.

### ISSUE THREAD

**Issue by PointerToNextPole** [javascript-tutorial/en.javascript.info#3169]
I had searched "regexp escaping" keyword in the issue search box and got nothing that could eliminate my confusion, so I came here to write the issue. 😜

In [Regular expressions - Escaping, special characters # new RegExp](https://javascript.info/regexp-escaping#new-regexp), I found  a little inconsistency, just like the quotes below:
> Here’s how “\d.\d” is perceived:
> ```js
> alert("\d\.\d"); // d.d
> ```
The string to be “alerted” in the code is described as “\d.\d”, but in the code, the string to be “alerted“ is “\d\.\d”; just a little inconsistency.

I am confused if it is a clerical mistake or a deliberate act, so write the issue.

**Comment by iliakan** [comment]
Sorry for the delay, I don't quite understand the problem ;(

**Comment by PointerToNextPole** [comment]
That's fine, what I said is just for curiosity, and it doesn't matter. Thank you for your reply. 😂

> Sorry for the delay, I don't quite understand the problem ;(
