### ISSUE TITLE
Publish Persian translations

### ISSUE THREAD

**Issue by mahdyar** [javascript-tutorial/en.javascript.info#3172]
Hi, It seems like we've made it at [`fa.javascript.info`](https://github.com/javascript-tutorial/fa.javascript.info)! 🥳 

As mentioned in the "Publish" part of [this](https://javascript.info/translate) page, it's now more than half-finished.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/20593549/187735224-0fcf4b73-05d8-45cb-82cc-0cb8f659a261.png">

cc @iliakan

**Comment by Beroozam** [comment]
> 

I am waiting too. Thanks everybody.💪❤

**Comment by mahdyar** [comment]
> Well done, I'll carry this forward tomorrow! 🎸

Hi, any updates on this?

**Comment by iliakan** [comment]
Sorry, not yet, will be publishing very soon.

**Comment by iliakan** [comment]
Sorry for the delay, had really pressing matters to attend to. Now let's get publishing ;)
[locales.zip](https://github.com/javascript-tutorial/en.javascript.info/files/9541041/locales.zip)

Please translate the phrases: keep English to the left, and make them Farsi to the right, all quoted.

**Comment by mahdiHash** [comment]
> 

![2022-09-10_230934](https://user-images.githubusercontent.com/72219881/189497696-703f85ef-eced-42ee-aa57-1c7839488149.png)

Hi, @iliakan.  
I was wondering if we have to surround all the right phrases in quotation marks.
What about the ones already including quotes (e.g. the repo address shown in the image)? Single quotes are supported, right?

**Comment by iliakan** [comment]
I'm not sure about Farsi, please use double quotes to make sure it's all good.

**Comment by iliakan** [comment]
and \" for quotes inside quotes =)

**Comment by mahdiHash** [comment]
> I'm not sure about Farsi, please use double quotes to make sure it's all good.

Farsi is similar to Arabic, and quotes are not used in [`locales/ar.yml`](https://github.com/javascript-tutorial/server/blob/master/locales/ar.yml), so I guess there won't be any problem without "".

**Comment by mahdyar** [comment]
Hi, it's done:
[locales.zip](https://github.com/javascript-tutorial/en.javascript.info/files/9541372/locales.zip)

Let us know if something's wrong.

cc @iliakan @mahdiHash

**Comment by mahdiHash** [comment]
> Hi, it's done: [locales.zip](https://github.com/javascript-tutorial/en.javascript.info/files/9541372/locales.zip)
> 
> Let us know if something's wrong.
> 
> cc @iliakan @mahdiHash

No problem I see :)

**Comment by iliakan** [comment]
Please fix the duplicate (see the English version, should be only one of them):
- ./1-js/07-object-properties/03-prototype-inheritance
- ./1-js/08-prototypes/01-prototype-inheritance

**Comment by mahdyar** [comment]
> Please fix the duplicate (see the English version, should be only one of them):
> 
>     * ./1-js/07-object-properties/03-prototype-inheritance
> 
>     * ./1-js/08-prototypes/01-prototype-inheritance

So should we remove all directories except the first two ones [here](https://github.com/javascript-tutorial/fa.javascript.info/tree/master/1-js/07-object-properties)?

**Comment by iliakan** [comment]
Please see the English variant.

Guess, one of these is a stale one, left from long time ago.

**Comment by mahdyar** [comment]
> Please see the English variant.
> 
> Guess, one of these is a stale one, left from long time ago.

Yup, it was the second one.
OK, now how does it look?

**Comment by iliakan** [comment]
Yep, fixed.
Please, take a look at this duplicate:
- ./9-regular-expressions/06-regexp-unicode
- ./9-regular-expressions/03-regexp-unicode

**Comment by mahdyar** [comment]
> Yep, fixed. Please, take a look at this duplicate:
> 
>     * ./9-regular-expressions/06-regexp-unicode
> 
>     * ./9-regular-expressions/03-regexp-unicode

Done.

**Comment by iliakan** [comment]
In Disqus (comment system) there's no Farsi/Persian language choice.

There's Arabic, though. Should I set Arabic?

**Comment by mahdyar** [comment]
> In Disqus (comment system) there's no Farsi/Persian language choice.
> 
> 
> 
> There's Arabic, though. Should I set Arabic?
> 
> 
> 
> P.S. I know it's a very different language, just wondering... I can set English.
> 
> There's also Tajik.

I use English in my own website. And yes, you're right. They're very different and people here know English much better than Arabic.

**Comment by iliakan** [comment]
Please, take a look: https://fa.javascript.info/

**Comment by mahdiHash** [comment]
> Please, take a look: https://fa.javascript.info/

![2022-09-11_151346](https://user-images.githubusercontent.com/72219881/189523304-fb08e767-74c2-4336-857b-8dbbdece5970.png)

I guess these parts weren't inside the [locale.zip](https://github.com/javascript-tutorial/en.javascript.info/files/9541041/locales.zip) that you uploaded here. Is there any way we translate them, too?

**Comment by iliakan** [comment]
They are inside the tutorial repo. Duly noted, they should be translated indeed ;)

**Comment by mahdiHash** [comment]
> 

We'll work on it then.
Thank you @iliakan. The tutorial is awesome!

**Comment by mahdyar** [comment]
> Please, take a look: https://fa.javascript.info/

Hi; It looks good, but here's some suggestions/problems I see:

1. Is it possible to add a Persian font to the site? [`Vazirmatn`](https://github.com/rastikerdar/vazirmatn) for example.

2. The search doesn't work at all and returns a 500 error. [[+](https://fa.javascript.info/search/?query=test&type=article)]

3. The search icon in the menu, when you click on it, makes a horizontal scroll:

![Screen Recording 2022-09-11 at 21 32 48](https://user-images.githubusercontent.com/20593549/189540049-c69fbf1d-b9cb-4c04-884a-005f1504af7d.gif)

4. Is it possible to change the English Discord chat to our Persian Telegram group chat?

**Comment by mahdiHash** [comment]
I agree with Mahdyar. The [`Vazirmatn`](https://github.com/rastikerdar/vazirmatn) font style is much better and readable than the default one. It would be great if you change it.

**Comment by mahdiHash** [comment]
![2022-09-11_221645](https://user-images.githubusercontent.com/72219881/189541887-e054714d-6047-4f40-9f86-a9aa8fb46e58.png)

Could we have articles numbers at right of its name?
This way, it'll make more sense to the readers.

**Comment by iliakan** [comment]
Site search - I'm working on it.

For website styling - could you please install https://github.com/iliakan/javascript-tutorial-server and run the tutorial locally, change what's wrong in styles?

**Comment by mahdiHash** [comment]
Hi, @iliakan.

It seems like the [fa.javascript.info](https://fa.javascript.info) isn't sync with the [Persian repository](https://github.com/javascript-tutorial/fa.javascript.info). There are some updates in the repo, but can't be seen in the website. Can you check it out to see what's wrong?

Also, we have changed the `locales.zip` content. Could you update it for the website, please? @mahdyar has uploaded it [here](https://github.com/javascript-tutorial/en.javascript.info/files/9543147/locales.zip).

**Comment by iliakan** [comment]
- Updated locales.
- Created webhook for autoupdate from the repo.

Waiting for advise on what to fix on site. The javascript-tutorial/server is a simpler repo, but fixes there are acceptable too.

**Comment by mahdiHash** [comment]
> Yes, thanks.
> 
> * Updated locales.
> * Created webhook for autoupdate from the repo.
> 
> Waiting for advise on what to fix on site styles. The javascript-tutorial/server is a simpler repo, but fixes there are acceptable too.

We'll inform you about styles.
Thank you for the fixes.

**Comment by mahdiHash** [comment]
Hi, @iliakan.

Currently we can't work on the styles. When the time comes for the changes, we'll let you know.
