### ISSUE TITLE
> Polish? Did you ping the maintainer? @kdshop , @RafalMichniuk want to go maintainers?

### ISSUE THREAD

**Issue by RafalMichniuk** [javascript-tutorial/en.javascript.info#3184]
> Polish? Did you ping the maintainer? @kdshop , @RafalMichniuk want to go maintainers?

Yes sure I will also connect with @RafalMichniuk to set up some plan for works

_Originally posted by @kdshop in https://github.com/javascript-tutorial/en.javascript.info/issues/2513#issuecomment-1241107294_

Hi @kdshop, how do you want to connect? :)

**Comment by iliakan** [comment]
What was that?

**Comment by RafalMichniuk** [comment]
I'm sorry - it was created by accident.

**Comment by iliakan** [comment]
😆
