### ISSUE TITLE
Correction needed in the Page Arrow Function - https://javascript.info/arrow-functions

### ISSUE THREAD

**Issue by priyeshbitsp** [javascript-tutorial/en.javascript.info#3203]
I don't think this is undefined as mentioned. this is indeed a global object here. And yes this.title is undefined as no such variable is initialized in the scope of the global object. Kindly check.

<img width="746" alt="Screenshot 2022-09-27 at 2 59 51 PM" src="https://user-images.githubusercontent.com/85963395/192490347-9d28f9b3-fed6-4b29-9b70-17443f9075af.png">

**Comment by joaquinelio** [comment]
!!!
"this" is in fact undefined, dont now why

**Comment by iliakan** [comment]
Don't forget to `use strict`.

All examples are in `use strict`, we don't write it explicitly for the sake of brevity.

**Comment by priyeshbitsp** [comment]
Alright, makes sense
