### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by Mecopi** [javascript-tutorial/en.javascript.info#3257]
Translation's missing in French documentation version at end of https://fr.javascript.info/closure#code-blocks section

**Comment by joaquinelio** [comment]
@Mecopi, 
fr maintainer may not see this issue, fr branch is a better place

@iliakan, 
maybe not the case, but this is the kind of problem you get when you use bot's merge instead of your own,  
FF changes harder to find

**Comment by iliakan** [comment]
@Mecopi Please report at https://github.com/javascript-tutorial/fr.javascript.info/issues (or maybe submit a PR ? ;) )

**Comment by benjGamache** [comment]
Hi, ok, sorry about that.
Thanks for replies ! :D
