### ISSUE TITLE
Translation to Malay Language (ISO 639-1 Code : "ms")

### ISSUE THREAD

**Issue by JianLoong** [javascript-tutorial/en.javascript.info#3259]
Greetings, 

I have learnt a lot from this website and often use it as my go to point for reference. (Besides MDN of course).

I would love to contribute with the translation to Malay language.

**ISO639-1 language code** : ms

However, since *ms* is the identifier **macro** language of Malay and ISO639-1 does not specify anything about the treatment of macro languages, my plan is to entirely use [standard Malay](https://en.wikipedia.org/wiki/Malaysian_Malay) instead of other variants of the language for the translation.  This is also the case where Wikipedia has the "ms" to indicate standard Malay for their articles as it is the most used form.

**Maintainer List**

GitHub - @JianLoong (Myself)
Email - jianloongliew@gmail.com

**Comment by iliakan** [comment]
Welcome to the team! Invite sent ;)
