### ISSUE TITLE
Scala actually allows mutable variables

### ISSUE THREAD

**Issue by arigoldx** [javascript-tutorial/en.javascript.info#3260]
I was just going through your _fantastic_ book and thought I should mention that which there is some truth in the little section on functional languages in the [variables chapter](https://javascript.info/variables) it's not technically correct. That is, Scala [allows](https://docs.scala-lang.org/overviews/scala-book/two-types-variables.html#:~:text=The%20difference%20between%20val%20and%20var%20is%20that%20val%20makes,as%20values%20rather%20than%20variables.) mutable variables. Heck even Haskell [does](https://wiki.haskell.org/Mutable_variable).

I'm happy to open a pull request to improve the text, if you think that would be helpful. It seems like a more thorough explanation might help -- while you _can_ use mutable variables in Scala (or Haskell) the fundamental concepts of functional programming most definitely stressed immutable variables, like you said.

**Comment by iliakan** [comment]
Hey, thanks!

Do you mean that we should use the term "pure functional language"? As the [wiki](https://en.wikipedia.org/wiki/Functional_programming) says, such languages don't allow mutable variables.

**Comment by arigoldx** [comment]
My pleasure :) It's a frickin _fantastic_, well written book & I'm happy to help :)

Well I'm not that familiar with Erlang but given a bit of google searching and given that most functional languages still have a way to mutate state since mutable state is, occasionally, necessary, I might change

> It’s interesting to note that there exist [functional](https://en.wikipedia.org/wiki/Functional_programming) programming languages, like [Scala](https://www.scala-lang.org/) or [Erlang](https://www.erlang.org/) that forbid changing variable values.
>
> In such languages, once the value is stored “in the box”, it’s there forever. If we need to store something else, the language forces us to create a new box (declare a new variable). We can’t reuse the old one.

to something like

> It’s interesting to note that with [functional](https://en.wikipedia.org/wiki/Functional_programming) programming languages, like [Scala](https://www.scala-lang.org/) or [Erlang](https://www.erlang.org/) changing variable values, or "mutating state", is strongly discouraged.
>
> Ideally, in functional languages, you use immutable variables. Once the value is stored “in the box”, it’s there forever. If we need to store something else, you create a new box (declare a new variable). We shouldn't reuse the old one.

That way, it's correct since Scala, for example, has `var` (mutable) even tho ideally programmers would make use of `val` (immutable) whenever possible.

How's that?

**Comment by joaquinelio** [comment]
mmm... no

I mean, WOW, thank YOU, I LOVE you brought this knoledge, I watched a couple of functional introductions and never mentioned val vs var,
maybe it's shamefully allowed indoors "dont let them out", I dont know...

sorry, the point
I love smart "digress", it keeps eyes/brain open without losing focus

"in other langs, it is forbiden" adds interest
"in other langs this is discouraged" adds burden. at this stage of learning, mutable vs immutable does not fit

keep it, keep it short: I liked the "PURE functional language" thing

**Comment by joaquinelio** [comment]
sorry all, Im becoming Abraham Simpson.

and if you dont know who A.S. is, sorry for this comment too

**Comment by arigoldx** [comment]
wow, that was a fun one 😅 

oh, i see [yall committed a change](https://github.com/javascript-tutorial/en.javascript.info/commit/746ad803c878e33182e7fab1578c0d15b9b75ca0) 🙌 

got me confused with that

> mmm... no

anyway & fwiw, the new text is still technically false:

> It’s interesting to note that there exist so-called [pure functional](https://en.wikipedia.org/wiki/Purely_functional_programming) programming languages, such as [Haskell](https://en.wikipedia.org/wiki/Haskell), that forbid changing variable values.

see the [official Haskell wiki](https://wiki.haskell.org/Mutable_variable) for examples & reasoning.

like ya said, people are in a state of learning -- i just didn't want them to read false things. if they can understanding the complexity of javascript (`this`, closures, etc), they can probably understand things like

"Although the functional programming paradigm emphasises the virtues of immutable variables, sometimes you need mutable variables nonetheless."

(from the docs above).

¯\\\_(ツ)\_/¯ & thanks

**Comment by iliakan** [comment]
Please read it carefully. It uses monads.
