### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by bogdanbacosca** [javascript-tutorial/en.javascript.info#3274]
Hi, I spoke with the maintainer of the Romanian translation @lighthousand privately about the work being done there. Obviously the repo is not that active and he suggested that it would be a good idea that I became a Maintainer.
Honestly I just wanted to contribute to this project but I am also keen to learn more about how to maintain a repo myself.

**Comment by iliakan** [comment]
Done! Invite sent.
