### ISSUE TITLE
Translation to Uyghur Language (ISO 639-1 code : ug)

### ISSUE THREAD

**Issue by UyCode** [javascript-tutorial/en.javascript.info#3275]
Hello JavaScript Team:

  My name is Ahmad, a back-end developer, also a JavaScript lover, I have learned a lot from this website. I really appreciate javascript.info and the team.
  In my language (Uyghur), there is lots of developers using JavaScript, but many of them don't understand English well, So I want to translate this website. I believe lots of Uyghur developers will benefit from this and will have better understanding about JavaScript.

**ISO639-1 language code**: ug
I would love to contribute with the translation to Uyghur language.

**Maintainer List**
GitHub: UyCode
Email: Hyper-Hack@outlook.com

**Comment by UyCode** [comment]
any author can response this issue please.

**Comment by iliakan** [comment]
Sorry for the wait. Done! Invite sent ;)
