### ISSUE TITLE
Translate to Kyrgyz language

### ISSUE THREAD

**Issue by Akmatworld** [javascript-tutorial/en.javascript.info#3291]
I would like to translate this useful tutorial to our Kyrgyz language.

```
{
  "name": "Kyrgyz",
  "code": "ky",
  "maintainers": [
    {
      githubNick: "Akmatworld",
      email:"sirazhidinovakmatali@gmail.com"
    }
  ]
}
```

**Comment by iliakan** [comment]
The translation is ongoing on https://github.com/javascript-tutorial/ky.javascript.info/

You're welcome to contribute! 

In case the maintainer @laindeso2 does not respond, please let me know.
