### ISSUE TITLE
Wrong solution for the Function in if exercise

### ISSUE THREAD

**Issue by baharev** [javascript-tutorial/en.javascript.info#3320]
If I execute the [Function in if](https://javascript.info/closure#function-in-if) exercise I get `Hello, John`, and that was the solution I expected as well.

However, in your solution I read:

> The result is **an error**. 
> The function `sayHi` is declared inside the `if`, so it only lives inside it. There is no `sayHi` outside.

Your solution is wrong, please fix it.

**Comment by iliakan** [comment]
You forgot `use strict`

**Comment by baharev** [comment]
@iliakan **You** forgot `use strict` on your webpage. If I execute your example "as-is", I get `Hello, John`. Sorry, it's a bug on your part.

You are welcome.

**Comment by iliakan** [comment]
All examples are assumed to run with `use strict`. You probably missed this part.

Sometimes that happens, got an idea how to clearly show others that `use strict` is always on?

Don't want to explicitly put it everywhere.

**Comment by baharev** [comment]
> All examples are assumed to run with use strict.

I did what I was supposed to do: Hit the execute button on the website, and got `Hello, John`. However, your solution claims that I get an error, which I clearly don't. Your website is just plain wrong.

The examples on your website are **NOT** run with `use strict` either.

>  You probably missed this part. Not only you. With other people same happens, 

It should be a sign that actually your webpage is broken, and you should fix it.

I did not miss anything: You are not mentioning it on that page *anywhere*, and you are running them in sloppy mode on the webpage too. This is the only mention of `use strict` on that page:

> If a variable is not found anywhere, that’s an error in strict mode (without use strict, an assignment to a non-existing variable creates a new global variable, for compatibility with old code).

If you still think it is OK, then I rest my case.

> got an idea how to clearly show others that use strict is always on?
>
> Don't want to explicitly put it everywhere.

First things first: You should run the examples in strict mode on the website too. You are currently running them in sloppy mode, leading to wrong results.

Second, if something is that important and the example is plain wrong without it, then it **must** be in it. Full stop.

**Comment by iliakan** [comment]
Which browser do you use?

Here's the error that I get when I click the right-top "play" button:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/349336/210951168-df56fdaa-bf1a-4b33-a4dc-6a09f0668ab3.png">

**Comment by baharev** [comment]
Sorry, I have fallen victim to my own strange browser setup here what the *"The examples on your website are NOT run with use strict either."* concerns. It is my bad, and I apologize.

However, for the rest, I still think you should fix those issues: 
 
 - You are not mentioning on that page at all that the examples must be run in strict mode.
 - You are discarding code that is essential for the example to work, namely `use strict`.

The code that you are showing on the webpage is not the code that you are executing in the background. If I hit that pencil, I get:

```html
<!DOCTYPE html>
<script>
"use strict";

let phrase = "Hello";

if (true) {
  let user = "John";

  function sayHi() {
    alert(`${phrase}, ${user}`);
  }
}

sayHi();
</script>
```

So you are silently discarding the `"use strict;"` on the website, although it is crucial for that example to work.

If something is that important and the example is plain wrong without it, then it must be in the code. Full stop.

As you wrote: *"You probably missed this part. Not only you. With other people same happens"*. It is a signal that you shouldn't be tripping people up.

**Comment by iliakan** [comment]
Yes, I also would like to make it more obvious, but adding use strict everywhere seems to be too much.Best regards,Ilya KantorOn 6 Jan 2023, at 13:27, Ali Baharev ***@***.***> wrote:﻿
Sorry, I have fallen victim to my own strange browser setup here what the "The examples on your website are NOT run with use strict either." concerns. It is my bad, and I apologize.
However, for the rest, I still think you should fix those issues:

You are not mentioning on that page at all that the examples must be run in strict mode.
You are discarding code that is essential for the example to work, namely use strict.

The code that you are showing on the webpage is not the code that you are executing in the background. If I hit that pencil, I get:
<!DOCTYPE html>
<script>
"use strict";

let phrase = "Hello";

if (true) {
  let user = "John";

  function sayHi() {
    alert(`${phrase}, ${user}`);
  }
}

sayHi();
</script>
So you are silently discarding the "use strict;" on the website, although it is crucial for that example to work.
If something is that important and the example is plain wrong without it, then it must be in the code. Full stop.
As you wrote: "You probably missed this part. Not only you. With other people same happens". It is a signal that you shouldn't be tripping people up.

**Comment by baharev** [comment]
> Yes, I also would like to make it more obvious, but adding use strict everywhere seems to be too much.

It would be sufficient to add it only if it is crucial for the example to work. Chances are, most of the time it is irrelevant anyway.

On the other hand, if it is crucial for the example to work, it must be in the code. Or you will keep wasting your time and other people's time with similar GitHub issues like this one.
