### ISSUE TITLE
Improve the content with plain language (English)

### ISSUE THREAD

**Issue by p2635** [javascript-tutorial/en.javascript.info#3335]
Thanks for creating this wonderful tutorial. I've enjoyed it so far and I continue to learn about JS.

**Who are you?**
- Recently, I got interested in the arts of editing (specifically plain language). I am _not_ a professional editor.
- I am a native English speaker from the UK. I am looking to sharpen my skills, not bragging.
- As I read the tutorial, I notice that certain words/phrases can be revised to sound better (in my opinion). 
- I forked this project and ~~created a plain-language branch.~~
- If you're a professional editor, I hope you can work with me to be more conscious on my editing efforts.

**What are you trying to do?**

1. Cut out the extraneous words, more focused content.
2. Improve structure and readability
3. Ultimately save time for both the author and the reader

**What did you spot?**

- 'such' as in 'such a course' -> 'this course' ('such' sounds too formal given the overall tone of the course.)
- 'there exists a function' -> 'there is a function' (same thing, 'there exists' sounds formal or non-native)
- 'We can implement a string' -> 'We can use a string' ('implement' is not a big issue, it's down to what the author prefers. Stick with plain language or not?)

Reference material (note to self): https://www.plainlanguage.gov/resources/checklists/web-checklist/

**Question from me (solved below)**
Before I put more effort into this, I want to know if this project is actively maintained. I see lots of old PRs and issues, so I'm not sure if it's worth my time to suggest edits.

**Ideas for the future**
Perhaps a style guide needs creating in future, I see conflicting things like 'we' vs 'you'. Sometimes 'such that' is used, sometimes it's not. I also noticed there is no specific contribution guide (what to do and what not to do).

UPDATE: I found AUTHORING.md which fits this purpose.

**Comment by iliakan** [comment]
Well, I come and cover all PRs from time to time, just not daily ;)

It's actually high time to do that ;)

**Comment by p2635** [comment]
Another consideration is to change 'we' to 'you'. This wording connects better with the reader.

Example from: https://javascript.info/object-toprimitive (which I'm reading now)

"We have two purposes:
- It will allow us to understand what’s going on in case of coding mistakes, when such an operation happened accidentally.
- There are exceptions, where such operations are possible and look good. E.g. subtracting or comparing dates (Date objects). We’ll come across them later."

1. 'We" have two purposes? How about 'You will learn about:"
2. "It will allow us.." How about "You can"

I love learning about how to optimise word count without changing the meaning. If you want me to contribute with these, let me know!

**Comment by p2635** [comment]
> Well, I come and consider all PRs from time to time, just not daily ;)
> 
> It's actually high time to do that now.

Thanks @iliakan, it's good to know that. It gives me confidence that my time is valued, even if you don't check everyday.

**Comment by p2635** [comment]
What's the best way to organise my commits? One commit per article?

**Comment by iliakan** [comment]
One PR per article. May be many commits.

**Comment by p2635** [comment]
Ok thanks, I will try to organise it that way. Note to self on patterns I've spotted so far:

1. 'such' as in 'such a course' -> 'this course'
2. 'there exists a function' -> 'there is a function'
3. 'We can implement a string' -> 'We can use a string'

**Comment by p2635** [comment]
Updated the main description of this issue

**Comment by p2635** [comment]
Following my thoughts on https://github.com/javascript-tutorial/en.javascript.info/pull/3342#issuecomment-1407768577 @iliakan , please tell me where I stand. If I am allowed to give suggestions on legibility like @joaquinelio said, let me know what counts as 'minor'. I do not want to make the same mistake twice.

**Comment by p2635** [comment]
Closing this because of the lack of interest and I don't think I'm going to revisit this.

**Comment by smith558** [comment]
@p2635 These are some good suggestions and I will try to review all of your outstanding PRs as well as this issue within a month. 🙂 Apologies for you not having received a response earlier.
