### ISSUE TITLE
In the 'Data Types" chapter, a typeof/typeof() output discrepancy

### ISSUE THREAD

**Issue by Mike-A-Fraser** [javascript-tutorial/en.javascript.info#3432]
I've found this tutorial very helpful so far as a beginning JavaScript learner, especially the well-thought out exercises with the detailed solution explanations. 

However, I've encountered a case where the assertion contained in the aside:

	"The typeof(x) syntax

	You may also come across another syntax: typeof(x). It’s the same as typeof x."

is not actually true, though I did not discover this until I reached the exercises in the objects chapter. 

To demonstrate (in the Chrome debugger console):

	let menu = {
		width: 200,
		height: 300,
		title: "My menu",
	}

Try both forms of the typeof syntax (that are claimed to be the same), which reveals two differing outputs:

	typeof menu.title == 'number';
	false
	
	typeof( menu.title == 'number' );
	'boolean'

A clarification of why this typeof/typeof() output discrepancy occurs, and perhaps use cases for each typeof form, would be helpful to us JS neophytes.

**Comment by joaquinelio** [comment]
The 1st is
typeof (menu.title) == 'number';

The 2nd is type of the result of the comparison

**Comment by Mike-A-Fraser** [comment]
Thanks for your contribution, much appreciated. I think I have a grasp on what you're pointing out here, but I'm still not completely clear about typeof's behavior. Further experimenting reveals the following:

	let menu = {
		width: 200,
		height: 300,
		title: "My menu",
	}
	undefined

	menu.title == 'number';
	false
	typeof menu.title == 'number';
	false

	(menu.title) == 'number';
	false
	typeof( menu.title ) == 'number';
	false

	( menu.title == 'number' );
	false
	typeof( menu.title == 'number' );
	'boolean'

I'm not sure what explains the apparent discrepancy in the last pair of statements. Is it a phenomenon of grouping, or of typeof/typeof(), or of the REPL capability in the Chrome debugger?

Maybe this will make more sense as I get further into the book.
