### ISSUE TITLE
‎ ‎ ‎ 

### ISSUE THREAD

**Issue by internetword** [javascript-tutorial/en.javascript.info#3460]

**Comment by Alexandre887** [comment]
If your Issue has lost relevance, you should close it rather than changing the title to a blank line.

![image](https://github.com/javascript-tutorial/en.javascript.info/assets/74434545/b18f2913-84de-48c2-a1e2-a156421fa1ec)

**Comment by internetword** [comment]
It hasn't . Here's the link to it. 
https://github.com/javascript-tutorial/en.javascript.info/issues/3354

**Comment by internetword** [comment]
It's still in use. Issue #3354 still hasn't been fixed. You wouldn't be aware of it if not for this issue so it's still relevant.

**Comment by Alexandre887** [comment]
This Issue has an **empty title** and an **empty description**. It provides absolutely **no value** to the tutorial. 

Your new Issue (#3354) has already been seen by the author, for what reason are you keeping #3460 open? Do you think your new issue is not showing up in the list? Or what? Do you think that by not going to #3460, no one will know about #3354? You're just clogging up the Issue list.

**Comment by internetword** [comment]
ok but before I close this issue. 

Since you seem to understand how the site work. Do you know how can I get community assessments for my solutions to the tasks on javascript.info since I come up with a different solution than the author quite a lot and they seem to also work quite well?

**Comment by Alexandre887** [comment]
If you're not completely sure about the correctness of your solutions, I'd suggest you to publish your solution to a particular problem and the author's solution on some of the popular forums/Q&A sites, like [Code Review Stack Exchange](https://codereview.stackexchange.com/), maybe [Stackoverflow](https://stackoverflow.com/), and ask how the first solution differs from the second, what are the pros/cons, etc. 

javascript.info also has its own [Discord server](https://discord.gg/AuEWpFkfD4), which is currently active, and on it you can get an answer from experienced developers quite quickly. For example:

> The solution provided by the author in the article "article_name":
> 
> ```javascript
> // ...some code
> ```
> In my opinion, this solution is not quite correct because ...........
> 
> My solution, which in my opinion works much better than the author's solution:
> ```javascript
> // ..some code
> ```
> Please comment on my solution and tell me how it differs from the author's solution and what are the pros and cons of one and the other solution in general

When you're completely sure that your solution is indeed better than the author's, you can submit a Pull Request with the fixes to the javascript.info repository. 

But anyway, looking at the number of open Issues and PRs you can see that the author quite rarely looks at an Issue and accepts PRs. In the English version of the tutorial, he does it all alone, he has no assistants, so you have to wait a long time for him to review your PR.

**Comment by internetword** [comment]
I'm banned from asking questions on stackoverflow for no reason. I can't get any answer from the discord server.

I'm looking for an assessment forum like it exist for the mdn like this: https://discourse.mozilla.org/t/assessment-wanted-for-creating-fancy-letterheaded-paper/112612 for example.

**Comment by internetword** [comment]
It worked, Thank you !
