### ISSUE TITLE
typo in https://javascript.info/custom-elements

### ISSUE THREAD

**Issue by dangarharshil11** [javascript-tutorial/en.javascript.info#3474]
in the custom element section there is typo in the following paragraph

Now for any HTML elements with tag <my-element>, an instance of MyElement is created, and the **aforementioned** methods are called. We also can document.createElement('my-element') in JavaScript.

it should be:
Now for any HTML elements with tag <my-element>, an instance of MyElement is created, and the **before mentioned** methods are called. We also can document.createElement('my-element') in JavaScript.

**Comment by 15demi08** [comment]
That's not a typo.

`aforementioned` can be used to call back to something you have previously written on the same text, without explicitly writing it again.

Check it out: https://dictionary.cambridge.org/dictionary/english/aforementioned
