### ISSUE TITLE
-

### ISSUE THREAD

**Issue by kimobrian** [javascript-tutorial/en.javascript.info#3496]
-

**Comment by iliakan** [comment]
Hello,

That's odd. Usually we reply quite fast. 

When you buy a book, it comes with 1 year of updates. Please let me know, what you expect of us now?

**Comment by kimobrian** [comment]
I was just looking for a way to access the purchase but from what you're said in the email(you don't store old copies) and the link is since expired, seems I've no way of accessing it unless I make a fresh purchase.
