### ISSUE TITLE
Bound function as a method

### ISSUE THREAD

**Issue by adeyems** [javascript-tutorial/en.javascript.info#3517]
```bash
function f() {
    alert(this) // or console.log(this) in NodeJS environment
}

let user = {
    g: f.bind(null)
}

user.g()
```
I did not get null. The Global Object is still displayed. Window in the browser environment and NodeJs Global Object in NodeJS environment.

**Comment by vsemozhetbyt** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind#parameters

> If the function is not in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null) and [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined) will be replaced with the global object

**Comment by adeyems** [comment]
That works. Thanks.
