### ISSUE TITLE
The Headline must be shifted

### ISSUE THREAD

**Issue by narasimha-1511** [javascript-tutorial/en.javascript.info#3584]
The Headline Splice must be shifted below

![jsinfocon](https://github.com/javascript-tutorial/en.javascript.info/assets/129654598/020e7e7a-aadc-462f-af68-f983a8fb7858)

**Comment by narasimha-1511** [comment]
I would like to work on this issue..

**Comment by Alexandre887** [comment]
This text is a kind of introduction to the `splice()` method:

![image](https://github.com/javascript-tutorial/en.javascript.info/assets/74434545/45808ba8-9901-4936-a98d-68bc5858b6f0)

First, it demonstrates the simplest variant that may come to mind. Then it tells about disadvantage of this approach and shows the correct one - using `splice()`.

The article does not require changes, all this text should be in the "splice" paragraph.

Please close this issue,
