### ISSUE TITLE
is correct this statement?

### ISSUE THREAD

**Issue by marvinmendezdevs** [javascript-tutorial/en.javascript.info#3630]
i was reading about weakMap and weakSet and i found this:
![image](https://github.com/javascript-tutorial/en.javascript.info/assets/133824886/7fcbcd01-7ce9-4eb3-ad26-6a6f97d36231)

I think you wanted write: 
Por lo general, las propiedades de un objeto, elementos de un array u otra estructura de datos se consideran accesibles y se mantienen en la memoria mientras esa estructura permanezca **alcanzables**.

**Comment by joaquinelio** [comment]
Uh.
👍

**Comment by joaquinelio** [comment]
Cambié de opinión.
La frase es correcta, quizá confusa.
la supuesta redundancia es adrede. 
Quizas
"Generalmente, mientras la estrctura esta en memoria, sus (elementos...) permanecen en memoria"
Que no es el caso de weakwhatever

**Comment by marvinmendezdevs** [comment]
Muy interesante. Tiene sentido ahora. Muchas gracias.

**Comment by joaquinelio** [comment]
(Hey, we have a Spanish repo)

Just had a debate with "chapití." It finally agreed to leave the original as is but suggested to add the "WeakMap" exception to the original.
I should have fed with the entire article, didnt want to give it that satisfaction.
It won't be "Terminator" but "Idiocracy" the mov that represents our future.

**Comment by joaquinelio** [comment]
>¿sigo este hilo de comentarios?

No es el lugar correcto
El repo es para correcciones del propio repo.
Tampoco hay movimiento en disqus comments
En el home ingles está discord chat.
Si no, podes esperar a q implemente la IA...

**Comment by joaquinelio** [comment]
@smith558 
You may close this as completd
This belongs to the Spanish repo anyway

**Comment by smith558** [comment]
> @smith558 You may close this as completd This belongs to the Spanish repo anyway

Alright. Thanks for the heads up!
