### ISSUE TITLE
Discrepancy in typeof(alert) Result in JavaScript Tutorial

### ISSUE THREAD

**Issue by Aditya-Ramachandran** [javascript-tutorial/en.javascript.info#3666]
#### Description 
In the tutorial, it states that the result of `typeof(alert)` is a `funciton`, but when I tested this on my local machine and another online JavaScript compiler ([Programiz](https://www.programiz.com/javascript/online-compiler/)), the result was consistently `undefined`. This inconsistency is causing confusion, and I believe there might be an error in the tutorial content.

 #### Expected Result:
The tutorial should accurately represent the result of `typeof(alert)` to avoid confusion among learners.

#### Actual Result:
The tutorial claims the result of `typeof(alert)` is a `funciton`, but real-world testing yields 'undefined'.

#### Screenshots 

From testing it on my machine: 
![Screenshot 2024-02-10 200551](https://github.com/javascript-tutorial/en.javascript.info/assets/60959037/5bb84868-805b-40c8-bca6-37beaa68f469)

From the[ tutorial](https://javascript.info/types#type-typeof): 
![Screenshot 2024-02-10 201635](https://github.com/javascript-tutorial/en.javascript.info/assets/60959037/7503131f-3988-47d5-8c27-51dd2cd0bca6)

**Comment by joaquinelio** [comment]
it IS function, in the browser environment.
what the tutorial aims

If you use it outside the browser window environment, "alert" would mean what that environment wants it to be, maybe an undefined variable.

Try console.log( typeof console.log )

**Comment by Aditya-Ramachandran** [comment]
Thank you for the clarification! I understand now that the `typeof(alert)` result is specific to the browser environment.
