### ISSUE TITLE
The image is not loading.

### ISSUE THREAD

**Issue by Mtlekvin** [javascript-tutorial/en.javascript.info#3668]
On https://javascript.info/private-protected-properties-methods  at the beginning of the page the image is not downloading:

![image](https://github.com/javascript-tutorial/en.javascript.info/assets/119450324/f9568d1b-7c5b-407c-8682-0619aea835ce)

**Comment by mones-cse** [comment]
Image is loading just fine 
![image](https://github.com/javascript-tutorial/en.javascript.info/assets/6597869/9f10dfe2-dfe3-445b-8d49-4b35d9da12e0)

**Comment by smith558** [comment]
Can confirm the images are indeed loading just fine. Please reopen if the issue persists. @Mtlekvin Thank you both! @mones-cse @Mtlekvin
