### ISSUE TITLE
Wrong Solution

### ISSUE THREAD

**Issue by HuyNhay** [javascript-tutorial/en.javascript.info#3725]
The solution of [this task](https://javascript.info/task/error-async) about [error handling with promise](https://javascript.info/promise-error-handling) is wrong. The answer should be YES, because regardless of setTimeout, the executor still throws the error object to the catch method, so it still alert the error (i.e the `.catch()` is triggered).

**Comment by iliakan** [comment]
Just tried in console.

<img width="488" alt="image" src="https://github.com/user-attachments/assets/7e71a044-2165-417f-9e06-9d359122d425">
