### ISSUE TITLE
Date example is incorrect

### ISSUE THREAD

**Issue by jesse-bonzo** [javascript-tutorial/en.javascript.info#697]
The example for creating a Date with a string is incorrect:

```
let date = new Date("2017-01-26");
alert(date); // Thu Jan 26 2017 ...
```
Actually alerts
`Wed Jan 25 2017 16:00:00 GMT-0800 (Pacific Standard Time)`

**Comment by iliakan** [comment]
Right, please send PR. That depends on your timezone.

**Comment by 11un** [comment]
I was going to fix this but on inspection it seems correct considering the comment:

```// The time portion of the date is assumed to be midnight GMT and
// is adjusted according to the timezone the code is run in
// So the result could be
// Thu Jan 26 2017 11:00:00 GMT+1100 (Australian Eastern Daylight Time)
// or
// Wed Jan 25 2017 16:00:00 GMT-0800 (Pacific Standard Time)```

**Comment by bikingbadger** [comment]
The comments below explain the difference:
// The time portion of the date is assumed to be midnight GMT and
// is adjusted according to the timezone the code is run in
// So the result could be
// Thu Jan 26 2017 11:00:00 GMT+1100 (Australian Eastern Daylight Time)
// or
// Wed Jan 25 2017 16:00:00 GMT-0800 (Pacific Standard Time)
Is this still an issue or am I missing a detail?
