### ISSUE TITLE
WeakSet chapter - last code snippet

### ISSUE THREAD

**Issue by dagolinuxoid** [javascript-tutorial/en.javascript.info#704]
src: https://javascript.info/map-set-weakmap-weakset#summary
In the last code snippet (right above summary) just scroll a little bit.
// no need to clean unreadSet, it now has 2 items
I think it should be 1 item since we deleted second item(at index1) directly from WeakSet and removed the first one (at index 0) via shift. 
// no need to clean unreadSet, it now has 1 item
But as you've mentioned dev tools don't (or may not) reflect on manipulation with an origin object though (at least immediately) e.g. after messages.length = 0 according to Firefox console unreadSet will contain all items except deleted ones via its delete method. Adding a small note about it can be helpful.

**Comment by iliakan** [comment]
Sorry for the delay, not sure, is the issue still actual? I fixed that article a bit.

**Comment by dagolinuxoid** [comment]
Maybe it doesn't require a correction but I have a question anyway
```js
let messages = [
    {text: "Hello", from: "John"},
    {text: "How goes?", from: "John"},
    {text: "See you soon", from: "Alice"}
];

// fill it with array elements (3 items)
let unreadSet = new WeakSet(messages);

// use unreadSet to see whether a message is unread
alert(unreadSet.has(messages[1])); // true

// remove it from the set after reading 
// update: now unreadSet clearly has two items - since we deleted one item directly
unreadSet.delete(messages[1]); // true

// and when we shift our messages history, the set is cleaned up automatically
messages.shift();
// no need to clean unreadSet, it now has 2 items
// QUESTION: isn't it should be no need to clean unreadSet, it now has 1 item instead?
// because we deleted one item from unreadSet directly and cleaned another one via shift()
// (though technically we don't know for sure when the JS engine clears it)
```

**Comment by iliakan** [comment]
I don't understand your question:
```
// QUESTION: isn't it should be no need to clean unreadSet, it now has 1 item instead?
```
