### ISSUE TITLE
find() and findIndex()

### ISSUE THREAD

**Issue by hjcasayas** [javascript-tutorial/en.javascript.info#712]
The .find() method returns **undefined** while the .findIndex() returns **-1**  when nothing is found.

In the section Array Methods -> Search In Array -> find and findIndex says that the two methods are essentially the same. I think it is worth mentioning that the .findIndex() method returns -1 when nothing is found. I myself have expected that the .findIndex() returns  **undefined**.

![image](https://user-images.githubusercontent.com/43360265/50642619-b2302c00-0fa6-11e9-9ebc-1ce44d4cd19f.png)

**Comment by iliakan** [comment]
Please send a PR to fix this :)

**Comment by Jerwinsamuel** [comment]
@iliakan Hi, this seems to be fixed #741

**Comment by AdarshNaidu** [comment]
This is fixed
