### ISSUE TITLE
Add some additional tests to Throttle task

### ISSUE THREAD

**Issue by dagolinuxoid** [javascript-tutorial/en.javascript.info#716]
I've "solved"  (passed all current provided tests) throttle task, but unfortunately my solution is *wrong* (at least isn't that efficient - it makes few redundant calls). It's not a very important issue although it would be nice to fix it.
srcMyAttempt: [throttle](https://github.com/dagolinuxoid/fccActivityLog/blob/master/0701019/throttle.js)
srcOriginalTask: [throttle task](https://javascript.info/call-apply-decorators#throttle-decorator)

**Comment by iliakan** [comment]
Do you have a suggestion what to fix/add? Maybe submit a PR?

**Comment by dagolinuxoid** [comment]
got it :) The issue isn't that urgent so it can hang for a while. Honestly I'm not strong in writing complicated (heck even regular) tests yet so it's going to be fun. I will submit PR after figuring it out.

**Comment by iliakan** [comment]
@dagolinuxoid would you submit a PR for that?

**Comment by dagolinuxoid** [comment]
Hi! If I'm not going to do something about it until November you can officially give up on me, so there is a hope.

**Comment by dagolinuxoid** [comment]
@iliakan it's been a while =) There is a working solution for node. I don't know why it doesn't work in a browser though.
``` javascript
const assert = require('chai').assert;
const throttle = require('../throttle');

describe('efficiency tests', () => {
  let log = '';
  const f = arg => log += arg;
  const f100 = throttle(f, 100);
  f100('once');

  it('a forwarded call should run just once', done => {
    setTimeout(function() {
      assert.equal(log, 'once');
      done();
    }, 200);
  });
});

**Comment by dagolinuxoid** [comment]
I figured it out. My test is working in browser too. However in order to work it on Plunker it's idex.html file should be modified slightly:
```html
<!doctype html>
<script src="https://en.js.cx/test/libs.js"></script>

<script>
  // ...Your code...
</script>

<script src="test.js"></script>
</html>
```
Placement of srcipts matter : test should be placed *after* a script with 'your code here'.
The repository doesn't have index.html file here (only file with tests) So probably It's best for you to modify the index on Plunker directly so the additional test can be added successfully via PR.
```javascript
describe('efficiency tests', () => {
  let log = '';
  const f = arg => log += arg;
  const f10 = throttle(f, 10);
  f10('once');

  it('a forwarded call should run just once', done => {
    setTimeout(() => {
      assert.equal(log, 'once');
      done();
    }, 20);
  });
});
```

**Comment by iliakan** [comment]
Added the code manually, to ensure it works with a regular `index.html`.
