### ISSUE TITLE
I want more explanation on the article.

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#923]
Hello, I'm translating the article, [Walking the DOM](https://javascript.info/dom-navigation#element-only-navigation).

While I'm translating the sentence, **"Sometimes that matters when we’re walking over the chain of parents and call _a method_ on each of them, but document doesn’t have _it(*1)_, so we exclude _it(*2)_."**, I think I couldn't understand whole context at the end of the sentence. 

I bet the first it(marked as _*1_) represents _a method_ and the second one is too. Is it right? If so, could you explain more about "excluding a method"?

**Comment by iliakan** [comment]
Updated!

**Comment by Violet-Bora-Lee** [comment]
Awesome! Thanks as always:)

**Comment by iliakan** [comment]
Please don't hesitate ask questions and send PRs to the English version =)
Thank you!
