### ISSUE TITLE
The solution to the task on the Class patterns section is missing underscores

### ISSUE THREAD

**Issue by davidbludlow** [javascript-tutorial/en.javascript.info#931]
In the solution of https://javascript.info/class-patterns#rewrite-to-prototypes it says

>Please note that properties that were internal in functional style (template, timer) and the internal method render are marked private with the underscore _.

but when you open the solution in plunker, there are no underscores in clock.js.
![image](https://user-images.githubusercontent.com/5985136/56461297-d9541300-6375-11e9-8400-d060f000ecb5.png)

**Comment by iliakan** [comment]
Rewritten.
