### ISSUE TITLE
Doubtful use of event.code instead of event.key

### ISSUE THREAD

**Issue by mathiasbockwoldt** [javascript-tutorial/en.javascript.info#950]
On the page `2-ui/3-event-details/5-keyboard-events`, you ask if it is better to use event.key or event.code for `Ctrl+Z` and even ask the reader to think carefully about it. Your answer is to use event.code, because it always maps on the same physical key on the keyboard.

I understand your arguments, especially the changes in event.key when Capslock is one etc., but I would be very confused to find an option that is advertised with `Ctrl+Z` on another key, e.g. `Ctrl+Y` on a German keyboard (where `Z` and `Y` are exchanged). The "standard" key combination for "undo" is, also in German, `Ctrl+Z`, although the key between `T` and `U` is used.

So I would argue for using event.key, because I would expect the actual letter `Z` to be the right key to press and not the key that happens to be left of the `X` key.

**Comment by iliakan** [comment]
Did you try it?

**Comment by mathiasbockwoldt** [comment]
Yes, I tried it. When I use the [German keyboard layout](https://en.wikipedia.org/wiki/QWERTZ), I have to press `Ctrl+Y` to get the alert with "Undo!". When I press `Ctrl+Z` nothing happens.

I see that it is of advantage to use the physical key position, for example, in games in which WASD is horrible to play with on a [French keyboard layout](https://en.wikipedia.org/wiki/AZERTY), but in the specific case of the undo action, the key with the `Z` printed on it should be used, not the key that happens to be at the position of the `Z` in the American layout. At least in German, it is common to use `Ctrl+Z` and not `Ctrl+Y` to undo/go back.

**Comment by iliakan** [comment]
That's a good point, I'll add more explanations into tutorial to highlight that!

**Comment by iliakan** [comment]
When you run this code (from the tutorial) and press `ctrl+Y`, it triggers, the code is `KeyZ`, really?
```js
document.addEventListener('keydown', function(event) {
  if (event.code == 'KeyZ' && (event.ctrlKey || event.metaKey)) {
    alert('Undo!')
  }
});
```

**Comment by iliakan** [comment]
There's a statement in the spec: "
```
"KeyZ" | z on a US keyboard.	
Labelled w on an AZERTY (e.g., French) keyboard, 
and y on a QWERTZ (e.g., German) keyboard.
```

**Comment by iliakan** [comment]
Closing it, fixed.
