### ISSUE TITLE
Possibly incomplete sentence in 1-js/02-first-steps/16-javascript-specials/

### ISSUE THREAD

**Issue by pimonenkov** [javascript-tutorial/en.javascript.info#963]
It looks like the sentence below is incomplete.

> The strict equality operator `===` doesn't do the conversion: different types always mean different values for it, so:

This "so:" does not seem to be followed by a logic continuation. The next sentence begins with "Values null and undefined...", which looks like a completely new construction, not associated with the previous one. 

Maybe we should just omit the "so:" part.

**Comment by iliakan** [comment]
fixed thanks
