### ISSUE TITLE
In case of using bundling tools, how inline script is treated?

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#973]
Hello, I have one question regarding the article, **Modules, introduction.**
http://javascript.info/modules-intro

Here is the part of the sentence I couldn't fully understand. 
_~~~ so the resulting build does not require type="module", and we can put it into a regular script:_

I think this phrase explains how inline script is treated when the application is bundled using bundle tools. Could you give me more explanation?

You mean, inline script code is not changed(minified, optimized, and so on) although when the whole modules are bundled?

**Comment by iliakan** [comment]
Added more explanations there. Inline scripts are not usually processed by bundle tools.
