### ISSUE TITLE
terms regarding modules

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#974]
I wonder the differences between native modules and bare modules.
Are these same or not? I think it is by the context of this sentence, "That said, native modules are also usable. So we won't be using Webpack here: you can configure it later" in the tutorial.

**Comment by iliakan** [comment]
Where did you find "bare" modules?

**Comment by iliakan** [comment]
Added more explanations =) Thanks!

**Comment by Violet-Bora-Lee** [comment]
Awesome! Thanks :) Have a great day.
