### ISSUE TITLE
inline, internal, external, dynamic, and embedded JS code

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#976]
While I was asking some questions to you, I wondered the definition of the terms inline, internal, external, dynamic, embedded JavaScript code.

I've found a good article explaining these terms in the [link](https://slideplayer.com/slide/5842779/).

Could you write the article regarding these terms?

**Comment by iliakan** [comment]
Did I get the problem correctly:
- We're not explaining them in the tutorial.
- But still using in ... modules?

**Comment by Violet-Bora-Lee** [comment]
Yes. It'd better to define trems in the article. It's just my opinion. If you think the readers wouldn't feel the same I felt, it's okay not to update the article :)

**Comment by iliakan** [comment]
Where exactly the problem with understanding occurs?

**Comment by iliakan** [comment]
@Violet-Bora-Lee up =)
I'm not leaving this out 👂

**Comment by Violet-Bora-Lee** [comment]
I don't have a problem to understand the tutorial so far but I suggest to add the explanations about the terms I mentioned.  I'm kinda person obsessed with definitions all the time lol.

**Comment by iliakan** [comment]
I understand the concern. I'm just trying to find the exact place where such definitions are needed.

**Comment by Violet-Bora-Lee** [comment]
How about this place? http://javascript.info/loading

**Comment by iliakan** [comment]
External scripts are described here: http://javascript.info/hello-world#external-scripts

**Comment by Violet-Bora-Lee** [comment]
Then, this place is THE place to insert the information!

**Comment by iliakan** [comment]
You mean, we should put the definitions in both places?

**Comment by Violet-Bora-Lee** [comment]
No. I mean it's good place to define the terms but external script. It's only my suggestion. :)

**Comment by iliakan** [comment]
Ok thank you, I'll see around if all definitions are at place in the starting chapters.
