### ISSUE TITLE
Internal timer on Chrome brower when I use alert.

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#990]
The contents of a smart header, **Modal windows freeze time in Chrome/Opera/Safari**, need to be updated In the article [Scheduling: setTimeout and setInterval](https://javascript.info/settimeout-setinterval).

I've tested on Chrome and the timer did't frozen.

**Comment by iliakan** [comment]
Yep, Chrome changed. Thanks!

**Comment by Violet-Bora-Lee** [comment]
I THANK YOU 💯 👍 🥇 It's awesome to join, contribute, improve articles with you!

**Comment by iliakan** [comment]
Thank's a lot, @Violet-Bora-Lee ! I wish I understood Korean to read your translation :)
